#![forbid(unsafe_code)]
//! Integration contract tests for CAP- fixtures H.264/rtpdump (fss-2h5zq.4).
//!
//! Acceptance criteria:
//! - cargo test -p fss-reference --test media_fixture_h264_contract passes
//! - regeneration identity for committed fixtures byte-for-byte against pinned hashes
//! - F2: asserts S on first FU-A fragment, E on last, and fragment contiguity (mutant M1 killer)
//! - F3: non-default params (gop_size < frame_count) exact NAL equivalence
//! - Tamper detection: mutating any fixture byte fails verification

use std::error::Error;
use std::fs;
use std::path::PathBuf;

use fss_core::ContentDigest;
use fss_packet::{
    H264Depacketizer, H264Limits, H264Mode, PacketLimits, RtpPacket, SequenceTracker, StreamKey,
};
use fss_reference::media_fixture::{
    H264FixtureParams, MEDIA_FIXTURE_NOTE, MediaFixtureError, RD_HDR_LEN, RD_PKT_HDR_LEN,
    RTPDUMP_MAGIC_HEADER, RtpdumpFixture, RtpdumpParams, build_h264_manifest_json,
    build_rtp_manifest_json, generate_h264_annexb, generate_rtpdump_clean,
    generate_rtpdump_duplicate, generate_rtpdump_large_gap, generate_rtpdump_loss,
    generate_rtpdump_reorder, generate_rtpdump_ssrc_reset, generate_rtpdump_truncated_last_record,
    verify_fixture_manifest,
};

const PINNED_SHA256_H264_CLEAN: &str =
    "f2c3a1c28f52194510f94cac342bb0b27cc933d04d09f7ff2431112134d25f8f";
const PINNED_SHA256_RTP_CLEAN: &str =
    "d6ffdc3a6f1ffb7a4f7b14b919e711a15fe8485115fa80676091a097307bf1fc";
const PINNED_SHA256_RTP_LOSS: &str =
    "173f2dfc63f5240e6ec66285ae959115785830aa24c1ebdb6ffb3953b33f06af";
const PINNED_SHA256_RTP_REORDER: &str =
    "217b6937562a7945dbdd976a8ed74d22ebe5f6d7ab013c11c262ac305b85d183";
const PINNED_SHA256_RTP_DUPLICATE: &str =
    "133cdc8b65384fc1416de6b2d43ad5b04f4d5190f2400b62ca66d86103c59948";
const PINNED_SHA256_RTP_SSRC_RESET: &str =
    "9f3b4d7ba3414a2d09cd3be7262d1f48c01e744da405b1c20cf2489b2a05e3d8";
const PINNED_SHA256_RTP_TRUNCATED: &str =
    "d7a35c3eee2b210966164aadd68f8c0f6a41099b1a451f8fca30f136ba1ba42c";
const PINNED_SHA256_RTP_LARGE_GAP: &str =
    "13b695dd9b62bf66072ccb1508f32636e4f135d1b184a16f3caab8226f13c142";

fn repo_root() -> Result<PathBuf, Box<dyn Error>> {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .map(PathBuf::from)
        .ok_or("cannot find repo root")?;
    Ok(p)
}

fn to_hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        use std::fmt::Write;
        let _ = write!(s, "{b:02x}");
    }
    s
}

fn parse_rtpdump_records(bytes: &[u8]) -> (Vec<Vec<u8>>, bool) {
    let mut o = match bytes.iter().position(|&b| b == b'\n') {
        Some(p) => p + 1 + 16,
        None => return (Vec::new(), true),
    };
    let mut out = Vec::new();
    while o < bytes.len() {
        if o + 8 > bytes.len() {
            return (out, true);
        }
        let len = usize::from(u16::from_be_bytes([bytes[o], bytes[o + 1]]));
        if o + len > bytes.len() || len < 8 {
            return (out, true);
        }
        out.push(bytes[o + 8..o + len].to_vec());
        o += len;
    }
    (out, false)
}

#[test]
fn test_media_fixture_h264_regeneration_identity() -> Result<(), Box<dyn Error>> {
    let h264_params = H264FixtureParams::default();
    let annexb = generate_h264_annexb(&h264_params)?;
    let rtp_params = RtpdumpParams::default();

    let clean = generate_rtpdump_clean(&annexb, &rtp_params)?;
    let loss = generate_rtpdump_loss(&annexb, &rtp_params)?;
    let reorder = generate_rtpdump_reorder(&annexb, &rtp_params)?;
    let duplicate = generate_rtpdump_duplicate(&annexb, &rtp_params)?;
    let ssrc_reset = generate_rtpdump_ssrc_reset(&annexb, &rtp_params)?;
    let truncated = generate_rtpdump_truncated_last_record(&annexb, &rtp_params)?;
    let large_gap = generate_rtpdump_large_gap(&annexb, &rtp_params)?;

    let root = repo_root()?;

    // Check clean.264
    let h264_file = root.join("tests/fixtures/media/h264/clean.264");
    assert!(h264_file.is_file(), "clean.264 must exist on disk");
    let on_disk_264 = fs::read(&h264_file)?;
    assert_eq!(
        on_disk_264, annexb.bytes,
        "clean.264 must match regenerated bytes"
    );
    let digest_264 = to_hex(&ContentDigest::sha256(&on_disk_264).bytes());
    assert_eq!(digest_264, PINNED_SHA256_H264_CLEAN);

    // Check all 7 RTP fixtures
    let rtp_fixtures: [(&str, &RtpdumpFixture, &str); 7] = [
        ("clean.rtp", &clean, PINNED_SHA256_RTP_CLEAN),
        ("loss.rtp", &loss, PINNED_SHA256_RTP_LOSS),
        ("reorder.rtp", &reorder, PINNED_SHA256_RTP_REORDER),
        ("duplicate.rtp", &duplicate, PINNED_SHA256_RTP_DUPLICATE),
        ("ssrc_reset.rtp", &ssrc_reset, PINNED_SHA256_RTP_SSRC_RESET),
        (
            "truncated_last_record.rtp",
            &truncated,
            PINNED_SHA256_RTP_TRUNCATED,
        ),
        ("large_gap.rtp", &large_gap, PINNED_SHA256_RTP_LARGE_GAP),
    ];

    for (fname, fix, pinned_sha) in rtp_fixtures {
        let rtp_path = root.join("tests/fixtures/media/rtp").join(fname);
        assert!(rtp_path.is_file(), "{fname} must exist on disk");
        let on_disk = fs::read(&rtp_path)?;
        assert_eq!(
            on_disk, fix.bytes,
            "committed {fname} must match regenerated bytes byte-for-byte"
        );
        let digest_on_disk = to_hex(&ContentDigest::sha256(&on_disk).bytes());
        assert_eq!(digest_on_disk, pinned_sha);
    }
    println!(r#"CAPLOG {{"step": "media_fixture_h264_regeneration_identity", "verdict": "pass"}}"#);
    Ok(())
}

#[test]
fn test_media_fixture_h264_manifest_integrity() -> Result<(), Box<dyn Error>> {
    let root = repo_root()?;
    let h264_params = H264FixtureParams::default();
    let annexb = generate_h264_annexb(&h264_params)?;
    let h264_man_path = root.join("tests/fixtures/media/h264/fixture_manifest.json");
    let h264_man_disk = fs::read_to_string(&h264_man_path)?;
    let h264_man_regen = build_h264_manifest_json(&annexb, &h264_params, "clean.264");
    assert_eq!(h264_man_disk, h264_man_regen);
    assert!(h264_man_disk.contains(MEDIA_FIXTURE_NOTE));

    let rtp_params = RtpdumpParams::default();
    let clean = generate_rtpdump_clean(&annexb, &rtp_params)?;
    let loss = generate_rtpdump_loss(&annexb, &rtp_params)?;
    let reorder = generate_rtpdump_reorder(&annexb, &rtp_params)?;
    let duplicate = generate_rtpdump_duplicate(&annexb, &rtp_params)?;
    let ssrc_reset = generate_rtpdump_ssrc_reset(&annexb, &rtp_params)?;
    let truncated = generate_rtpdump_truncated_last_record(&annexb, &rtp_params)?;
    let large_gap = generate_rtpdump_large_gap(&annexb, &rtp_params)?;
    let all_fixtures = [
        clean, loss, reorder, duplicate, ssrc_reset, truncated, large_gap,
    ];

    let rtp_man_path = root.join("tests/fixtures/media/rtp/fixture_manifest.json");
    let rtp_man_disk = fs::read_to_string(&rtp_man_path)?;
    let rtp_man_regen = build_rtp_manifest_json(&all_fixtures, &rtp_params);
    assert_eq!(rtp_man_disk, rtp_man_regen);
    assert!(rtp_man_disk.contains(MEDIA_FIXTURE_NOTE));

    println!(r#"CAPLOG {{"step": "media_fixture_h264_manifest_integrity", "verdict": "pass"}}"#);
    Ok(())
}

#[test]
fn test_media_fixture_h264_fua_contiguity_and_markers() -> Result<(), Box<dyn Error>> {
    let h264_params = H264FixtureParams::default();
    let annexb = generate_h264_annexb(&h264_params)?;
    let rtp_params = RtpdumpParams::default();
    let clean = generate_rtpdump_clean(&annexb, &rtp_params)?;

    let mut offset = RTPDUMP_MAGIC_HEADER.len() + RD_HDR_LEN;
    let mut rtp_packets = Vec::new();
    while offset + RD_PKT_HDR_LEN <= clean.bytes.len() {
        let length = u16::from_be_bytes([clean.bytes[offset], clean.bytes[offset + 1]]) as usize;
        let rtp_bytes = &clean.bytes[offset + RD_PKT_HDR_LEN..offset + length];
        rtp_packets.push(rtp_bytes);
        offset += length;
    }

    assert_eq!(rtp_packets.len(), clean.packets.len());

    let mut found_fua = false;
    let mut in_fua = false;
    let mut fua_inner_type = 0u8;
    for (idx, rtp_wire) in rtp_packets.iter().enumerate() {
        assert!(rtp_wire.len() >= 12);
        let m_bit = (rtp_wire[1] & 0x80) != 0;
        let payload = &rtp_wire[12..];
        assert!(!payload.is_empty());

        let nal_header = payload[0];
        let nal_type = nal_header & 0x1f;

        if nal_type == 28 {
            found_fua = true;
            assert!(payload.len() >= 2);
            let fu_header = payload[1];
            let s_bit = (fu_header & 0x80) != 0;
            let e_bit = (fu_header & 0x40) != 0;
            let r_bit = (fu_header & 0x20) != 0;

            assert!(!r_bit, "pkt {idx}: FU-A reserved bit must be 0");
            assert!(
                !(s_bit && e_bit),
                "pkt {idx}: FU-A S and E cannot both be set"
            );
            let inner_type = fu_header & 0x1f;
            assert!(
                (1..=23).contains(&inner_type),
                "pkt {idx}: FU-A inner type {inner_type} must be valid"
            );

            // F2 / M1 guard: assert S on first fragment, E on last, and fragment contiguity
            if !in_fua {
                assert!(
                    s_bit,
                    "pkt {idx}: first FU-A fragment must have S bit set (M1 guard)"
                );
                assert!(
                    !e_bit,
                    "pkt {idx}: first FU-A fragment must not have E bit set"
                );
                in_fua = true;
                fua_inner_type = inner_type;
            } else {
                assert!(
                    !s_bit,
                    "pkt {idx}: continuation FU-A fragment must not have S bit set (M1 guard)"
                );
                assert_eq!(
                    inner_type, fua_inner_type,
                    "pkt {idx}: FU-A continuation fragment inner type {inner_type} differs from start {fua_inner_type}"
                );
                if e_bit {
                    in_fua = false;
                }
            }

            if m_bit {
                assert!(
                    e_bit,
                    "pkt {idx}: RTP marker bit on FU-A packet may only be set if FU-A E bit is set"
                );
            }
        } else {
            assert!(
                !in_fua,
                "pkt {idx}: non-FU-A packet while FU-A sequence is incomplete"
            );
        }
    }
    assert!(!in_fua, "FU-A sequence did not terminate with an E bit");
    assert!(found_fua, "clean.rtp must exercise FU-A fragmentation");

    println!(
        r#"CAPLOG {{"step": "media_fixture_h264_fua_contiguity_and_markers", "verdict": "pass"}}"#
    );
    Ok(())
}

#[test]
fn test_media_fixture_h264_non_default_params_nal_equivalence() -> Result<(), Box<dyn Error>> {
    let test_configs = [(6, 2), (5, 1), (7, 3)];

    for (frame_count, gop_size) in test_configs {
        let hp = H264FixtureParams {
            seed: 9999,
            frame_count,
            gop_size,
            include_aud: true,
            include_sei: true,
            two_slice_au: true,
            force_emulation_prevention: true,
            trailing_zeros: 1,
        };
        let annexb = generate_h264_annexb(&hp)?;
        let rp = RtpdumpParams::default();
        let clean = generate_rtpdump_clean(&annexb, &rp)?;

        let (recs, trunc) = parse_rtpdump_records(&clean.bytes);
        assert!(!trunc);

        let key = StreamKey {
            ingress: 1,
            generation: 1,
            ssrc: rp.ssrc,
        };
        let mut tracker = SequenceTracker::new(key, rp.payload_type).map_err(|e| format!("{e}"))?;
        let mut depack = H264Depacketizer::new(
            key,
            rp.payload_type,
            H264Mode::NonInterleaved,
            H264Limits::default(),
        )
        .map_err(|e| format!("{e}"))?;

        let mut delivered = Vec::new();
        for (idx, rec) in recs.iter().enumerate() {
            let pkt = RtpPacket::parse(rec, PacketLimits::default())?;
            let obs = tracker.observe(key, pkt).map_err(|e| format!("{e}"))?;
            if let Some(ext) = obs.extended_sequence {
                let out = depack
                    .push(key, ext, pkt, idx as u64 * 1_000_000)
                    .map_err(|e| format!("{e}"))?;
                for n in &out.nals {
                    delivered.push(n.bytes().to_vec());
                }
            }
        }

        let annex: Vec<Vec<u8>> = annexb.nals.iter().map(|n| n.wire_bytes.clone()).collect();
        assert_eq!(
            delivered, annex,
            "exact NAL equivalence failed for frame_count={frame_count}, gop_size={gop_size}"
        );
    }

    println!(
        r#"CAPLOG {{"step": "media_fixture_h264_non_default_params_nal_equivalence", "verdict": "pass"}}"#
    );
    Ok(())
}

#[test]
fn test_media_fixture_h264_tamper_detection() -> Result<(), Box<dyn Error>> {
    let root = repo_root()?;
    let h264_man_path = root.join("tests/fixtures/media/h264/fixture_manifest.json");
    let h264_manifest = fs::read_to_string(&h264_man_path)?;
    let h264_file = root.join("tests/fixtures/media/h264/clean.264");
    let clean_264 = fs::read(&h264_file)?;

    // Untampered Annex-B fixture verification succeeds
    verify_fixture_manifest(&h264_manifest, "clean.264", &clean_264)?;

    // Mutating a single byte in Annex-B stream causes typed DigestMismatch
    let mut tampered_bytes = clean_264;
    assert!(!tampered_bytes.is_empty());
    tampered_bytes[10] ^= 0xff;
    let err_264 = verify_fixture_manifest(&h264_manifest, "clean.264", &tampered_bytes);
    assert!(
        matches!(err_264, Err(MediaFixtureError::DigestMismatch { .. })),
        "tampered Annex-B fixture must fail manifest check with typed DigestMismatch, got: {err_264:?}"
    );

    let rtp_man_path = root.join("tests/fixtures/media/rtp/fixture_manifest.json");
    let rtp_manifest = fs::read_to_string(&rtp_man_path)?;
    let rtp_file = root.join("tests/fixtures/media/rtp/clean.rtp");
    let clean_rtp = fs::read(&rtp_file)?;

    // Untampered RTP fixture verification succeeds
    verify_fixture_manifest(&rtp_manifest, "clean.rtp", &clean_rtp)?;

    // Mutating a single byte in clean.rtp causes typed DigestMismatch
    let mut tampered_rtp = clean_rtp;
    assert!(!tampered_rtp.is_empty());
    tampered_rtp[50] ^= 0x01;
    let err_rtp = verify_fixture_manifest(&rtp_manifest, "clean.rtp", &tampered_rtp);
    assert!(
        matches!(err_rtp, Err(MediaFixtureError::DigestMismatch { .. })),
        "tampered RTP fixture must fail manifest check with typed DigestMismatch, got: {err_rtp:?}"
    );

    println!(r#"CAPLOG {{"step": "media_fixture_h264_tamper_detection", "verdict": "pass"}}"#);
    Ok(())
}
