//! CABAC context layout (one offset per context-coded syntax element),
//! context initialisation values and arithmetic-engine tables of ITU-T
//! H.265 clause 9.3.
// GENERATED by scripts/generate_h265_cabac_tables.py from FFmpeg n8.0.1
// libavcodec/hevc/cabac.c and libavcodec/cabac.c (transcriptions of ITU-T
// H.265 Tables 9-5..9-37, 9-52 and 9-53). Do not edit by hand; regenerate.
// Spec entries are re-checked by hand in cabac.rs tests.

/// Number of context variables (all syntax elements, clause 9.3.2.2).
pub const CTX_COUNT: usize = 179;

/// First context of `sao_merge_flag` (1 context).
pub const SAO_MERGE_FLAG: usize = 0;
/// First context of `sao_type_idx` (1 context).
pub const SAO_TYPE_IDX: usize = 1;
/// First context of `split_coding_unit_flag` (3 contexts).
pub const SPLIT_CODING_UNIT_FLAG: usize = 2;
/// First context of `cu_transquant_bypass_flag` (1 context).
pub const CU_TRANSQUANT_BYPASS_FLAG: usize = 5;
/// First context of `skip_flag` (3 contexts).
pub const SKIP_FLAG: usize = 6;
/// First context of `cu_qp_delta` (3 contexts).
pub const CU_QP_DELTA: usize = 9;
/// First context of `pred_mode_flag` (1 context).
pub const PRED_MODE_FLAG: usize = 12;
/// First context of `part_mode` (4 contexts).
pub const PART_MODE: usize = 13;
/// First context of `prev_intra_luma_pred_flag` (1 context).
pub const PREV_INTRA_LUMA_PRED_FLAG: usize = 17;
/// First context of `intra_chroma_pred_mode` (2 contexts).
pub const INTRA_CHROMA_PRED_MODE: usize = 18;
/// First context of `merge_flag` (1 context).
pub const MERGE_FLAG: usize = 20;
/// First context of `merge_idx` (1 context).
pub const MERGE_IDX: usize = 21;
/// First context of `inter_pred_idc` (5 contexts).
pub const INTER_PRED_IDC: usize = 22;
/// First context of `ref_idx_l0` (2 contexts).
pub const REF_IDX_L0: usize = 27;
/// First context of `ref_idx_l1` (2 contexts).
pub const REF_IDX_L1: usize = 29;
/// First context of `abs_mvd_greater0_flag` (2 contexts).
pub const ABS_MVD_GREATER0_FLAG: usize = 31;
/// First context of `abs_mvd_greater1_flag` (2 contexts).
pub const ABS_MVD_GREATER1_FLAG: usize = 33;
/// First context of `mvp_lx_flag` (1 context).
pub const MVP_LX_FLAG: usize = 35;
/// First context of `no_residual_data_flag` (1 context).
pub const NO_RESIDUAL_DATA_FLAG: usize = 36;
/// First context of `split_transform_flag` (3 contexts).
pub const SPLIT_TRANSFORM_FLAG: usize = 37;
/// First context of `cbf_luma` (2 contexts).
pub const CBF_LUMA: usize = 40;
/// First context of `cbf_cb_cr` (5 contexts).
pub const CBF_CB_CR: usize = 42;
/// First context of `transform_skip_flag` (2 contexts).
pub const TRANSFORM_SKIP_FLAG: usize = 47;
/// First context of `last_significant_coeff_x_prefix` (18 contexts).
pub const LAST_SIGNIFICANT_COEFF_X_PREFIX: usize = 53;
/// First context of `last_significant_coeff_y_prefix` (18 contexts).
pub const LAST_SIGNIFICANT_COEFF_Y_PREFIX: usize = 71;
/// First context of `significant_coeff_group_flag` (4 contexts).
pub const SIGNIFICANT_COEFF_GROUP_FLAG: usize = 89;
/// First context of `significant_coeff_flag` (44 contexts).
pub const SIGNIFICANT_COEFF_FLAG: usize = 93;
/// First context of `coeff_abs_level_greater1_flag` (24 contexts).
pub const COEFF_ABS_LEVEL_GREATER1_FLAG: usize = 137;
/// First context of `coeff_abs_level_greater2_flag` (6 contexts).
pub const COEFF_ABS_LEVEL_GREATER2_FLAG: usize = 161;

/// initValue per context, indexed by initType 0 (I), 1 and 2.
pub static INIT_VALUES: [[u8; CTX_COUNT]; 3] = [
    [
    153, 200, 139, 141, 157, 154, 154, 154, 154, 154, 154, 154, 154, 184, 154, 154,
    154, 184, 63, 139, 154, 154, 154, 154, 154, 154, 154, 154, 154, 154, 154, 154,
    154, 154, 154, 154, 154, 153, 138, 138, 111, 141, 94, 138, 182, 154, 154, 139,
    139, 139, 139, 139, 139, 110, 110, 124, 125, 140, 153, 125, 127, 140, 109, 111,
    143, 127, 111, 79, 108, 123, 63, 110, 110, 124, 125, 140, 153, 125, 127, 140,
    109, 111, 143, 127, 111, 79, 108, 123, 63, 91, 171, 134, 141, 111, 111, 125,
    110, 110, 94, 124, 108, 124, 107, 125, 141, 179, 153, 125, 107, 125, 141, 179,
    153, 125, 107, 125, 141, 179, 153, 125, 140, 139, 182, 182, 152, 136, 152, 136,
    153, 136, 139, 111, 136, 139, 111, 141, 111, 140, 92, 137, 138, 140, 152, 138,
    139, 153, 74, 149, 92, 139, 107, 122, 152, 140, 179, 166, 182, 140, 227, 122,
    197, 138, 153, 136, 167, 152, 152, 154, 154, 154, 154, 154, 154, 154, 154, 154,
    154, 154, 154,
    ],
    [
    153, 185, 107, 139, 126, 154, 197, 185, 201, 154, 154, 154, 149, 154, 139, 154,
    154, 154, 152, 139, 110, 122, 95, 79, 63, 31, 31, 153, 153, 153, 153, 140,
    198, 140, 198, 168, 79, 124, 138, 94, 153, 111, 149, 107, 167, 154, 154, 139,
    139, 139, 139, 139, 139, 125, 110, 94, 110, 95, 79, 125, 111, 110, 78, 110,
    111, 111, 95, 94, 108, 123, 108, 125, 110, 94, 110, 95, 79, 125, 111, 110,
    78, 110, 111, 111, 95, 94, 108, 123, 108, 121, 140, 61, 154, 155, 154, 139,
    153, 139, 123, 123, 63, 153, 166, 183, 140, 136, 153, 154, 166, 183, 140, 136,
    153, 154, 166, 183, 140, 136, 153, 154, 170, 153, 123, 123, 107, 121, 107, 121,
    167, 151, 183, 140, 151, 183, 140, 140, 140, 154, 196, 196, 167, 154, 152, 167,
    182, 182, 134, 149, 136, 153, 121, 136, 137, 169, 194, 166, 167, 154, 167, 137,
    182, 107, 167, 91, 122, 107, 167, 154, 154, 154, 154, 154, 154, 154, 154, 154,
    154, 154, 154,
    ],
    [
    153, 160, 107, 139, 126, 154, 197, 185, 201, 154, 154, 154, 134, 154, 139, 154,
    154, 183, 152, 139, 154, 137, 95, 79, 63, 31, 31, 153, 153, 153, 153, 169,
    198, 169, 198, 168, 79, 224, 167, 122, 153, 111, 149, 92, 167, 154, 154, 139,
    139, 139, 139, 139, 139, 125, 110, 124, 110, 95, 94, 125, 111, 111, 79, 125,
    126, 111, 111, 79, 108, 123, 93, 125, 110, 124, 110, 95, 94, 125, 111, 111,
    79, 125, 126, 111, 111, 79, 108, 123, 93, 121, 140, 61, 154, 170, 154, 139,
    153, 139, 123, 123, 63, 124, 166, 183, 140, 136, 153, 154, 166, 183, 140, 136,
    153, 154, 166, 183, 140, 136, 153, 154, 170, 153, 138, 138, 122, 121, 122, 121,
    167, 151, 183, 140, 151, 183, 140, 140, 140, 154, 196, 167, 167, 154, 152, 167,
    182, 182, 134, 149, 136, 153, 121, 136, 122, 169, 208, 166, 167, 154, 152, 167,
    182, 107, 167, 91, 107, 107, 167, 154, 154, 154, 154, 154, 154, 154, 154, 154,
    154, 154, 154,
    ],
];

/// rangeTabLps[pStateIdx][qRangeIdx] (Table 9-52).
pub static RANGE_TAB_LPS: [[u8; 4]; 64] = [
    [128, 176, 208, 240],
    [128, 167, 197, 227],
    [128, 158, 187, 216],
    [123, 150, 178, 205],
    [116, 142, 169, 195],
    [111, 135, 160, 185],
    [105, 128, 152, 175],
    [100, 122, 144, 166],
    [95, 116, 137, 158],
    [90, 110, 130, 150],
    [85, 104, 123, 142],
    [81, 99, 117, 135],
    [77, 94, 111, 128],
    [73, 89, 105, 122],
    [69, 85, 100, 116],
    [66, 80, 95, 110],
    [62, 76, 90, 104],
    [59, 72, 86, 99],
    [56, 69, 81, 94],
    [53, 65, 77, 89],
    [51, 62, 73, 85],
    [48, 59, 69, 80],
    [46, 56, 66, 76],
    [43, 53, 63, 72],
    [41, 50, 59, 69],
    [39, 48, 56, 65],
    [37, 45, 54, 62],
    [35, 43, 51, 59],
    [33, 41, 48, 56],
    [32, 39, 46, 53],
    [30, 37, 43, 50],
    [29, 35, 41, 48],
    [27, 33, 39, 45],
    [26, 31, 37, 43],
    [24, 30, 35, 41],
    [23, 28, 33, 39],
    [22, 27, 32, 37],
    [21, 26, 30, 35],
    [20, 24, 29, 33],
    [19, 23, 27, 31],
    [18, 22, 26, 30],
    [17, 21, 25, 28],
    [16, 20, 23, 27],
    [15, 19, 22, 25],
    [14, 18, 21, 24],
    [14, 17, 20, 23],
    [13, 16, 19, 22],
    [12, 15, 18, 21],
    [12, 14, 17, 20],
    [11, 14, 16, 19],
    [11, 13, 15, 18],
    [10, 12, 15, 17],
    [10, 12, 14, 16],
    [9, 11, 13, 15],
    [9, 11, 12, 14],
    [8, 10, 12, 14],
    [8, 9, 11, 13],
    [7, 9, 11, 12],
    [7, 9, 10, 12],
    [7, 8, 10, 11],
    [6, 8, 9, 11],
    [6, 7, 9, 10],
    [6, 7, 8, 9],
    [2, 2, 2, 2],
];

/// transIdxLps[pStateIdx] (Table 9-53).
pub static TRANS_IDX_LPS: [u8; 64] = [
    0, 0, 1, 2, 2, 4, 4, 5, 6, 7, 8, 9, 9, 11, 11, 12,
    13, 13, 15, 15, 16, 16, 18, 18, 19, 19, 21, 21, 22, 22, 23, 24,
    24, 25, 26, 26, 27, 27, 28, 29, 29, 30, 30, 30, 31, 32, 32, 33,
    33, 33, 34, 34, 35, 35, 35, 36, 36, 36, 37, 37, 37, 38, 38, 63,
];

/// transIdxMps[pStateIdx] (Table 9-53).
pub static TRANS_IDX_MPS: [u8; 64] = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
    17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
    33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
    49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 62, 63,
];
