#![forbid(unsafe_code)]
//! H.265/HEVC Main-profile pixel decode (8-bit 4:2:0), scalar reference
//! implementation.
//!
//! NAL units enter, reconstructed 8-bit 4:2:0 pictures leave in output
//! (display) order, with every stage bounded, deterministic, and
//! typed-error on hostile input.
//!
//! Stage map, in decode order:
//! 1. [`nal`] — two-byte NAL header, emulation-prevention removal.
//! 2. [`bits`] — bounds-checked bit reader with `ue(v)` / `se(v)`.
//! 3. [`params`] / [`slice`] — VPS/SPS/PPS (profile, conformance window,
//!    scaling lists, short-term reference picture sets, VUI) and slice
//!    segment headers.
//! 4. [`cabac`] — the CABAC arithmetic decoder and context initialisation
//!    (clause 9.3), with tables generated from the oracle's transcription.
//! 5. `ctu` / `residual` — the coding quadtree (CTU, CU, PU and TU
//!    splits), residual coding with sign data hiding, PCM.
//! 6. `intra` / `transform` — planar, DC and 33 angular predictions with
//!    reference substitution and (strong) smoothing; scaling lists,
//!    transform skip, the 4x4 DST and 4..32 DCTs.
//! 7. `inter` — merge (spatial, temporal, combined bi-predictive, zero
//!    candidates) and AMVP motion vectors with POC-distance scaling and
//!    collocated temporal prediction; 8-tap luma / 4-tap chroma
//!    interpolation; default and explicit weighted prediction.
//! 8. [`decoder`] — the streaming [`Decoder`]: parameter-set store,
//!    picture order count, reference picture set marking, reference list
//!    construction (with list modification) and the decoded picture
//!    buffer's output (bumping) process.
//!
//! Admitted tool set: Main (and Main Still Picture) profile, 8-bit 4:2:0,
//! I, P and B slices (all partition modes incl. AMP), short-term
//! reference pictures, one or more slices per picture in raster order, wavefront
//! parallel processing (`entropy_coding_sync_enabled_flag`), scaling
//! lists, transform skip, transquant bypass, PCM, sign data hiding and
//! constrained intra prediction. Everything else is refused with
//! [`DecodeError::Unsupported`] naming the feature: other profiles, chroma
//! formats and bit depths, the range / multilayer / 3D / screen-content
//! extensions, tiles, dependent slice segments, field-coded (SEI-based
//! interlaced) sequences and layers above the base layer.
//!
//! Correctness is established differentially: tests compare every decoded
//! frame bit-exactly, in output order, against digests produced offline by
//! the sealed FFmpeg laboratory oracle (never invoked at runtime or by
//! tests).

pub mod bits;
pub mod cabac;
// Generated by scripts/generate_h265_cabac_tables.py; kept byte-identical
// to the generator output rather than reflowed by rustfmt.
#[rustfmt::skip]
pub mod cabac_tables;
mod ctu;
pub mod decoder;
mod inter;
mod intra;
pub mod nal;
pub mod params;
pub mod picture;
mod residual;
pub mod slice;
mod tables;
mod transform;

pub use decoder::{Decoder, DecoderLimits, annex_b_nal_units};
pub use picture::Picture;

/// A coding tool or stream property outside the admitted tool set. Refusal
/// is explicit: the decoder never emits approximate pixels for these.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UnsupportedFeature {
    /// A profile other than Main or Main Still Picture (Main 10, the
    /// range extensions profiles, screen content coding, ...).
    Profile,
    /// Anything but 8-bit 4:2:0: monochrome, 4:2:2, 4:4:4, separate colour
    /// planes, or a luma/chroma bit depth above 8.
    SampleFormat,
    /// SPS/PPS range extension syntax (`sps_range_extension_flag`,
    /// `pps_range_extension_flag`).
    RangeExtension,
    /// Screen content coding extension syntax.
    ScreenContent,
    /// Multilayer / 3D extension syntax, or a NAL unit above the base layer
    /// (`nuh_layer_id > 0`).
    MultiLayer,
    /// `tiles_enabled_flag`.
    Tiles,
    /// `dependent_slice_segments_enabled_flag` with a dependent segment.
    DependentSlices,
    /// Field-coded sequences (`field_seq_flag`, SEI-signalled interlace).
    Interlaced,
    /// Historical: P and B slices. Admitted since inter prediction support;
    /// no longer produced, kept for API stability.
    InterPrediction,
    /// Enabled in-loop filters (deblocking or sample adaptive offset).
    LoopFilter,
    /// Long-term reference pictures.
    LongTermReference,
}

/// Typed decode failure for this crate. An error never publishes a
/// partially reconstructed picture.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DecodeError {
    /// The NAL, its payload, or a decoder budget violated a hard bound.
    Limit,
    /// Structural corruption (impossible syntax, out-of-range values,
    /// truncation, a CABAC stream that does not end where it must).
    Malformed,
    /// A NAL of an unexpected type reached this stage.
    UnexpectedNal,
    /// Syntax declared by the stream exceeds the admitted tool set.
    Unsupported(UnsupportedFeature),
    /// A slice referenced a VPS/SPS/PPS id that has not been received.
    MissingParameterSet,
    /// A picture's reference picture set named a picture that is not in the
    /// decoded picture buffer (e.g. decoding started without an IRAP
    /// picture, or after a refused picture).
    MissingReference,
    /// A picture ended (new picture or flush) before all its coding tree
    /// units were decoded; the partial picture is discarded, not concealed.
    IncompletePicture,
}

impl std::fmt::Display for DecodeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Limit => write!(f, "h265 decode input exceeded hard limits"),
            Self::Malformed => write!(f, "h265 bitstream is structurally malformed"),
            Self::UnexpectedNal => write!(f, "unexpected nal unit type at this decode stage"),
            Self::Unsupported(feature) => {
                write!(f, "h265 syntax outside the admitted tool set: {feature:?}")
            }
            Self::MissingParameterSet => write!(f, "h265 slice references an unknown VPS/SPS/PPS"),
            Self::MissingReference => {
                write!(f, "h265 picture references an absent reference picture")
            }
            Self::IncompletePicture => {
                write!(f, "h265 picture ended with undecoded coding tree units")
            }
        }
    }
}

impl std::error::Error for DecodeError {}
