#!/usr/bin/env python3
"""Generates crates/fss-codec-h264/src/cabac_tables.rs (H.264 clause 9.3
CABAC tables for 8-bit 4:2:0 frame coding, ctxIdx 0..=459).

Source: FFmpeg n8.0.1 (the sealed laboratory oracle's own tables, which
transcribe ITU-T H.264 Tables 9-12..9-33, 9-43, 9-44 and 9-45):

- libavcodec/h264_cabac.c: cabac_context_init_I[1024][2],
  cabac_context_init_PB[3][1024][2] (m, n per ctxIdx; only 0..=459 are
  used by frame-coded 4:2:0), significant_coeff_flag_offset_8x8[0] (frame
  8x8 significance ctxIdxInc, Table 9-43).
- libavcodec/cabac.c: ff_h264_cabac_tables (rangeTabLPS, Table 9-44;
  the combined MPS/LPS state transition, Table 9-45; and the 8x8
  last_significant_coeff_flag ctxIdxInc, Table 9-43).

Usage:
  scripts/generate_h264_cabac_tables.py <dir holding h264_cabac.c and cabac.c>

The Rust unit tests in src/cabac.rs re-check hand-typed spec entries
(Table 9-12/9-13 rows, Table 9-44 rows, Table 9-45) against the emitted
tables, so a transcription or parsing slip here fails independently.
"""
import os
import re
import sys

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                   "crates", "fss-codec-h264", "src", "cabac_tables.rs")
CTX_COUNT = 460


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def initializer(text, name):
    m = re.search(re.escape(name) + r"[^=]*=\s*\{", text)
    assert m, f"missing array {name}"
    depth, i = 1, m.end()
    while depth:
        c = text[i]
        depth += c == "{"
        depth -= c == "}"
        i += 1
    return text[m.end():i - 1]


def ints(body):
    return [int(x) for x in re.findall(r"-?\d+", body)]


def main():
    src_dir = sys.argv[1]
    h264 = strip_comments(open(os.path.join(src_dir, "h264_cabac.c")).read())
    cabac = strip_comments(open(os.path.join(src_dir, "cabac.c")).read())

    init_i = ints(initializer(h264, "cabac_context_init_I"))
    assert len(init_i) == 1024 * 2, len(init_i)
    init_pb = ints(initializer(h264, "cabac_context_init_PB"))
    assert len(init_pb) == 3 * 1024 * 2, len(init_pb)
    sig8 = ints(initializer(h264, "significant_coeff_flag_offset_8x8"))
    assert len(sig8) == 2 * 63
    sig8 = sig8[:63]

    tables = [v & 0xFF for v in ints(initializer(cabac, "ff_h264_cabac_tables"))]
    assert len(tables) == 512 + 4 * 2 * 64 + 4 * 64 + 63, len(tables)
    lps = tables[512:512 + 512]
    mlps = tables[1024:1024 + 256]
    last8 = tables[1280:1280 + 63]

    range_lps = []
    for state in range(64):
        row = []
        for q in range(4):
            a, b = lps[q * 128 + 2 * state], lps[q * 128 + 2 * state + 1]
            assert a == b
            row.append(a)
        range_lps.append(row)
    # mlps[128 + s] is the state after an MPS for packed s = 2*p + mps;
    # mlps[127 - s] the state after an LPS (packed the same way).
    trans_lps, trans_mps = [], []
    for p in range(64):
        for mps in (0, 1):
            s = 2 * p + mps
            after_mps, after_lps = mlps[128 + s], mlps[127 - s]
            assert after_mps & 1 == mps
            if mps == 0:
                trans_mps.append(after_mps >> 1)
                trans_lps.append(after_lps >> 1)
                # valMPS flips only on an LPS from state 0.
                assert (after_lps & 1) == (1 if p == 0 else 0), (p, after_lps)
    # State 63 is the terminate-only state; the MPS/LPS tables never
    # leave or enter it through regular bins except 62 -> 62.
    pairs = lambda flat: [(flat[2 * i], flat[2 * i + 1]) for i in range(CTX_COUNT)]
    ctx_i = pairs(init_i)
    ctx_pb = [pairs(init_pb[k * 2048:(k + 1) * 2048]) for k in range(3)]

    def fmt_pairs(rows):
        out = []
        for i in range(0, len(rows), 6):
            chunk = ", ".join(f"({m}, {n})" for m, n in rows[i:i + 6])
            out.append(f"    {chunk},")
        return "\n".join(out)

    def fmt_list(values, per=16):
        out = []
        for i in range(0, len(values), per):
            out.append("    " + ", ".join(str(v) for v in values[i:i + per]) + ",")
        return "\n".join(out)

    body = f"""// GENERATED by scripts/generate_h264_cabac_tables.py from FFmpeg n8.0.1
// libavcodec/h264_cabac.c and libavcodec/cabac.c (transcriptions of ITU-T
// H.264 Tables 9-12..9-33, 9-43, 9-44, 9-45). Do not edit by hand;
// regenerate. Spec entries are re-checked by hand in cabac.rs tests.

/// Number of CABAC contexts used by 8-bit 4:2:0 frame coding (ctxIdx 0..=459).
pub(crate) const CTX_COUNT: usize = {CTX_COUNT};

/// (m, n) for I and SI slices, ctxIdx 0..=459.
pub(crate) static CTX_INIT_I: [(i8, i8); CTX_COUNT] = [
{fmt_pairs(ctx_i)}
];

/// (m, n) for P and B slices, indexed by cabac_init_idc, ctxIdx 0..=459.
pub(crate) static CTX_INIT_PB: [[(i8, i8); CTX_COUNT]; 3] = [
    [
{fmt_pairs(ctx_pb[0])}
    ],
    [
{fmt_pairs(ctx_pb[1])}
    ],
    [
{fmt_pairs(ctx_pb[2])}
    ],
];

/// rangeTabLPS[pStateIdx][qCodIRangeIdx] (Table 9-44).
pub(crate) static RANGE_TAB_LPS: [[u8; 4]; 64] = [
{chr(10).join("    [" + ", ".join(str(v) for v in row) + "]," for row in range_lps)}
];

/// transIdxLPS[pStateIdx] (Table 9-45).
pub(crate) static TRANS_IDX_LPS: [u8; 64] = [
{fmt_list(trans_lps)}
];

/// transIdxMPS[pStateIdx] (Table 9-45).
pub(crate) static TRANS_IDX_MPS: [u8; 64] = [
{fmt_list(trans_mps)}
];

/// ctxIdxInc of significant_coeff_flag for frame-coded 8x8 blocks, by
/// levelListIdx 0..=62 (Table 9-43).
pub(crate) static SIG_COEFF_8X8_FRAME: [u8; 63] = [
{fmt_list(sig8)}
];

/// ctxIdxInc of last_significant_coeff_flag for 8x8 blocks, by
/// levelListIdx 0..=62 (Table 9-43).
pub(crate) static LAST_COEFF_8X8: [u8; 63] = [
{fmt_list(last8)}
];
"""
    with open(OUT, "w") as f:
        f.write(body)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
