#!/usr/bin/env python3
"""OFFLINE LABORATORY ORACLE for the YOLOX-Nano package (fss-q4ngj). Never a runtime path.

Runs the pinned upstream ONNX file under onnxruntime (a sealed laboratory oracle; FSS never
executes it) on the exact model-input tensors that FSS preprocessing produced
(`cargo run -p fss-reference --example yolox_lab -- inputs DIR`), and writes the committed
conformance fixture: sampled raw and decoded head values (exact F32 bits), the complete 85
values of the rows with the largest objectness logits, and the expected post-processed
detections under the package's own head semantics (score = objectness * class probability,
multi-label, inclusive threshold, class-aware NMS on 1/256-pixel source boxes).

Run inside a uv venv OUTSIDE the repository (see models/yolox-nano/README.md):
  python scripts/yolox_nano_oracle.py MODEL.onnx INPUT_DIR OUT_FIXTURE
The output must not already exist. No network access; no files other than OUT_FIXTURE are written.
"""
import hashlib
import importlib.metadata
import math
import platform
import sys
from pathlib import Path

import numpy as np
import onnxruntime as ort

EXPECTED_ONNX = "c789161ed43c8269fcd4e67c67eeeb4e80c622da2eb296a20bc6007bd18a0b7d"
CASES = ["synthetic_pattern", "jpeg_colorbars", "silhouette"]
STRIDES = (8, 16, 32)
INPUT = 416
SAMPLES = 1024
TOP_ROWS = 16
PACKAGE_PPM = 300_000
LOW_PPM = 50_000
NMS_PPM = 450_000
SUBPIXELS = 256


def grid_and_strides():
    grid, stride = [], []
    for s in STRIDES:
        n = INPUT // s
        for gy in range(n):
            for gx in range(n):
                grid.append((gx, gy))
                stride.append(s)
    return np.array(grid, np.float32), np.array(stride, np.float32)[:, None]


def source_box(b, geometry):
    sw, sh, iw, ih, left, top = geometry
    if not all(math.isfinite(v) for v in b) or b[0] >= b[2] or b[1] >= b[3]:
        return None
    x = lambda v: min(max(v - left, 0.0), float(iw)) * sw / iw
    y = lambda v: min(max(v - top, 0.0), float(ih)) * sh / ih
    r = [x(b[0]), y(b[1]), x(b[2]), y(b[3])]
    return r if r[0] < r[2] and r[1] < r[3] else None


def suppresses(a, b, ppm):
    area = lambda r: (r[2] - r[0]) * (r[3] - r[1])
    inter = max(0, min(a[2], b[2]) - max(a[0], b[0])) * max(0, min(a[3], b[3]) - max(a[1], b[1]))
    union = area(a) + area(b) - inter
    return inter * 1_000_000 > union * ppm, abs(inter * 1_000_000 - union * ppm) / max(union * 1_000_000, 1)


def detections(decoded, geometry, ppm):
    """Mirror of fss-reference rgb_detections::decode_head for this package's head spec."""
    candidates, score_margin = [], math.inf
    for row in range(decoded.shape[0]):
        v = decoded[row]
        cx, cy, w, h = (float(t) for t in v[:4])
        if w <= 0 or h <= 0:
            raise SystemExit("nonpositive box would be refused")
        scores = (np.float32(v[4]) * v[5:].astype(np.float32)).astype(np.float32)
        box = [cx - w * 0.5, cy - h * 0.5, cx + w * 0.5, cy + h * 0.5]
        passing = [c for c in range(scores.shape[0]) if float(scores[c]) * 1_000_000.0 >= ppm]
        score_margin = min(score_margin, float(np.min(np.abs(scores.astype(np.float64) - ppm / 1e6))))
        if not passing:
            continue
        mapped = source_box(box, geometry)
        if mapped is None:
            continue
        q = [math.floor(mapped[0] * SUBPIXELS), math.floor(mapped[1] * SUBPIXELS),
             math.ceil(mapped[2] * SUBPIXELS), math.ceil(mapped[3] * SUBPIXELS)]
        for c in passing:
            candidates.append((float(scores[c]), row, c, q))
    candidates.sort(key=lambda t: (-t[0], t[1], t[2]))
    kept, nms_margin = [], math.inf
    for score, row, c, q in candidates:
        suppressed = False
        for _, _, kc, kq in kept:
            if kc != c:
                continue
            hit, margin = suppresses(kq, q, NMS_PPM)
            nms_margin = min(nms_margin, margin)
            if hit:
                suppressed = True
                break
        if not suppressed:
            kept.append((score, row, c, q))
    return kept, len(candidates), score_margin, nms_margin


def bits(v):
    return "%08x" % int(np.float32(v).view(np.uint32))


def main():
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    model, inputs, out = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    raw_model = model.read_bytes()
    if hashlib.sha256(raw_model).hexdigest() != EXPECTED_ONNX:
        raise SystemExit("unpinned ONNX source")
    options = ort.SessionOptions()
    options.intra_op_num_threads = 1
    options.inter_op_num_threads = 1
    session = ort.InferenceSession(raw_model, options, providers=["CPUExecutionProvider"])
    grid, stride = grid_and_strides()
    lines = ["# fss.yolox_nano_conformance.v1 (generated by scripts/yolox_nano_oracle.py; do not edit)",
             "oracle onnxruntime=%s onnx=%s numpy=%s python=%s machine=%s providers=CPUExecutionProvider threads=1" % (
                 ort.__version__, importlib.metadata.version("onnx"), np.__version__, platform.python_version(),
                 platform.machine()),
             "source_sha256 " + EXPECTED_ONNX,
             "thresholds package_ppm=%d low_ppm=%d nms_ppm=%d" % (PACKAGE_PPM, LOW_PPM, NMS_PPM)]
    for case in CASES:
        data = (inputs / f"{case}.input.f32le").read_bytes()
        geometry = [int(t) for t in (inputs / f"{case}.geometry.txt").read_text().split()]
        rgb = np.frombuffer(data, "<f4").reshape(1, 3, INPUT, INPUT)
        bgr = np.ascontiguousarray(rgb[:, ::-1])
        raw = session.run(None, {"images": bgr})[0][0].astype(np.float32)
        decoded = raw.copy()
        decoded[:, :2] = (raw[:, :2] + grid) * stride
        decoded[:, 2:4] = np.exp(raw[:, 2:4]) * stride
        n = raw.size
        lines += ["case " + case, "input_sha256 " + hashlib.sha256(data).hexdigest(),
                  "geometry " + " ".join(map(str, geometry))]
        flat_raw, flat_dec = raw.reshape(-1), decoded.reshape(-1)
        for k in range(SAMPLES):
            i = (k * 7919) % n
            lines.append("sample %d %s %s" % (i, bits(flat_raw[i]), bits(flat_dec[i])))
        for row in np.argsort(-raw[:, 4], kind="stable")[:TOP_ROWS]:
            lines.append("toprow %d %s" % (row, " ".join(bits(v) for v in raw[row])))
        for ppm in (PACKAGE_PPM, LOW_PPM):
            kept, count, score_margin, nms_margin = detections(decoded, geometry, ppm)
            lines.append("candidates %d %d score_margin %.9g nms_margin %.9g" % (ppm, count, score_margin, nms_margin))
            for score, row, c, q in kept:
                lines.append("det %d %d %d %s %d %d %d %d" % (ppm, row, c, bits(score), *q))
        print(case, "max_objectness_logit", float(raw[:, 4].max()),
              {ppm: len(detections(decoded, geometry, ppm)[0]) for ppm in (PACKAGE_PPM, LOW_PPM)})
    lines.append("end")
    with out.open("x") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", out, "sha256", hashlib.sha256(out.read_bytes()).hexdigest())


if __name__ == "__main__":
    main()
