#![forbid(unsafe_code)]
//! H.264 pixel decode (Constrained Baseline and Main profile,
//! progressive 8-bit 4:2:0), scalar reference implementation.
//!
//! NAL units enter, reconstructed 8-bit 4:2:0 pictures leave in output
//! (display) order, with every stage bounded, deterministic, and
//! typed-error on hostile input. Parameter sets are first admitted by
//! `fss-packet`'s AVC custody parser (which owns the admission decision and
//! refuses what it cannot bound); this crate then reads the decode-relevant
//! fields that custody deliberately leaves inside the exact original NAL
//! bytes.
//!
//! Stage map, in decode order:
//! 1. [`rbsp`] — NAL header, emulation-prevention removal, trailing bits.
//! 2. [`bits`] — bounds-checked bit reader with ue/se/te mappings.
//! 3. [`params`] / [`slice`] — SPS/PPS decode fields (scaling lists, VUI
//!    reorder bounds) and slice headers (list modification, weights,
//!    reference marking).
//! 4. [`cavlc`] / [`residual`] — CAVLC residual blocks (clause 9.2);
//!    [`cabac`] — the CABAC arithmetic decoder (clause 9.3).
//! 5. `macroblock` — the macroblock layer shared by both entropy coders
//!    (`mb_cavlc`, `mb_cabac`): I_NxN (4x4 and 8x8), I_16x16, I_PCM, P and
//!    B partitions, sub-macroblocks, skip and direct (spatial and
//!    temporal) prediction.
//! 6. [`intra`] / [`transform`] / `inter` — prediction, scaling-list
//!    dequantisation, 4x4/8x8 inverse transforms, quarter-pel luma /
//!    eighth-pel chroma interpolation, default/explicit/implicit weighting.
//! 7. `deblock` — the in-loop deblocking filter (clause 8.7).
//! 8. [`decoder`] — the streaming [`Decoder`]: POC, reference lists,
//!    sliding-window and MMCO marking with long-term references, and the
//!    decoded picture buffer's output process.
//!
//! Admitted tool set: CAVLC and CABAC, I, P and B slices, frame pictures,
//! 8-bit 4:2:0, flat scaling, weighted prediction, one slice group,
//! slices in raster order, POC types 0 and 2. Everything else (the 8x8
//! transform, scaling matrices, interlaced/PAFF/MBAFF, other chroma formats
//! and bit depths, lossless, SP/SI, FMO/ASO, data partitioning, POC type 1,
//! MVC and SVC) is refused with [`DecodeError::Unsupported`] naming the
//! feature.
//!
//! Correctness is established differentially: tests compare every decoded
//! frame bit-exactly, in output order, against digests produced offline by
//! the sealed FFmpeg laboratory oracle (never invoked at runtime or by
//! tests).
#![allow(clippy::module_name_repetitions)]

pub mod bits;
pub mod cabac;
// Generated by scripts/generate_h264_cabac_tables.py; kept byte-identical
// to the generator output rather than reflowed by rustfmt.
#[rustfmt::skip]
mod cabac_tables;
pub mod cavlc;
mod deblock;
pub mod decoder;
mod inter;
pub mod intra;
mod macroblock;
mod mb_cabac;
mod mb_cavlc;
pub mod params;
pub mod picture;
pub mod rbsp;
pub mod residual;
pub mod slice;
// Generated by scripts/generate_cavlc_tables.py; kept byte-identical to
// the generator output rather than reflowed by rustfmt.
#[rustfmt::skip]
mod tables;
#[cfg(test)]
mod tables_tests;
pub mod transform;

pub use decoder::{Decoder, DecoderLimits, annex_b_nal_units};
pub use picture::Picture;

use fss_packet::avc::AvcError;

/// A coding tool or stream property outside the admitted tool set. Refusal
/// is explicit: the decoder never emits approximate pixels for these.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UnsupportedFeature {
    /// `profile_idc` not admitted by `fss-packet` custody.
    Profile,
    /// Anything but 8-bit 4:2:0: other chroma formats, separate colour
    /// planes, or luma/chroma bit depth above 8.
    SampleFormat,
    /// `qpprime_y_zero_transform_bypass_flag` (lossless macroblocks).
    TransformBypass,
    /// SPS or PPS scaling matrices (only flat scaling is admitted).
    ScalingMatrix,
    /// The 8x8 transform (High profile `transform_8x8_mode_flag`).
    Transform8x8,
    /// Historical: CABAC entropy coding. Admitted since Main profile
    /// support; no longer produced, kept for API stability.
    Cabac,
    /// Field pictures, PAFF or MBAFF (`frame_mbs_only_flag == 0`).
    Interlaced,
    /// More than one slice group (FMO).
    SliceGroups,
    /// Slices not contiguous in raster order within a picture (ASO, or a
    /// missing slice: the decoder does not conceal either).
    ArbitrarySliceOrder,
    /// Historical: B slices. Admitted since Main profile support; no
    /// longer produced, kept for API stability.
    BSlice,
    /// SP or SI slices.
    SwitchingSlice,
    /// Data-partitioned slices (NAL unit types 2..=4).
    DataPartitioning,
    /// Historical: explicit weighted prediction. Admitted; no longer
    /// produced, kept for API stability.
    WeightedPrediction,
    /// Historical: `ref_pic_list_modification`. Admitted; no longer
    /// produced, kept for API stability.
    RefPicListModification,
    /// Historical: long-term reference pictures. Admitted; no longer
    /// produced, kept for API stability.
    LongTermReference,
    /// Historical: adaptive (MMCO) reference picture marking. Admitted; no
    /// longer produced, kept for API stability.
    AdaptiveRefPicMarking,
    /// Picture order count type 1.
    PocType1,
    /// Historical: output reordering. Pictures are now reordered through
    /// the decoded picture buffer; no longer produced, kept for API
    /// stability.
    OutputReordering,
    /// A CAVLC `level_prefix` above 15 (the escape only High profiles at
    /// bit depths above 8 need; not implemented).
    LevelPrefixEscape,
}

/// Typed decode failure for this crate. Wraps `fss-packet` syntax refusals
/// verbatim so upstream custody and decode reject with one vocabulary.
/// An error never publishes a partially reconstructed picture.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum DecodeError {
    /// The NAL, its payload, or a decoder budget violated a hard bound.
    Limit,
    /// Structural corruption (impossible syntax, bad trailing bits, failed
    /// emulation-prevention invariants, out-of-range values, truncation).
    Malformed,
    /// A NAL of an unexpected type reached this stage.
    UnexpectedNal,
    /// Syntax declared by the stream exceeds the admitted tool set.
    Unsupported(UnsupportedFeature),
    /// A slice referenced an SPS or PPS id that has not been received.
    MissingParameterSet,
    /// An inter slice referenced a picture that is not in its reference
    /// list (e.g. decoding started without an IDR, or after a refused
    /// picture), or a list modification named an absent picture.
    MissingReference,
    /// `frame_num` skipped values (lost pictures); gap filling is not done.
    FrameNumGap,
    /// A picture ended (new picture or flush) before all its macroblocks
    /// were decoded. The partial picture is discarded, not concealed.
    IncompletePicture,
    /// Propagated `fss-packet` syntax error.
    Packet(AvcError),
}

impl From<AvcError> for DecodeError {
    fn from(value: AvcError) -> Self {
        match value {
            AvcError::Limit => Self::Limit,
            AvcError::Malformed | AvcError::Truncated | AvcError::Corrupt => Self::Malformed,
            AvcError::UnexpectedNal => Self::UnexpectedNal,
            AvcError::UnsupportedProfile => Self::Unsupported(UnsupportedFeature::Profile),
            AvcError::UnsupportedSampleFormat => {
                Self::Unsupported(UnsupportedFeature::SampleFormat)
            }
            AvcError::UnsupportedSliceGroups => Self::Unsupported(UnsupportedFeature::SliceGroups),
            other => Self::Packet(other),
        }
    }
}

impl std::fmt::Display for DecodeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Limit => write!(f, "h264 decode input exceeded hard limits"),
            Self::Malformed => write!(f, "h264 bitstream is structurally malformed"),
            Self::UnexpectedNal => write!(f, "unexpected nal unit type at this decode stage"),
            Self::Unsupported(feature) => {
                write!(f, "h264 syntax outside the admitted tool set: {feature:?}")
            }
            Self::MissingParameterSet => write!(f, "h264 slice references an unknown SPS/PPS"),
            Self::MissingReference => {
                write!(f, "h264 slice references an absent reference picture")
            }
            Self::FrameNumGap => write!(f, "h264 frame_num gap (lost pictures)"),
            Self::IncompletePicture => write!(f, "h264 picture ended with undecoded macroblocks"),
            Self::Packet(err) => write!(f, "avc syntax refusal: {err}"),
        }
    }
}
impl std::error::Error for DecodeError {}
