#![forbid(unsafe_code)]
//! Constrained-Baseline H.264 pixel decode, scalar reference implementation.
//!
//! NAL units enter, reconstructed 8-bit 4:2:0 pictures leave, with every
//! stage bounded, deterministic, and typed-error on hostile input. Parameter
//! sets are first admitted by `fss-packet`'s AVC custody parser (which owns
//! the admission decision and refuses what it cannot bound); this crate then
//! reads the decode-relevant fields that custody deliberately leaves inside
//! the exact original NAL bytes.
//!
//! Stage map, in decode order:
//! 1. [`rbsp`] — NAL header, emulation-prevention removal, trailing bits.
//! 2. [`bits`] — bounds-checked bit reader with ue/se/te mappings.
//! 3. [`params`] / [`slice`] — SPS/PPS decode fields and slice headers.
//! 4. [`cavlc`] / [`residual`] — CAVLC residual blocks (clause 9.2).
//! 5. `macroblock` — I_NxN, I_16x16, I_PCM, P_L0 partitions, P_Skip.
//! 6. [`intra`] / [`transform`] / `inter` — prediction, dequantisation,
//!    inverse transforms, quarter-pel luma / eighth-pel chroma interpolation.
//! 7. `deblock` — the in-loop deblocking filter (clause 8.7).
//! 8. [`decoder`] — the streaming [`Decoder`], reference list, sliding-window
//!    marking, output in decode order.
//!
//! Admitted tool set: CAVLC, I and P slices, frame pictures, 8-bit 4:2:0,
//! flat scaling, one slice group, slices in raster order, sliding-window
//! reference marking, no reference-list modification, no weighted
//! prediction, POC type 0 without reordering or POC type 2. Everything else
//! is refused with [`DecodeError::Unsupported`] naming the feature.
//!
//! Correctness is established differentially: tests compare every decoded
//! frame bit-exactly against digests produced offline by the sealed FFmpeg
//! laboratory oracle (never invoked at runtime or by tests).
#![allow(clippy::module_name_repetitions)]

pub mod bits;
pub mod cavlc;
mod deblock;
pub mod decoder;
mod inter;
pub mod intra;
mod macroblock;
pub mod params;
pub mod picture;
pub mod rbsp;
pub mod residual;
pub mod slice;
// Generated by scripts/generate_cavlc_tables.py; kept byte-identical to
// the generator output rather than reflowed by rustfmt.
#[rustfmt::skip]
mod tables;
#[cfg(test)]
mod tables_tests;
pub mod transform;

pub use decoder::{Decoder, DecoderLimits, annex_b_nal_units};
pub use picture::Picture;

use fss_packet::avc::AvcError;

/// A coding tool or stream property outside the admitted tool set. Refusal
/// is explicit: the decoder never emits approximate pixels for these.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UnsupportedFeature {
    /// `profile_idc` not admitted by `fss-packet` custody.
    Profile,
    /// Anything but 8-bit 4:2:0: other chroma formats, separate colour
    /// planes, or luma/chroma bit depth above 8.
    SampleFormat,
    /// `qpprime_y_zero_transform_bypass_flag` (lossless macroblocks).
    TransformBypass,
    /// SPS or PPS scaling matrices (only flat scaling is admitted).
    ScalingMatrix,
    /// The 8x8 transform (High profile `transform_8x8_mode_flag`).
    Transform8x8,
    /// CABAC entropy coding.
    Cabac,
    /// Field pictures, PAFF or MBAFF (`frame_mbs_only_flag == 0`).
    Interlaced,
    /// More than one slice group (FMO).
    SliceGroups,
    /// Slices not contiguous in raster order within a picture (ASO, or a
    /// missing slice: the decoder does not conceal either).
    ArbitrarySliceOrder,
    /// B slices.
    BSlice,
    /// SP or SI slices.
    SwitchingSlice,
    /// Data-partitioned slices (NAL unit types 2..=4).
    DataPartitioning,
    /// Explicit weighted prediction.
    WeightedPrediction,
    /// `ref_pic_list_modification` in a slice header.
    RefPicListModification,
    /// Long-term reference pictures.
    LongTermReference,
    /// Adaptive (MMCO) reference picture marking.
    AdaptiveRefPicMarking,
    /// Picture order count type 1.
    PocType1,
    /// Picture order count that would require output reordering.
    OutputReordering,
    /// A CAVLC `level_prefix` above 15 (not allowed for 8-bit Baseline).
    LevelPrefixEscape,
}

/// Typed decode failure for this crate. Wraps `fss-packet` syntax refusals
/// verbatim so upstream custody and decode reject with one vocabulary.
/// An error never publishes a partially reconstructed picture.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum DecodeError {
    /// The NAL, its payload, or a decoder budget violated a hard bound.
    Limit,
    /// Structural corruption (impossible syntax, bad trailing bits, failed
    /// emulation-prevention invariants, out-of-range values, truncation).
    Malformed,
    /// A NAL of an unexpected type reached this stage.
    UnexpectedNal,
    /// Syntax declared by the stream exceeds the admitted tool set.
    Unsupported(UnsupportedFeature),
    /// A slice referenced an SPS or PPS id that has not been received.
    MissingParameterSet,
    /// A P slice referenced a picture that is not in the reference list
    /// (e.g. decoding started without an IDR, or after a refused picture).
    MissingReference,
    /// `frame_num` skipped values (lost pictures); gap filling is not done.
    FrameNumGap,
    /// A picture ended (new picture or flush) before all its macroblocks
    /// were decoded. The partial picture is discarded, not concealed.
    IncompletePicture,
    /// Propagated `fss-packet` syntax error.
    Packet(AvcError),
}

impl From<AvcError> for DecodeError {
    fn from(value: AvcError) -> Self {
        match value {
            AvcError::Limit => Self::Limit,
            AvcError::Malformed | AvcError::Truncated | AvcError::Corrupt => Self::Malformed,
            AvcError::UnexpectedNal => Self::UnexpectedNal,
            AvcError::UnsupportedProfile => Self::Unsupported(UnsupportedFeature::Profile),
            AvcError::UnsupportedSampleFormat => {
                Self::Unsupported(UnsupportedFeature::SampleFormat)
            }
            AvcError::UnsupportedSliceGroups => Self::Unsupported(UnsupportedFeature::SliceGroups),
            other => Self::Packet(other),
        }
    }
}

impl std::fmt::Display for DecodeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Limit => write!(f, "h264 decode input exceeded hard limits"),
            Self::Malformed => write!(f, "h264 bitstream is structurally malformed"),
            Self::UnexpectedNal => write!(f, "unexpected nal unit type at this decode stage"),
            Self::Unsupported(feature) => {
                write!(
                    f,
                    "h264 syntax outside the admitted baseline tool set: {feature:?}"
                )
            }
            Self::MissingParameterSet => write!(f, "h264 slice references an unknown SPS/PPS"),
            Self::MissingReference => write!(f, "h264 P slice references an absent picture"),
            Self::FrameNumGap => write!(f, "h264 frame_num gap (lost pictures)"),
            Self::IncompletePicture => write!(f, "h264 picture ended with undecoded macroblocks"),
            Self::Packet(err) => write!(f, "avc syntax refusal: {err}"),
        }
    }
}
impl std::error::Error for DecodeError {}
