// GENERATED by scripts/generate_cavlc_tables.py. Sources: FFmpeg
// libavcodec/h264_cavlc.c tables (complete) + codecs-in-markdown H.264
// 9.2 transcription (chroma DC). Do not edit by hand; regenerate.

// The residual decoder that consumes every table lands in the next
// slice; until then the toolchain sees validated-but-unread data.
#![allow(dead_code)]

use std::sync::LazyLock;

use super::cavlc::{VlcEntry, VlcTable};

static CT_NC01: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 1, value: 0 },
    VlcEntry { code: 0x5, len: 6, value: 4 },
    VlcEntry { code: 0x1, len: 2, value: 5 },
    VlcEntry { code: 0x7, len: 8, value: 8 },
    VlcEntry { code: 0x4, len: 6, value: 9 },
    VlcEntry { code: 0x1, len: 3, value: 10 },
    VlcEntry { code: 0x7, len: 9, value: 12 },
    VlcEntry { code: 0x6, len: 8, value: 13 },
    VlcEntry { code: 0x5, len: 7, value: 14 },
    VlcEntry { code: 0x3, len: 5, value: 15 },
    VlcEntry { code: 0x7, len: 10, value: 16 },
    VlcEntry { code: 0x6, len: 9, value: 17 },
    VlcEntry { code: 0x5, len: 8, value: 18 },
    VlcEntry { code: 0x3, len: 6, value: 19 },
    VlcEntry { code: 0x7, len: 11, value: 20 },
    VlcEntry { code: 0x6, len: 10, value: 21 },
    VlcEntry { code: 0x5, len: 9, value: 22 },
    VlcEntry { code: 0x4, len: 7, value: 23 },
    VlcEntry { code: 0xf, len: 13, value: 24 },
    VlcEntry { code: 0x6, len: 11, value: 25 },
    VlcEntry { code: 0x5, len: 10, value: 26 },
    VlcEntry { code: 0x4, len: 8, value: 27 },
    VlcEntry { code: 0xb, len: 13, value: 28 },
    VlcEntry { code: 0xe, len: 13, value: 29 },
    VlcEntry { code: 0x5, len: 11, value: 30 },
    VlcEntry { code: 0x4, len: 9, value: 31 },
    VlcEntry { code: 0x8, len: 13, value: 32 },
    VlcEntry { code: 0xa, len: 13, value: 33 },
    VlcEntry { code: 0xd, len: 13, value: 34 },
    VlcEntry { code: 0x4, len: 10, value: 35 },
    VlcEntry { code: 0xf, len: 14, value: 36 },
    VlcEntry { code: 0xe, len: 14, value: 37 },
    VlcEntry { code: 0x9, len: 13, value: 38 },
    VlcEntry { code: 0x4, len: 11, value: 39 },
    VlcEntry { code: 0xb, len: 14, value: 40 },
    VlcEntry { code: 0xa, len: 14, value: 41 },
    VlcEntry { code: 0xd, len: 14, value: 42 },
    VlcEntry { code: 0xc, len: 13, value: 43 },
    VlcEntry { code: 0xf, len: 15, value: 44 },
    VlcEntry { code: 0xe, len: 15, value: 45 },
    VlcEntry { code: 0x9, len: 14, value: 46 },
    VlcEntry { code: 0xc, len: 14, value: 47 },
    VlcEntry { code: 0xb, len: 15, value: 48 },
    VlcEntry { code: 0xa, len: 15, value: 49 },
    VlcEntry { code: 0xd, len: 15, value: 50 },
    VlcEntry { code: 0x8, len: 14, value: 51 },
    VlcEntry { code: 0xf, len: 16, value: 52 },
    VlcEntry { code: 0x1, len: 15, value: 53 },
    VlcEntry { code: 0x9, len: 15, value: 54 },
    VlcEntry { code: 0xc, len: 15, value: 55 },
    VlcEntry { code: 0xb, len: 16, value: 56 },
    VlcEntry { code: 0xe, len: 16, value: 57 },
    VlcEntry { code: 0xd, len: 16, value: 58 },
    VlcEntry { code: 0x8, len: 15, value: 59 },
    VlcEntry { code: 0x7, len: 16, value: 60 },
    VlcEntry { code: 0xa, len: 16, value: 61 },
    VlcEntry { code: 0x9, len: 16, value: 62 },
    VlcEntry { code: 0xc, len: 16, value: 63 },
    VlcEntry { code: 0x4, len: 16, value: 64 },
    VlcEntry { code: 0x6, len: 16, value: 65 },
    VlcEntry { code: 0x5, len: 16, value: 66 },
    VlcEntry { code: 0x8, len: 16, value: 67 },
];

static CT_NC24: &[VlcEntry] = &[
    VlcEntry { code: 0x3, len: 2, value: 0 },
    VlcEntry { code: 0xb, len: 6, value: 4 },
    VlcEntry { code: 0x2, len: 2, value: 5 },
    VlcEntry { code: 0x7, len: 6, value: 8 },
    VlcEntry { code: 0x7, len: 5, value: 9 },
    VlcEntry { code: 0x3, len: 3, value: 10 },
    VlcEntry { code: 0x7, len: 7, value: 12 },
    VlcEntry { code: 0xa, len: 6, value: 13 },
    VlcEntry { code: 0x9, len: 6, value: 14 },
    VlcEntry { code: 0x5, len: 4, value: 15 },
    VlcEntry { code: 0x7, len: 8, value: 16 },
    VlcEntry { code: 0x6, len: 6, value: 17 },
    VlcEntry { code: 0x5, len: 6, value: 18 },
    VlcEntry { code: 0x4, len: 4, value: 19 },
    VlcEntry { code: 0x4, len: 8, value: 20 },
    VlcEntry { code: 0x6, len: 7, value: 21 },
    VlcEntry { code: 0x5, len: 7, value: 22 },
    VlcEntry { code: 0x6, len: 5, value: 23 },
    VlcEntry { code: 0x7, len: 9, value: 24 },
    VlcEntry { code: 0x6, len: 8, value: 25 },
    VlcEntry { code: 0x5, len: 8, value: 26 },
    VlcEntry { code: 0x8, len: 6, value: 27 },
    VlcEntry { code: 0xf, len: 11, value: 28 },
    VlcEntry { code: 0x6, len: 9, value: 29 },
    VlcEntry { code: 0x5, len: 9, value: 30 },
    VlcEntry { code: 0x4, len: 6, value: 31 },
    VlcEntry { code: 0xb, len: 11, value: 32 },
    VlcEntry { code: 0xe, len: 11, value: 33 },
    VlcEntry { code: 0xd, len: 11, value: 34 },
    VlcEntry { code: 0x4, len: 7, value: 35 },
    VlcEntry { code: 0xf, len: 12, value: 36 },
    VlcEntry { code: 0xa, len: 11, value: 37 },
    VlcEntry { code: 0x9, len: 11, value: 38 },
    VlcEntry { code: 0x4, len: 9, value: 39 },
    VlcEntry { code: 0xb, len: 12, value: 40 },
    VlcEntry { code: 0xe, len: 12, value: 41 },
    VlcEntry { code: 0xd, len: 12, value: 42 },
    VlcEntry { code: 0xc, len: 11, value: 43 },
    VlcEntry { code: 0x8, len: 12, value: 44 },
    VlcEntry { code: 0xa, len: 12, value: 45 },
    VlcEntry { code: 0x9, len: 12, value: 46 },
    VlcEntry { code: 0x8, len: 11, value: 47 },
    VlcEntry { code: 0xf, len: 13, value: 48 },
    VlcEntry { code: 0xe, len: 13, value: 49 },
    VlcEntry { code: 0xd, len: 13, value: 50 },
    VlcEntry { code: 0xc, len: 12, value: 51 },
    VlcEntry { code: 0xb, len: 13, value: 52 },
    VlcEntry { code: 0xa, len: 13, value: 53 },
    VlcEntry { code: 0x9, len: 13, value: 54 },
    VlcEntry { code: 0xc, len: 13, value: 55 },
    VlcEntry { code: 0x7, len: 13, value: 56 },
    VlcEntry { code: 0xb, len: 14, value: 57 },
    VlcEntry { code: 0x6, len: 13, value: 58 },
    VlcEntry { code: 0x8, len: 13, value: 59 },
    VlcEntry { code: 0x9, len: 14, value: 60 },
    VlcEntry { code: 0x8, len: 14, value: 61 },
    VlcEntry { code: 0xa, len: 14, value: 62 },
    VlcEntry { code: 0x1, len: 13, value: 63 },
    VlcEntry { code: 0x7, len: 14, value: 64 },
    VlcEntry { code: 0x6, len: 14, value: 65 },
    VlcEntry { code: 0x5, len: 14, value: 66 },
    VlcEntry { code: 0x4, len: 14, value: 67 },
];

static CT_NC48: &[VlcEntry] = &[
    VlcEntry { code: 0xf, len: 4, value: 0 },
    VlcEntry { code: 0xf, len: 6, value: 4 },
    VlcEntry { code: 0xe, len: 4, value: 5 },
    VlcEntry { code: 0xb, len: 6, value: 8 },
    VlcEntry { code: 0xf, len: 5, value: 9 },
    VlcEntry { code: 0xd, len: 4, value: 10 },
    VlcEntry { code: 0x8, len: 6, value: 12 },
    VlcEntry { code: 0xc, len: 5, value: 13 },
    VlcEntry { code: 0xe, len: 5, value: 14 },
    VlcEntry { code: 0xc, len: 4, value: 15 },
    VlcEntry { code: 0xf, len: 7, value: 16 },
    VlcEntry { code: 0xa, len: 5, value: 17 },
    VlcEntry { code: 0xb, len: 5, value: 18 },
    VlcEntry { code: 0xb, len: 4, value: 19 },
    VlcEntry { code: 0xb, len: 7, value: 20 },
    VlcEntry { code: 0x8, len: 5, value: 21 },
    VlcEntry { code: 0x9, len: 5, value: 22 },
    VlcEntry { code: 0xa, len: 4, value: 23 },
    VlcEntry { code: 0x9, len: 7, value: 24 },
    VlcEntry { code: 0xe, len: 6, value: 25 },
    VlcEntry { code: 0xd, len: 6, value: 26 },
    VlcEntry { code: 0x9, len: 4, value: 27 },
    VlcEntry { code: 0x8, len: 7, value: 28 },
    VlcEntry { code: 0xa, len: 6, value: 29 },
    VlcEntry { code: 0x9, len: 6, value: 30 },
    VlcEntry { code: 0x8, len: 4, value: 31 },
    VlcEntry { code: 0xf, len: 8, value: 32 },
    VlcEntry { code: 0xe, len: 7, value: 33 },
    VlcEntry { code: 0xd, len: 7, value: 34 },
    VlcEntry { code: 0xd, len: 5, value: 35 },
    VlcEntry { code: 0xb, len: 8, value: 36 },
    VlcEntry { code: 0xe, len: 8, value: 37 },
    VlcEntry { code: 0xa, len: 7, value: 38 },
    VlcEntry { code: 0xc, len: 6, value: 39 },
    VlcEntry { code: 0xf, len: 9, value: 40 },
    VlcEntry { code: 0xa, len: 8, value: 41 },
    VlcEntry { code: 0xd, len: 8, value: 42 },
    VlcEntry { code: 0xc, len: 7, value: 43 },
    VlcEntry { code: 0xb, len: 9, value: 44 },
    VlcEntry { code: 0xe, len: 9, value: 45 },
    VlcEntry { code: 0x9, len: 8, value: 46 },
    VlcEntry { code: 0xc, len: 8, value: 47 },
    VlcEntry { code: 0x8, len: 9, value: 48 },
    VlcEntry { code: 0xa, len: 9, value: 49 },
    VlcEntry { code: 0xd, len: 9, value: 50 },
    VlcEntry { code: 0x8, len: 8, value: 51 },
    VlcEntry { code: 0xd, len: 10, value: 52 },
    VlcEntry { code: 0x7, len: 9, value: 53 },
    VlcEntry { code: 0x9, len: 9, value: 54 },
    VlcEntry { code: 0xc, len: 9, value: 55 },
    VlcEntry { code: 0x9, len: 10, value: 56 },
    VlcEntry { code: 0xc, len: 10, value: 57 },
    VlcEntry { code: 0xb, len: 10, value: 58 },
    VlcEntry { code: 0xa, len: 10, value: 59 },
    VlcEntry { code: 0x5, len: 10, value: 60 },
    VlcEntry { code: 0x8, len: 10, value: 61 },
    VlcEntry { code: 0x7, len: 10, value: 62 },
    VlcEntry { code: 0x6, len: 10, value: 63 },
    VlcEntry { code: 0x1, len: 10, value: 64 },
    VlcEntry { code: 0x4, len: 10, value: 65 },
    VlcEntry { code: 0x3, len: 10, value: 66 },
    VlcEntry { code: 0x2, len: 10, value: 67 },
];

static CT_CDC: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 2, value: 0 },
    VlcEntry { code: 0x7, len: 6, value: 4 },
    VlcEntry { code: 0x1, len: 1, value: 5 },
    VlcEntry { code: 0x4, len: 6, value: 8 },
    VlcEntry { code: 0x6, len: 6, value: 9 },
    VlcEntry { code: 0x1, len: 3, value: 10 },
    VlcEntry { code: 0x3, len: 6, value: 12 },
    VlcEntry { code: 0x3, len: 7, value: 13 },
    VlcEntry { code: 0x2, len: 7, value: 14 },
    VlcEntry { code: 0x5, len: 6, value: 15 },
    VlcEntry { code: 0x2, len: 6, value: 16 },
    VlcEntry { code: 0x3, len: 8, value: 17 },
    VlcEntry { code: 0x2, len: 8, value: 18 },
    VlcEntry { code: 0x0, len: 7, value: 19 },
];

static TZ_1: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 1, value: 0 },
    VlcEntry { code: 0x3, len: 3, value: 1 },
    VlcEntry { code: 0x2, len: 3, value: 2 },
    VlcEntry { code: 0x3, len: 4, value: 3 },
    VlcEntry { code: 0x2, len: 4, value: 4 },
    VlcEntry { code: 0x3, len: 5, value: 5 },
    VlcEntry { code: 0x2, len: 5, value: 6 },
    VlcEntry { code: 0x3, len: 6, value: 7 },
    VlcEntry { code: 0x2, len: 6, value: 8 },
    VlcEntry { code: 0x3, len: 7, value: 9 },
    VlcEntry { code: 0x2, len: 7, value: 10 },
    VlcEntry { code: 0x3, len: 8, value: 11 },
    VlcEntry { code: 0x2, len: 8, value: 12 },
    VlcEntry { code: 0x3, len: 9, value: 13 },
    VlcEntry { code: 0x2, len: 9, value: 14 },
    VlcEntry { code: 0x1, len: 9, value: 15 },
];

static TZ_2: &[VlcEntry] = &[
    VlcEntry { code: 0x7, len: 3, value: 0 },
    VlcEntry { code: 0x6, len: 3, value: 1 },
    VlcEntry { code: 0x5, len: 3, value: 2 },
    VlcEntry { code: 0x4, len: 3, value: 3 },
    VlcEntry { code: 0x3, len: 3, value: 4 },
    VlcEntry { code: 0x5, len: 4, value: 5 },
    VlcEntry { code: 0x4, len: 4, value: 6 },
    VlcEntry { code: 0x3, len: 4, value: 7 },
    VlcEntry { code: 0x2, len: 4, value: 8 },
    VlcEntry { code: 0x3, len: 5, value: 9 },
    VlcEntry { code: 0x2, len: 5, value: 10 },
    VlcEntry { code: 0x3, len: 6, value: 11 },
    VlcEntry { code: 0x2, len: 6, value: 12 },
    VlcEntry { code: 0x1, len: 6, value: 13 },
    VlcEntry { code: 0x0, len: 6, value: 14 },
];

static TZ_3: &[VlcEntry] = &[
    VlcEntry { code: 0x5, len: 4, value: 0 },
    VlcEntry { code: 0x7, len: 3, value: 1 },
    VlcEntry { code: 0x6, len: 3, value: 2 },
    VlcEntry { code: 0x5, len: 3, value: 3 },
    VlcEntry { code: 0x4, len: 4, value: 4 },
    VlcEntry { code: 0x3, len: 4, value: 5 },
    VlcEntry { code: 0x4, len: 3, value: 6 },
    VlcEntry { code: 0x3, len: 3, value: 7 },
    VlcEntry { code: 0x2, len: 4, value: 8 },
    VlcEntry { code: 0x3, len: 5, value: 9 },
    VlcEntry { code: 0x2, len: 5, value: 10 },
    VlcEntry { code: 0x1, len: 6, value: 11 },
    VlcEntry { code: 0x1, len: 5, value: 12 },
    VlcEntry { code: 0x0, len: 6, value: 13 },
];

static TZ_4: &[VlcEntry] = &[
    VlcEntry { code: 0x3, len: 5, value: 0 },
    VlcEntry { code: 0x7, len: 3, value: 1 },
    VlcEntry { code: 0x5, len: 4, value: 2 },
    VlcEntry { code: 0x4, len: 4, value: 3 },
    VlcEntry { code: 0x6, len: 3, value: 4 },
    VlcEntry { code: 0x5, len: 3, value: 5 },
    VlcEntry { code: 0x4, len: 3, value: 6 },
    VlcEntry { code: 0x3, len: 4, value: 7 },
    VlcEntry { code: 0x3, len: 3, value: 8 },
    VlcEntry { code: 0x2, len: 4, value: 9 },
    VlcEntry { code: 0x2, len: 5, value: 10 },
    VlcEntry { code: 0x1, len: 5, value: 11 },
    VlcEntry { code: 0x0, len: 5, value: 12 },
];

static TZ_5: &[VlcEntry] = &[
    VlcEntry { code: 0x5, len: 4, value: 0 },
    VlcEntry { code: 0x4, len: 4, value: 1 },
    VlcEntry { code: 0x3, len: 4, value: 2 },
    VlcEntry { code: 0x7, len: 3, value: 3 },
    VlcEntry { code: 0x6, len: 3, value: 4 },
    VlcEntry { code: 0x5, len: 3, value: 5 },
    VlcEntry { code: 0x4, len: 3, value: 6 },
    VlcEntry { code: 0x3, len: 3, value: 7 },
    VlcEntry { code: 0x2, len: 4, value: 8 },
    VlcEntry { code: 0x1, len: 5, value: 9 },
    VlcEntry { code: 0x1, len: 4, value: 10 },
    VlcEntry { code: 0x0, len: 5, value: 11 },
];

static TZ_6: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 6, value: 0 },
    VlcEntry { code: 0x1, len: 5, value: 1 },
    VlcEntry { code: 0x7, len: 3, value: 2 },
    VlcEntry { code: 0x6, len: 3, value: 3 },
    VlcEntry { code: 0x5, len: 3, value: 4 },
    VlcEntry { code: 0x4, len: 3, value: 5 },
    VlcEntry { code: 0x3, len: 3, value: 6 },
    VlcEntry { code: 0x2, len: 3, value: 7 },
    VlcEntry { code: 0x1, len: 4, value: 8 },
    VlcEntry { code: 0x1, len: 3, value: 9 },
    VlcEntry { code: 0x0, len: 6, value: 10 },
];

static TZ_7: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 6, value: 0 },
    VlcEntry { code: 0x1, len: 5, value: 1 },
    VlcEntry { code: 0x5, len: 3, value: 2 },
    VlcEntry { code: 0x4, len: 3, value: 3 },
    VlcEntry { code: 0x3, len: 3, value: 4 },
    VlcEntry { code: 0x3, len: 2, value: 5 },
    VlcEntry { code: 0x2, len: 3, value: 6 },
    VlcEntry { code: 0x1, len: 4, value: 7 },
    VlcEntry { code: 0x1, len: 3, value: 8 },
    VlcEntry { code: 0x0, len: 6, value: 9 },
];

static TZ_8: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 6, value: 0 },
    VlcEntry { code: 0x1, len: 4, value: 1 },
    VlcEntry { code: 0x1, len: 5, value: 2 },
    VlcEntry { code: 0x3, len: 3, value: 3 },
    VlcEntry { code: 0x3, len: 2, value: 4 },
    VlcEntry { code: 0x2, len: 2, value: 5 },
    VlcEntry { code: 0x2, len: 3, value: 6 },
    VlcEntry { code: 0x1, len: 3, value: 7 },
    VlcEntry { code: 0x0, len: 6, value: 8 },
];

static TZ_9: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 6, value: 0 },
    VlcEntry { code: 0x0, len: 6, value: 1 },
    VlcEntry { code: 0x1, len: 4, value: 2 },
    VlcEntry { code: 0x3, len: 2, value: 3 },
    VlcEntry { code: 0x2, len: 2, value: 4 },
    VlcEntry { code: 0x1, len: 3, value: 5 },
    VlcEntry { code: 0x1, len: 2, value: 6 },
    VlcEntry { code: 0x1, len: 5, value: 7 },
];

static TZ_10: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 5, value: 0 },
    VlcEntry { code: 0x0, len: 5, value: 1 },
    VlcEntry { code: 0x1, len: 3, value: 2 },
    VlcEntry { code: 0x3, len: 2, value: 3 },
    VlcEntry { code: 0x2, len: 2, value: 4 },
    VlcEntry { code: 0x1, len: 2, value: 5 },
    VlcEntry { code: 0x1, len: 4, value: 6 },
];

static TZ_11: &[VlcEntry] = &[
    VlcEntry { code: 0x0, len: 4, value: 0 },
    VlcEntry { code: 0x1, len: 4, value: 1 },
    VlcEntry { code: 0x1, len: 3, value: 2 },
    VlcEntry { code: 0x2, len: 3, value: 3 },
    VlcEntry { code: 0x1, len: 1, value: 4 },
    VlcEntry { code: 0x3, len: 3, value: 5 },
];

static TZ_12: &[VlcEntry] = &[
    VlcEntry { code: 0x0, len: 4, value: 0 },
    VlcEntry { code: 0x1, len: 4, value: 1 },
    VlcEntry { code: 0x1, len: 2, value: 2 },
    VlcEntry { code: 0x1, len: 1, value: 3 },
    VlcEntry { code: 0x1, len: 3, value: 4 },
];

static TZ_13: &[VlcEntry] = &[
    VlcEntry { code: 0x0, len: 3, value: 0 },
    VlcEntry { code: 0x1, len: 3, value: 1 },
    VlcEntry { code: 0x1, len: 1, value: 2 },
    VlcEntry { code: 0x1, len: 2, value: 3 },
];

static TZ_14: &[VlcEntry] = &[
    VlcEntry { code: 0x0, len: 2, value: 0 },
    VlcEntry { code: 0x1, len: 2, value: 1 },
    VlcEntry { code: 0x1, len: 1, value: 2 },
];

static TZ_15: &[VlcEntry] = &[
    VlcEntry { code: 0x0, len: 1, value: 0 },
    VlcEntry { code: 0x1, len: 1, value: 1 },
];

static TZ_CDC_1: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 1, value: 0 },
    VlcEntry { code: 0x1, len: 2, value: 1 },
    VlcEntry { code: 0x1, len: 3, value: 2 },
    VlcEntry { code: 0x0, len: 3, value: 3 },
];

static TZ_CDC_2: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 1, value: 0 },
    VlcEntry { code: 0x1, len: 2, value: 1 },
    VlcEntry { code: 0x0, len: 2, value: 2 },
];

static TZ_CDC_3: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 1, value: 0 },
    VlcEntry { code: 0x0, len: 1, value: 1 },
];

static RB_1: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 1, value: 0 },
    VlcEntry { code: 0x0, len: 1, value: 1 },
];

static RB_2: &[VlcEntry] = &[
    VlcEntry { code: 0x1, len: 1, value: 0 },
    VlcEntry { code: 0x1, len: 2, value: 1 },
    VlcEntry { code: 0x0, len: 2, value: 2 },
];

static RB_3: &[VlcEntry] = &[
    VlcEntry { code: 0x3, len: 2, value: 0 },
    VlcEntry { code: 0x2, len: 2, value: 1 },
    VlcEntry { code: 0x1, len: 2, value: 2 },
    VlcEntry { code: 0x0, len: 2, value: 3 },
];

static RB_4: &[VlcEntry] = &[
    VlcEntry { code: 0x3, len: 2, value: 0 },
    VlcEntry { code: 0x2, len: 2, value: 1 },
    VlcEntry { code: 0x1, len: 2, value: 2 },
    VlcEntry { code: 0x1, len: 3, value: 3 },
    VlcEntry { code: 0x0, len: 3, value: 4 },
];

static RB_5: &[VlcEntry] = &[
    VlcEntry { code: 0x3, len: 2, value: 0 },
    VlcEntry { code: 0x2, len: 2, value: 1 },
    VlcEntry { code: 0x3, len: 3, value: 2 },
    VlcEntry { code: 0x2, len: 3, value: 3 },
    VlcEntry { code: 0x1, len: 3, value: 4 },
    VlcEntry { code: 0x0, len: 3, value: 5 },
];

static RB_6: &[VlcEntry] = &[
    VlcEntry { code: 0x3, len: 2, value: 0 },
    VlcEntry { code: 0x0, len: 3, value: 1 },
    VlcEntry { code: 0x1, len: 3, value: 2 },
    VlcEntry { code: 0x3, len: 3, value: 3 },
    VlcEntry { code: 0x2, len: 3, value: 4 },
    VlcEntry { code: 0x5, len: 3, value: 5 },
    VlcEntry { code: 0x4, len: 3, value: 6 },
];

static RB_7: &[VlcEntry] = &[
    VlcEntry { code: 0x7, len: 3, value: 0 },
    VlcEntry { code: 0x6, len: 3, value: 1 },
    VlcEntry { code: 0x5, len: 3, value: 2 },
    VlcEntry { code: 0x4, len: 3, value: 3 },
    VlcEntry { code: 0x3, len: 3, value: 4 },
    VlcEntry { code: 0x2, len: 3, value: 5 },
    VlcEntry { code: 0x1, len: 3, value: 6 },
    VlcEntry { code: 0x1, len: 4, value: 7 },
    VlcEntry { code: 0x1, len: 5, value: 8 },
    VlcEntry { code: 0x1, len: 6, value: 9 },
    VlcEntry { code: 0x1, len: 7, value: 10 },
    VlcEntry { code: 0x1, len: 8, value: 11 },
    VlcEntry { code: 0x1, len: 9, value: 12 },
    VlcEntry { code: 0x1, len: 10, value: 13 },
    VlcEntry { code: 0x1, len: 11, value: 14 },
];

static RB_8: &[VlcEntry] = &[
    VlcEntry { code: 0x7, len: 3, value: 0 },
    VlcEntry { code: 0x6, len: 3, value: 1 },
    VlcEntry { code: 0x5, len: 3, value: 2 },
    VlcEntry { code: 0x4, len: 3, value: 3 },
    VlcEntry { code: 0x3, len: 3, value: 4 },
    VlcEntry { code: 0x2, len: 3, value: 5 },
    VlcEntry { code: 0x1, len: 3, value: 6 },
    VlcEntry { code: 0x1, len: 4, value: 7 },
    VlcEntry { code: 0x1, len: 5, value: 8 },
    VlcEntry { code: 0x1, len: 6, value: 9 },
    VlcEntry { code: 0x1, len: 7, value: 10 },
    VlcEntry { code: 0x1, len: 8, value: 11 },
    VlcEntry { code: 0x1, len: 9, value: 12 },
    VlcEntry { code: 0x1, len: 10, value: 13 },
    VlcEntry { code: 0x1, len: 11, value: 14 },
];

static RB_9: &[VlcEntry] = &[
    VlcEntry { code: 0x7, len: 3, value: 0 },
    VlcEntry { code: 0x6, len: 3, value: 1 },
    VlcEntry { code: 0x5, len: 3, value: 2 },
    VlcEntry { code: 0x4, len: 3, value: 3 },
    VlcEntry { code: 0x3, len: 3, value: 4 },
    VlcEntry { code: 0x2, len: 3, value: 5 },
    VlcEntry { code: 0x1, len: 3, value: 6 },
    VlcEntry { code: 0x1, len: 4, value: 7 },
    VlcEntry { code: 0x1, len: 5, value: 8 },
    VlcEntry { code: 0x1, len: 6, value: 9 },
    VlcEntry { code: 0x1, len: 7, value: 10 },
    VlcEntry { code: 0x1, len: 8, value: 11 },
    VlcEntry { code: 0x1, len: 9, value: 12 },
    VlcEntry { code: 0x1, len: 10, value: 13 },
    VlcEntry { code: 0x1, len: 11, value: 14 },
];

static RB_10: &[VlcEntry] = &[
    VlcEntry { code: 0x7, len: 3, value: 0 },
    VlcEntry { code: 0x6, len: 3, value: 1 },
    VlcEntry { code: 0x5, len: 3, value: 2 },
    VlcEntry { code: 0x4, len: 3, value: 3 },
    VlcEntry { code: 0x3, len: 3, value: 4 },
    VlcEntry { code: 0x2, len: 3, value: 5 },
    VlcEntry { code: 0x1, len: 3, value: 6 },
    VlcEntry { code: 0x1, len: 4, value: 7 },
    VlcEntry { code: 0x1, len: 5, value: 8 },
    VlcEntry { code: 0x1, len: 6, value: 9 },
    VlcEntry { code: 0x1, len: 7, value: 10 },
    VlcEntry { code: 0x1, len: 8, value: 11 },
    VlcEntry { code: 0x1, len: 9, value: 12 },
    VlcEntry { code: 0x1, len: 10, value: 13 },
    VlcEntry { code: 0x1, len: 11, value: 14 },
];

static RB_11: &[VlcEntry] = &[
    VlcEntry { code: 0x7, len: 3, value: 0 },
    VlcEntry { code: 0x6, len: 3, value: 1 },
    VlcEntry { code: 0x5, len: 3, value: 2 },
    VlcEntry { code: 0x4, len: 3, value: 3 },
    VlcEntry { code: 0x3, len: 3, value: 4 },
    VlcEntry { code: 0x2, len: 3, value: 5 },
    VlcEntry { code: 0x1, len: 3, value: 6 },
    VlcEntry { code: 0x1, len: 4, value: 7 },
    VlcEntry { code: 0x1, len: 5, value: 8 },
    VlcEntry { code: 0x1, len: 6, value: 9 },
    VlcEntry { code: 0x1, len: 7, value: 10 },
    VlcEntry { code: 0x1, len: 8, value: 11 },
    VlcEntry { code: 0x1, len: 9, value: 12 },
    VlcEntry { code: 0x1, len: 10, value: 13 },
    VlcEntry { code: 0x1, len: 11, value: 14 },
];

static RB_12: &[VlcEntry] = &[
    VlcEntry { code: 0x7, len: 3, value: 0 },
    VlcEntry { code: 0x6, len: 3, value: 1 },
    VlcEntry { code: 0x5, len: 3, value: 2 },
    VlcEntry { code: 0x4, len: 3, value: 3 },
    VlcEntry { code: 0x3, len: 3, value: 4 },
    VlcEntry { code: 0x2, len: 3, value: 5 },
    VlcEntry { code: 0x1, len: 3, value: 6 },
    VlcEntry { code: 0x1, len: 4, value: 7 },
    VlcEntry { code: 0x1, len: 5, value: 8 },
    VlcEntry { code: 0x1, len: 6, value: 9 },
    VlcEntry { code: 0x1, len: 7, value: 10 },
    VlcEntry { code: 0x1, len: 8, value: 11 },
    VlcEntry { code: 0x1, len: 9, value: 12 },
    VlcEntry { code: 0x1, len: 10, value: 13 },
    VlcEntry { code: 0x1, len: 11, value: 14 },
];

static RB_13: &[VlcEntry] = &[
    VlcEntry { code: 0x7, len: 3, value: 0 },
    VlcEntry { code: 0x6, len: 3, value: 1 },
    VlcEntry { code: 0x5, len: 3, value: 2 },
    VlcEntry { code: 0x4, len: 3, value: 3 },
    VlcEntry { code: 0x3, len: 3, value: 4 },
    VlcEntry { code: 0x2, len: 3, value: 5 },
    VlcEntry { code: 0x1, len: 3, value: 6 },
    VlcEntry { code: 0x1, len: 4, value: 7 },
    VlcEntry { code: 0x1, len: 5, value: 8 },
    VlcEntry { code: 0x1, len: 6, value: 9 },
    VlcEntry { code: 0x1, len: 7, value: 10 },
    VlcEntry { code: 0x1, len: 8, value: 11 },
    VlcEntry { code: 0x1, len: 9, value: 12 },
    VlcEntry { code: 0x1, len: 10, value: 13 },
    VlcEntry { code: 0x1, len: 11, value: 14 },
];

static RB_14: &[VlcEntry] = &[
    VlcEntry { code: 0x7, len: 3, value: 0 },
    VlcEntry { code: 0x6, len: 3, value: 1 },
    VlcEntry { code: 0x5, len: 3, value: 2 },
    VlcEntry { code: 0x4, len: 3, value: 3 },
    VlcEntry { code: 0x3, len: 3, value: 4 },
    VlcEntry { code: 0x2, len: 3, value: 5 },
    VlcEntry { code: 0x1, len: 3, value: 6 },
    VlcEntry { code: 0x1, len: 4, value: 7 },
    VlcEntry { code: 0x1, len: 5, value: 8 },
    VlcEntry { code: 0x1, len: 6, value: 9 },
    VlcEntry { code: 0x1, len: 7, value: 10 },
    VlcEntry { code: 0x1, len: 8, value: 11 },
    VlcEntry { code: 0x1, len: 9, value: 12 },
    VlcEntry { code: 0x1, len: 10, value: 13 },
    VlcEntry { code: 0x1, len: 11, value: 14 },
];

static RB_15: &[VlcEntry] = &[
    VlcEntry { code: 0x7, len: 3, value: 0 },
    VlcEntry { code: 0x6, len: 3, value: 1 },
    VlcEntry { code: 0x5, len: 3, value: 2 },
    VlcEntry { code: 0x4, len: 3, value: 3 },
    VlcEntry { code: 0x3, len: 3, value: 4 },
    VlcEntry { code: 0x2, len: 3, value: 5 },
    VlcEntry { code: 0x1, len: 3, value: 6 },
    VlcEntry { code: 0x1, len: 4, value: 7 },
    VlcEntry { code: 0x1, len: 5, value: 8 },
    VlcEntry { code: 0x1, len: 6, value: 9 },
    VlcEntry { code: 0x1, len: 7, value: 10 },
    VlcEntry { code: 0x1, len: 8, value: 11 },
    VlcEntry { code: 0x1, len: 9, value: 12 },
    VlcEntry { code: 0x1, len: 10, value: 13 },
    VlcEntry { code: 0x1, len: 11, value: 14 },
];

/// Validated CAVLC table set, built once on first use.
pub(crate) static TABLES: LazyLock<Tables> = LazyLock::new(build);

pub(crate) fn tables() -> &'static Tables {
    &TABLES
}

pub(crate) struct Tables {
    /// coeff_token indexed by context: 0 = 0<=nC<2, 1 = 2<=nC<4,
    /// 2 = 4<=nC<8, 3 = nC==-1 (ChromaDC 4:2:0). Entry value packs
    /// `TotalCoeff * 4 + TrailingOnes`. nC>=8 is a later increment.
    pub coeff_token: [VlcTable; 4],
    /// total_zeros for 4x4 blocks by tzVlcIndex (1..=15; index 0 unused).
    pub total_zeros_4x4: [VlcTable; 16],
    /// ChromaDC 2x2 total_zeros by tzVlcIndex (1..=3; index 0 unused).
    pub total_zeros_chroma_dc: [VlcTable; 4],
    /// run_before by zerosLeft (1..=15; index 0 unused).
    pub run_before: [VlcTable; 16],
}

fn build() -> Tables {
    // Generator + tables_tests double-validate; expect here cannot fire
    // unless the generator itself broke, which the tests catch.
    #![allow(clippy::expect_used)]
    let table = |entries: &'static [VlcEntry]| {
        VlcTable::new(entries.to_vec()).expect("validated")
    };
    Tables {
        coeff_token: [
            table(CT_NC01),
            table(CT_NC24),
            table(CT_NC48),
            table(CT_CDC),
        ],
        total_zeros_4x4: std::array::from_fn(|index| match index {
            1 => table(TZ_1),
            2 => table(TZ_2),
            3 => table(TZ_3),
            4 => table(TZ_4),
            5 => table(TZ_5),
            6 => table(TZ_6),
            7 => table(TZ_7),
            8 => table(TZ_8),
            9 => table(TZ_9),
            10 => table(TZ_10),
            11 => table(TZ_11),
            12 => table(TZ_12),
            13 => table(TZ_13),
            14 => table(TZ_14),
            15 => table(TZ_15),
            _ => VlcTable::new(Vec::new()).expect("empty is valid"),
        }),
        total_zeros_chroma_dc: std::array::from_fn(|index| match index {
            1 => table(TZ_CDC_1),
            2 => table(TZ_CDC_2),
            3 => table(TZ_CDC_3),
            _ => VlcTable::new(Vec::new()).expect("empty is valid"),
        }),
        run_before: std::array::from_fn(|index| match index {
            1 => table(RB_1),
            2 => table(RB_2),
            3 => table(RB_3),
            4 => table(RB_4),
            5 => table(RB_5),
            6 => table(RB_6),
            7 => table(RB_7),
            8 => table(RB_8),
            9 => table(RB_9),
            10 => table(RB_10),
            11 => table(RB_11),
            12 => table(RB_12),
            13 => table(RB_13),
            14 => table(RB_14),
            15 => table(RB_15),
            _ => VlcTable::new(Vec::new()).expect("empty is valid"),
        }),
    }
}

