//! Deterministic alert-effect oracle with lost-ACK reconciliation.

use std::collections::BTreeMap;

use fss_core::{
    CanonicalDecode, CanonicalDecoder, CanonicalEncode, CanonicalEncoder, ContentDigest,
    EffectIntent, EffectJournal, EffectState, EventHypothesis, EventState, IdempotencyKey,
    LedgerAnchor, Obligation, ObligationId, OperationId, OperationReceipt, TimestampNs,
};
use fss_ledger::{DurableLedgerError, DurableReferenceLedger, JournalError};

use crate::{
    ReferenceError, ReferenceEventReceipt, ReferencePolicyAction, ReferencePolicyDecision,
};

const MAX_ALERT_CHANNEL_BYTES: usize = 256;

/// Immutable prepared alert plan. Preparation grants no external dispatch by itself.
///
/// # Plane boundary (ADR-0001, NEG-003)
///
/// The plan carries an effect-plane `EffectIntent` created by the effect plane. Invariant 5:
/// a model or VLM output such as [`crate::MockModelOutput`] can never convert into that intent.
///
/// ```compile_fail,E0277
/// use fss_core::effect::EffectIntent;
/// use fss_reference::MockModelOutput;
///
/// fn forbidden_model_effect(output: MockModelOutput) {
///     // adr-0001/inv-5-reference: no `From<MockModelOutput>` exists for `EffectIntent`.
///     let intent: EffectIntent = output.into();
///     let _ = intent;
/// }
/// ```
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReferenceAlertPlan {
    /// Exact effect intent registered in the effect journal.
    pub intent: EffectIntent,
    /// Existing terminal-proof obligation owned by the operation.
    pub obligation_id: ObligationId,
    /// Exact canonical event graph being reported.
    pub event_root: ContentDigest,
    /// Event revision fingerprint.
    pub event_revision_digest: ContentDigest,
    /// Authority anchor after publication.
    pub authority_anchor: LedgerAnchor,
    /// Stable bounded alert channel identity.
    pub channel: String,
    /// Exact canonical encoding of the event revision whose SHA-256 is `event_revision_digest`.
    ///
    /// Hydration only: dispatch admits it solely when it hashes to the revision the authority
    /// ledger currently holds for this event, then re-derives eligibility from it (fss-wjisz).
    pub event_revision_encoding: Vec<u8>,
    /// Exact canonical encodings of every earlier revision of the event, oldest first.
    ///
    /// Hydration only: dispatch admits each solely when it hashes to the authority ledger's
    /// `event_revision` witness at its position, then recomputes the lineage tamper status from
    /// them (fss-2uftm).
    pub prior_revision_encodings: Vec<Vec<u8>>,
    /// Number of authority batches when the plan was prepared: the prepare-time ledger head.
    pub prepared_head_sequence: u64,
    /// Batch digest of the prepare-time ledger head.
    ///
    /// The head is read from the authority ledger at preparation and bound into the intent's
    /// precondition digest, which the effect journal records with the operation.
    pub prepared_head_digest: ContentDigest,
}

/// Deterministic provider fault choice for one dispatch attempt.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReferenceProviderBehavior {
    /// Provider stores the message and returns trustworthy delivery proof.
    Deliver,
    /// Provider stores the message but the caller loses the acknowledgement.
    LoseAckAfterDelivery,
    /// Provider proves the request failed before any message was created.
    FailBeforeDelivery,
}

/// Result of dispatching an intent through the reference alert provider.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProviderDispatch {
    /// Provider successfully delivered the message and generated delivery proof.
    Delivered(ContentDigest),
    /// Acknowledgement was lost after delivery.
    LostAck,
    /// Known failure before delivery with failure proof.
    KnownFailure(ContentDigest),
    /// Conflicting intent attempted under an existing idempotency key.
    ConflictingIdempotency,
}

/// Provider-generated observation receipt for a delivered message.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProviderObservationReceipt {
    /// Nonce generated by provider; cannot be derived from intent alone.
    pub provider_nonce: ContentDigest,
    /// Message digest of the dispatched intent.
    pub message_digest: ContentDigest,
}

impl ProviderObservationReceipt {
    /// Canonical encoded bytes of the observation receipt.
    #[must_use]
    pub fn canonical_bytes(&self) -> Vec<u8> {
        let mut encoder = CanonicalEncoder::new();
        encoder.text("fss.effect_proof.v1");
        encoder.digest(self.provider_nonce);
        encoder.digest(self.message_digest);
        encoder.finish()
    }

    /// SHA-256 digest of the canonical receipt bytes.
    #[must_use]
    pub fn receipt_digest(&self) -> ContentDigest {
        ContentDigest::sha256(&self.canonical_bytes())
    }
}

/// Typed failure proof issued by the reference provider oracle.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProviderFailureReceipt {
    /// Independent provider-generated dispatch nonce.
    pub provider_nonce: ContentDigest,
    /// Canonical digest of the dispatched intent payload.
    pub message_digest: ContentDigest,
    /// Error code or failure reason issued by the provider.
    pub error_code: String,
}

impl ProviderFailureReceipt {
    /// Canonical encoded bytes of the failure receipt.
    #[must_use]
    pub fn canonical_bytes(&self) -> Vec<u8> {
        let mut encoder = CanonicalEncoder::new();
        encoder.text("fss.effect_proof.v1");
        encoder.digest(self.provider_nonce);
        encoder.digest(self.message_digest);
        encoder.text(&self.error_code);
        encoder.finish()
    }

    /// SHA-256 digest of the canonical receipt bytes.
    #[must_use]
    pub fn receipt_digest(&self) -> ContentDigest {
        ContentDigest::sha256(&self.canonical_bytes())
    }
}

/// Bounded stable terminal predicate for reference alert obligations.
pub const REFERENCE_ALERT_TERMINAL_PREDICATE: &str =
    "provider delivery is independently reconciled";

pub const REFERENCE_ALERT_FAILURE_REASON: &str = "failed_before_delivery";

#[derive(Clone, Debug, Eq, PartialEq)]
struct ProviderMessage {
    operation_id: OperationId,
    effect_class: String,
    request_digest: ContentDigest,
    precondition_digest: ContentDigest,
    receipt: ProviderObservationReceipt,
}

impl ProviderMessage {
    fn matches_intent(&self, intent: &EffectIntent) -> bool {
        self.operation_id == intent.operation_id
            && self.effect_class == intent.effect_class
            && self.request_digest == intent.request_digest
            && self.precondition_digest == intent.precondition_digest
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct ProviderFailureMessage {
    operation_id: OperationId,
    effect_class: String,
    request_digest: ContentDigest,
    precondition_digest: ContentDigest,
    receipt: ProviderFailureReceipt,
}

impl ProviderFailureMessage {
    fn matches_intent(&self, intent: &EffectIntent) -> bool {
        self.operation_id == intent.operation_id
            && self.effect_class == intent.effect_class
            && self.request_digest == intent.request_digest
            && self.precondition_digest == intent.precondition_digest
    }
}

/// Trait for in-memory or durable effect journals to transition operations on refusal.
pub(crate) trait AlertEffectTransitioner {
    /// Look up an operation by identity.
    fn operation(&self, operation_id: &OperationId) -> Option<&OperationReceipt>;
    /// Look up an obligation by identity.
    fn obligation(&self, obligation_id: &ObligationId) -> Option<&Obligation>;
    /// Transition an operation to [`EffectState::Cancelled`] with cancel proof and reason.
    fn transition_cancelled(
        &mut self,
        operation_id: &OperationId,
        now: TimestampNs,
        proof: ContentDigest,
        reason: String,
    ) -> Result<(), ReferenceError>;
    /// Transition an operation to [`EffectState::Committed`].
    fn transition_committed(
        &mut self,
        operation_id: &OperationId,
        now: TimestampNs,
    ) -> Result<(), ReferenceError>;
    /// Transition an operation to [`EffectState::AdapterAccepted`].
    fn transition_adapter_accepted(
        &mut self,
        operation_id: &OperationId,
        now: TimestampNs,
    ) -> Result<OperationReceipt, ReferenceError>;
    /// Mark an operation as [`EffectState::Indeterminate`].
    fn mark_indeterminate(
        &mut self,
        operation_id: &OperationId,
        now: TimestampNs,
        reason: &str,
    ) -> Result<OperationReceipt, ReferenceError>;
    /// Transition an operation to [`EffectState::Failed`].
    fn transition_failed(
        &mut self,
        operation_id: &OperationId,
        now: TimestampNs,
        proof: Option<ContentDigest>,
        reason: Option<String>,
    ) -> Result<OperationReceipt, ReferenceError>;
}

impl AlertEffectTransitioner for EffectJournal {
    fn operation(&self, operation_id: &OperationId) -> Option<&OperationReceipt> {
        self.operation(operation_id)
    }

    fn obligation(&self, obligation_id: &ObligationId) -> Option<&Obligation> {
        self.obligations()
            .find(|o| &o.obligation_id == obligation_id)
    }

    fn transition_cancelled(
        &mut self,
        operation_id: &OperationId,
        now: TimestampNs,
        proof: ContentDigest,
        reason: String,
    ) -> Result<(), ReferenceError> {
        self.transition(
            operation_id,
            EffectState::Cancelled,
            now,
            Some(proof),
            Some(reason),
        )
        .map(|_| ())
        .map_err(ReferenceError::from)
    }

    fn transition_committed(
        &mut self,
        operation_id: &OperationId,
        now: TimestampNs,
    ) -> Result<(), ReferenceError> {
        self.transition(operation_id, EffectState::Committed, now, None, None)
            .map(|_| ())
            .map_err(ReferenceError::from)
    }

    fn transition_adapter_accepted(
        &mut self,
        operation_id: &OperationId,
        now: TimestampNs,
    ) -> Result<OperationReceipt, ReferenceError> {
        self.transition(operation_id, EffectState::AdapterAccepted, now, None, None)
            .cloned()
            .map_err(ReferenceError::from)
    }

    fn mark_indeterminate(
        &mut self,
        operation_id: &OperationId,
        now: TimestampNs,
        reason: &str,
    ) -> Result<OperationReceipt, ReferenceError> {
        self.mark_indeterminate(operation_id, now, reason)
            .cloned()
            .map_err(ReferenceError::from)
    }

    fn transition_failed(
        &mut self,
        operation_id: &OperationId,
        now: TimestampNs,
        proof: Option<ContentDigest>,
        reason: Option<String>,
    ) -> Result<OperationReceipt, ReferenceError> {
        self.transition(operation_id, EffectState::Failed, now, proof, reason)
            .cloned()
            .map_err(ReferenceError::from)
    }
}

/// Computes a canonical cancellation proof bound to the operation identity,
/// the prepared authority anchor, and the displacing authority anchor (P10).
#[must_use]
pub fn alert_cancel_proof(
    operation_id: &OperationId,
    prepared_anchor: &LedgerAnchor,
    displacing_anchor: &LedgerAnchor,
) -> ContentDigest {
    let mut encoder = CanonicalEncoder::new();
    encoder.text("fss.alert_cancel_proof.v1");
    operation_id.encode_canonical(&mut encoder);
    prepared_anchor.encode_canonical(&mut encoder);
    displacing_anchor.encode_canonical(&mut encoder);
    ContentDigest::sha256(&encoder.finish())
}

/// Verifies event alert eligibility against policy, corroboration, and sensor integrity.
pub(crate) fn verify_event_alert_eligibility(
    state: fss_core::EventState,
    action: ReferencePolicyAction,
    evidence: &[fss_core::EventEvidence],
) -> Result<(), ReferenceError> {
    if action != ReferencePolicyAction::PrepareAlert || state != fss_core::EventState::Corroborated
    {
        return Err(ReferenceError::InvalidSpec("alert_not_eligible"));
    }
    if evidence
        .iter()
        .any(fss_core::EventEvidence::reports_sensor_tamper)
    {
        return Err(fss_core::ContractError::SensorIntegrityRisk.into());
    }
    Ok(())
}

/// Exact canonical encoding hashed by [`EventHypothesis::revision_digest`].
pub(crate) fn event_revision_encoding(event: &EventHypothesis) -> Vec<u8> {
    let mut encoder = CanonicalEncoder::new();
    encoder.text("fss.canonical.v1");
    encoder.text(EventHypothesis::SCHEMA);
    event.encode_canonical(&mut encoder);
    encoder.finish()
}

/// Decodes the event revision a plan carries, admitting it only as the exact revision named by
/// `revision_digest`.
fn hydrate_event_revision(
    encoding: &[u8],
    revision_digest: ContentDigest,
) -> Result<EventHypothesis, ReferenceError> {
    if ContentDigest::sha256(encoding) != revision_digest {
        return Err(ReferenceError::StaleEventAuthority);
    }
    let event = decode_event_revision(encoding)?;
    if event.revision_digest() != revision_digest {
        return Err(ReferenceError::StaleEventAuthority);
    }
    Ok(event)
}

/// Decodes one exact canonical event revision encoding, with no authority binding of its own.
fn decode_event_revision(encoding: &[u8]) -> Result<EventHypothesis, ReferenceError> {
    let mut decoder = CanonicalDecoder::new(encoding);
    if decoder.text()? != "fss.canonical.v1" || decoder.text()? != EventHypothesis::SCHEMA {
        return Err(ReferenceError::StaleEventAuthority);
    }
    let event = EventHypothesis::decode_canonical(&mut decoder)?;
    decoder.ensure_finished()?;
    Ok(event)
}

/// Decodes the earlier revisions a receipt or plan carries, bounded by the lineage depth limit.
///
/// Decoding binds nothing: [`recompute_lineage_tamper_status`] admits the revisions only when they
/// are exactly the ledger's `event_revision` witnesses for the event.
pub(crate) fn decode_prior_revisions(
    encodings: &[Vec<u8>],
) -> Result<Vec<EventHypothesis>, ReferenceError> {
    if encodings.len() >= fss_core::event::MAX_LINEAGE_DEPTH {
        return Err(ReferenceError::StaleEventAuthority);
    }
    encodings
        .iter()
        .map(|encoding| decode_event_revision(encoding.as_slice()))
        .collect()
}

/// Recomputes the lineage sensor-tamper status of `current` from the authority ledger (fss-2uftm).
///
/// The ledger names every revision of the event: the `event_revision` deltas of its event object,
/// in ledger order. `prior` followed by `current` must be exactly those revisions (each hashing to
/// the witness at its position, at its generation) and one supersession chain, so `current` is the
/// event's current revision. The status is recomputed from them with the one accumulation
/// verification, replay and publication use. The `sensor_tamper_status` witness published with
/// `current` is a cross-check only: it must equal the recomputed status and is never trusted alone,
/// and neither is any receipt.
///
/// Shared by alert preparation, alert dispatch and situation compilation.
pub(crate) fn recompute_lineage_tamper_status(
    authority: &DurableReferenceLedger,
    current: &EventHypothesis,
    prior: &[EventHypothesis],
) -> Result<fss_core::SensorTamperStatus, ReferenceError> {
    let object_id =
        fss_core::ObjectId::parse(format!("object:event:{}", current.event_id.as_str()))?;
    let batches = authority.batches();
    let published: Vec<(usize, &fss_core::EvidenceDelta)> = batches
        .iter()
        .enumerate()
        .flat_map(|(index, batch)| {
            batch
                .deltas
                .iter()
                .filter(|delta| delta.object_id == object_id && delta.family == "event_revision")
                .map(move |delta| (index, delta))
        })
        .collect();
    let lineage: Vec<&EventHypothesis> = prior.iter().chain(std::iter::once(current)).collect();
    if published.len() != lineage.len() {
        return Err(ReferenceError::StaleEventAuthority);
    }
    let mut predecessor: Option<ContentDigest> = None;
    for ((_, delta), revision) in published.iter().zip(&lineage) {
        let digest = revision.revision_digest();
        if delta.witness_digest != Some(digest)
            || delta.new_generation != revision.revision
            || revision.event_id != current.event_id
            || revision.supersedes != predecessor
        {
            return Err(ReferenceError::StaleEventAuthority);
        }
        predecessor = Some(digest);
    }
    let status = fss_core::event::compute_sensor_tamper_status(lineage.iter().copied(), None);
    let (current_batch, current_delta) = published
        .last()
        .ok_or(ReferenceError::StaleEventAuthority)?;
    let witnessed = batches.get(*current_batch).is_some_and(|batch| {
        batch.deltas.iter().any(|delta| {
            delta.family == "sensor_tamper_status"
                && delta.payload_digest == current_delta.payload_digest
                && delta.witness_digest == Some(status.canonical_digest())
        })
    });
    if !witnessed {
        return Err(ReferenceError::InvalidSpec(
            "sensor_tamper_witness_mismatch",
        ));
    }
    Ok(status)
}

/// The alert eligibility preparation and dispatch share (fss-wjisz, fss-2uftm).
///
/// The revision's own state, committed action and edges must be eligible, and its lineage,
/// recomputed from the authority ledger by [`recompute_lineage_tamper_status`], must hold no open,
/// unretired sensor tamper.
pub(crate) fn verify_alert_eligibility_in_lineage(
    authority: &DurableReferenceLedger,
    event: &EventHypothesis,
    action: ReferencePolicyAction,
    prior: &[EventHypothesis],
) -> Result<fss_core::SensorTamperStatus, ReferenceError> {
    verify_event_alert_eligibility(event.state, action, &event.evidence)?;
    let status = recompute_lineage_tamper_status(authority, event, prior)?;
    if status.has_open_tamper() {
        return Err(fss_core::ContractError::SensorIntegrityRisk.into());
    }
    Ok(status)
}

/// Policy action an authority event revision commits to.
///
/// The reference policy prepares an alert only on the decision path it fingerprints for
/// [`ReferencePolicyAction::PrepareAlert`] over this exact event identity, state, and evidence;
/// every other decision path holds.
fn committed_policy_action(event: &EventHypothesis) -> ReferencePolicyAction {
    let alert_path = crate::policy::policy_decision_path(
        &event.event_id,
        &event.evidence,
        event.state,
        ReferencePolicyAction::PrepareAlert,
    );
    if event.decision_path == alert_path {
        ReferencePolicyAction::PrepareAlert
    } else {
        ReferencePolicyAction::Hold
    }
}

/// Maps a failed bounded durable-head check to a typed dispatch refusal (fail closed).
///
/// A durable journal that moved under this handle (another handle's commit, an appended, torn, or
/// corrupt suffix, a truncation, or a replaced trailer) makes this handle's view of event
/// authority stale. Anything else (a missing path, an I/O failure, an unresolved append) makes
/// current authority unreadable. Both refuse; neither is skipped (fss-wjisz).
fn authority_head_refusal(error: DurableLedgerError) -> ReferenceError {
    match error {
        DurableLedgerError::Journal(JournalError::ExternalMutation { .. }) => {
            ReferenceError::StaleEventAuthority
        }
        other => ReferenceError::AuthorityLedgerUnreadable(Box::new(other)),
    }
}

/// Index of the batch that published the ledger's current revision of the event the plan names.
///
/// The event object is the one whose `event_revision` delta published the plan's exact event
/// root and revision digest. Its current revision is the latest `event_revision` delta for that
/// object, which must agree with the ledger's current object and be the plan's revision exactly.
fn current_event_revision_batch(
    plan: &ReferenceAlertPlan,
    authority: &DurableReferenceLedger,
) -> Result<usize, ReferenceError> {
    let batches = authority.batches();
    let object_id = batches
        .iter()
        .rev()
        .flat_map(|batch| batch.deltas.iter())
        .find(|delta| {
            delta.family == "event_revision"
                && delta.payload_digest == plan.event_root
                && delta.witness_digest == Some(plan.event_revision_digest)
        })
        .map(|delta| delta.object_id.clone())
        .ok_or(ReferenceError::StaleEventAuthority)?;
    let current = authority
        .current()
        .objects
        .get(&object_id)
        .ok_or(ReferenceError::StaleEventAuthority)?;
    let (batch_index, latest) = batches
        .iter()
        .enumerate()
        .rev()
        .find_map(|(index, batch)| {
            batch
                .deltas
                .iter()
                .find(|delta| delta.object_id == object_id && delta.family == "event_revision")
                .map(|delta| (index, delta))
        })
        .ok_or(ReferenceError::StaleEventAuthority)?;
    if latest.new_generation != current.generation
        || latest.payload_digest != current.payload_digest
        || latest.payload_digest != plan.event_root
        || latest.witness_digest != Some(plan.event_revision_digest)
    {
        return Err(ReferenceError::StaleEventAuthority);
    }
    Ok(batch_index)
}

/// Every dispatch-time check, in order; the first refusal is returned.
///
/// Nothing the caller wrote into the journal is trusted for eligibility: the obligation's terminal
/// predicate is informational only. Eligibility is re-derived from the revision the authority
/// ledger currently holds, with the same [`verify_event_alert_eligibility`] preparation uses.
fn check_alert_dispatch_authority(
    plan: &ReferenceAlertPlan,
    authority: &DurableReferenceLedger,
    prepared_intent: &EffectIntent,
    obligation: Option<&Obligation>,
) -> Result<(), ReferenceError> {
    // 1. The plan is internally consistent (request digest binds root, revision, and channel).
    validate_reference_alert_plan(plan)?;
    // 2. The plan names an obligation the journal holds for this exact operation.
    let obligation = obligation.ok_or(fss_core::ContractError::NotFound)?;
    // 3. The plan is exactly the intent the journal recorded at prepare.
    if *prepared_intent != plan.intent || obligation.operation_id != plan.intent.operation_id {
        return Err(ReferenceError::StaleEventAuthority);
    }
    // 4. Fail closed: the durable authority must be readable and exactly this handle's history.
    // Bounded: one length probe and one 40-byte commit-trailer read, never a history re-read.
    authority
        .verify_durable_head()
        .map_err(authority_head_refusal)?;
    // 5. The planned revision is the ledger's current revision of the event, published under the
    // planned authority anchor.
    let batch_index = current_event_revision_batch(plan, authority)?;
    let batches = authority.batches();
    let publishing_anchor_matches = batches
        .get(batch_index)
        .is_some_and(|batch| batch.new_anchor == plan.authority_anchor);
    if !publishing_anchor_matches {
        return Err(ReferenceError::StaleEventAuthority);
    }
    // 6. Re-derive eligibility from that current authority revision and its whole lineage,
    // recomputed from the ledger (fss-2uftm): the same check preparation runs.
    let event = hydrate_event_revision(&plan.event_revision_encoding, plan.event_revision_digest)?;
    let prior = decode_prior_revisions(&plan.prior_revision_encodings)?;
    verify_alert_eligibility_in_lineage(
        authority,
        &event,
        committed_policy_action(&event),
        &prior,
    )?;
    // 7. The prepare-time head lies in this ledger's history, at or after the publishing batch: a
    // ledger with a different history is refused, an unrelated later batch is not (P6).
    let head_in_history = usize::try_from(plan.prepared_head_sequence)
        .ok()
        .and_then(|sequence| sequence.checked_sub(1))
        .is_some_and(|head_index| {
            head_index >= batch_index
                && batches
                    .get(head_index)
                    .is_some_and(|batch| batch.batch_digest == plan.prepared_head_digest)
        });
    if !head_in_history {
        return Err(ReferenceError::StaleEventAuthority);
    }
    // 8. The journal-recorded precondition binds the revision, anchor, committed decision, and
    // prepare-time head checked above.
    let precondition = alert_precondition_digest_parts(
        plan.event_revision_digest,
        &plan.authority_anchor,
        event.state,
        event.decision_path.fingerprint,
        plan.prepared_head_sequence,
        plan.prepared_head_digest,
    );
    if prepared_intent.precondition_digest != precondition {
        return Err(ReferenceError::StaleEventAuthority);
    }
    Ok(())
}

/// Revalidates event authority in the ledger before an alert plan is dispatched.
///
/// The one shared helper for both public dispatch paths ([`dispatch_reference_alert`] and
/// [`crate::DurableEffectJournal::dispatch_alert`]). Ensures:
/// 1. The operation is in [`EffectState::Prepared`] state.
/// 2. The plan passes canonical validation and is exactly the intent and obligation prepared.
/// 3. The durable authority ledger is readable and not moved under this handle (bounded check).
/// 4. The plan's revision is the event's current revision in the ledger, under the planned anchor.
/// 5. That current revision is alert-eligible, re-derived with [`verify_event_alert_eligibility`].
/// 6. The prepare-time ledger head is in the ledger's history and bound by the recorded intent.
///
/// Any refusal after step 1 transitions the operation and its obligation to
/// [`EffectState::Cancelled`] with a bound cancel proof before the error is returned.
pub(crate) fn revalidate_alert_event_authority<J: AlertEffectTransitioner>(
    plan: &ReferenceAlertPlan,
    authority: &DurableReferenceLedger,
    requested_at: TimestampNs,
    journal: &mut J,
) -> Result<(), ReferenceError> {
    let operation_id = &plan.intent.operation_id;
    let operation = journal
        .operation(operation_id)
        .ok_or(fss_core::ContractError::NotFound)?;
    if operation.state == EffectState::Committed || operation.state == EffectState::Indeterminate {
        return Err(fss_core::ContractError::ReconciliationRequired.into());
    }
    if operation.state != EffectState::Prepared {
        return Err(fss_core::ContractError::InvalidEffectTransition.into());
    }
    let updated_at = operation.updated_at;
    let prepared_intent = operation.intent.clone();

    let verdict = check_alert_dispatch_authority(
        plan,
        authority,
        &prepared_intent,
        journal.obligation(&plan.obligation_id),
    );
    let Err(refusal) = verdict else {
        return Ok(());
    };
    let cancel_at = if requested_at > updated_at {
        requested_at
    } else {
        TimestampNs(updated_at.0.saturating_add(1))
    };
    let cancel_proof = alert_cancel_proof(
        operation_id,
        &plan.authority_anchor,
        &authority.current().anchor,
    );
    journal.transition_cancelled(
        operation_id,
        cancel_at,
        cancel_proof,
        "stale_event_authority".to_owned(),
    )?;
    Err(refusal)
}

/// Deterministic idempotent alert provider oracle.
///
/// External callers cannot invoke provider dispatch directly; delivery requires revalidation
/// through [`dispatch_reference_alert`] or [`crate::DurableEffectJournal::dispatch_alert`].
///
/// ```compile_fail,E0624
/// use fss_core::effect::EffectIntent;
/// use fss_core::{ContentDigest, IdempotencyKey, OperationId};
/// use fss_reference::{ReferenceAlertProvider, ReferenceProviderBehavior};
///
/// fn direct_dispatch_forbidden() -> Result<(), Box<dyn std::error::Error>> {
///     let mut provider = ReferenceAlertProvider::with_provider_id("external:provider");
///     let intent = EffectIntent {
///         operation_id: OperationId::parse("op:alert:forbidden")?,
///         idempotency_key: IdempotencyKey::parse("idempotency:alert:forbidden")?,
///         effect_class: "alert.dispatch".to_owned(),
///         request_digest: ContentDigest::sha256(b"req"),
///         precondition_digest: ContentDigest::sha256(b"pre"),
///     };
///     // ReferenceAlertProvider::dispatch is pub(crate); calling it outside the crate fails to compile.
///     provider.dispatch(&intent, ReferenceProviderBehavior::Deliver);
///     Ok(())
/// }
/// ```
#[derive(Clone, Debug)]
pub struct ReferenceAlertProvider {
    provider_id: String,
    nonce_counter: u64,
    messages: BTreeMap<IdempotencyKey, ProviderMessage>,
    failures: BTreeMap<IdempotencyKey, ProviderFailureMessage>,
}

impl ReferenceAlertProvider {
    /// Creates an empty deterministic provider with explicit provider instance identity.
    #[must_use]
    pub fn new(provider_id: impl Into<String>) -> Self {
        Self::with_provider_id(provider_id)
    }

    /// Creates an empty deterministic provider with explicit provider instance identity.
    #[must_use]
    pub fn with_provider_id(provider_id: impl Into<String>) -> Self {
        Self {
            provider_id: provider_id.into(),
            nonce_counter: 0,
            messages: BTreeMap::new(),
            failures: BTreeMap::new(),
        }
    }

    /// Provider instance identity.
    #[must_use]
    pub fn provider_id(&self) -> &str {
        &self.provider_id
    }

    /// Number of unique provider delivery messages created.
    #[must_use]
    pub fn message_count(&self) -> usize {
        self.messages.len()
    }

    /// Number of unique provider failure receipts created.
    #[must_use]
    pub fn failure_count(&self) -> usize {
        self.failures.len()
    }

    /// Dispatches an intent to the provider oracle under the requested behavior.
    pub(crate) fn dispatch(
        &mut self,
        intent: &EffectIntent,
        behavior: ReferenceProviderBehavior,
    ) -> ProviderDispatch {
        if let Some(existing) = self.messages.get(&intent.idempotency_key) {
            return if existing.matches_intent(intent) {
                ProviderDispatch::Delivered(existing.receipt.receipt_digest())
            } else {
                ProviderDispatch::ConflictingIdempotency
            };
        }
        if let Some(existing) = self.failures.get(&intent.idempotency_key) {
            return if existing.matches_intent(intent) {
                ProviderDispatch::KnownFailure(existing.receipt.receipt_digest())
            } else {
                ProviderDispatch::ConflictingIdempotency
            };
        }

        if self.nonce_counter == u64::MAX {
            return ProviderDispatch::ConflictingIdempotency;
        }
        self.nonce_counter += 1;
        let mut nonce_enc = CanonicalEncoder::new();
        nonce_enc.text("fss.effect_proof.v1");
        nonce_enc.text(&self.provider_id);
        nonce_enc.u64(self.nonce_counter);
        let provider_nonce = ContentDigest::sha256(&nonce_enc.finish());

        match behavior {
            ReferenceProviderBehavior::FailBeforeDelivery => {
                let receipt = ProviderFailureReceipt {
                    provider_nonce,
                    message_digest: intent.canonical_digest("fss.effect_proof.v1"),
                    error_code: REFERENCE_ALERT_FAILURE_REASON.to_owned(),
                };
                let receipt_digest = receipt.receipt_digest();
                self.failures.insert(
                    intent.idempotency_key.clone(),
                    ProviderFailureMessage {
                        operation_id: intent.operation_id.clone(),
                        effect_class: intent.effect_class.clone(),
                        request_digest: intent.request_digest,
                        precondition_digest: intent.precondition_digest,
                        receipt,
                    },
                );
                ProviderDispatch::KnownFailure(receipt_digest)
            }
            ReferenceProviderBehavior::Deliver
            | ReferenceProviderBehavior::LoseAckAfterDelivery => {
                let receipt = ProviderObservationReceipt {
                    provider_nonce,
                    message_digest: intent.canonical_digest("fss.effect_proof.v1"),
                };
                let receipt_digest = receipt.receipt_digest();

                self.messages.insert(
                    intent.idempotency_key.clone(),
                    ProviderMessage {
                        operation_id: intent.operation_id.clone(),
                        effect_class: intent.effect_class.clone(),
                        request_digest: intent.request_digest,
                        precondition_digest: intent.precondition_digest,
                        receipt,
                    },
                );
                if behavior == ReferenceProviderBehavior::Deliver {
                    ProviderDispatch::Delivered(receipt_digest)
                } else {
                    ProviderDispatch::LostAck
                }
            }
        }
    }

    /// Looks up prior delivery observation receipt for an intent if present.
    pub fn lookup(
        &self,
        intent: &EffectIntent,
    ) -> Result<Option<ProviderObservationReceipt>, ReferenceError> {
        if let Some(message) = self.messages.get(&intent.idempotency_key) {
            return if message.matches_intent(intent) {
                Ok(Some(message.receipt.clone()))
            } else {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::IdempotencyConflict,
                ))
            };
        }
        if let Some(failure) = self.failures.get(&intent.idempotency_key) {
            return if failure.matches_intent(intent) {
                Ok(None)
            } else {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::IdempotencyConflict,
                ))
            };
        }
        Ok(None)
    }

    /// Looks up prior failure receipt for an intent if present.
    pub fn lookup_failure(
        &self,
        intent: &EffectIntent,
    ) -> Result<Option<ProviderFailureReceipt>, ReferenceError> {
        if let Some(failure) = self.failures.get(&intent.idempotency_key) {
            return if failure.matches_intent(intent) {
                Ok(Some(failure.receipt.clone()))
            } else {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::IdempotencyConflict,
                ))
            };
        }
        if let Some(message) = self.messages.get(&intent.idempotency_key) {
            return if message.matches_intent(intent) {
                Ok(None)
            } else {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::IdempotencyConflict,
                ))
            };
        }
        Ok(None)
    }

    /// Explicitly records an external provider delivery failure for an indeterminate intent.
    pub fn record_failure(
        &mut self,
        intent: &EffectIntent,
        error_code: impl Into<String>,
    ) -> Result<ProviderFailureReceipt, ReferenceError> {
        let error_str = error_code.into();
        if error_str.is_empty() {
            return Err(ReferenceError::Contract(
                fss_core::ContractError::EvidenceRequired,
            ));
        }
        if let Some(existing) = self.messages.get(&intent.idempotency_key) {
            return if existing.matches_intent(intent) {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::InvalidEffectTransition,
                ))
            } else {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::IdempotencyConflict,
                ))
            };
        }
        if let Some(existing) = self.failures.get(&intent.idempotency_key) {
            return if existing.matches_intent(intent) {
                if existing.receipt.error_code == error_str {
                    Ok(existing.receipt.clone())
                } else {
                    Err(ReferenceError::Contract(
                        fss_core::ContractError::IdempotencyConflict,
                    ))
                }
            } else {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::IdempotencyConflict,
                ))
            };
        }

        if self.nonce_counter == u64::MAX {
            return Err(ReferenceError::ArithmeticOverflow);
        }
        self.nonce_counter += 1;
        let mut nonce_enc = CanonicalEncoder::new();
        nonce_enc.text("fss.effect_proof.v1");
        nonce_enc.text(&self.provider_id);
        nonce_enc.u64(self.nonce_counter);
        let provider_nonce = ContentDigest::sha256(&nonce_enc.finish());

        let receipt = ProviderFailureReceipt {
            provider_nonce,
            message_digest: intent.canonical_digest("fss.effect_proof.v1"),
            error_code: error_str,
        };
        self.failures.insert(
            intent.idempotency_key.clone(),
            ProviderFailureMessage {
                operation_id: intent.operation_id.clone(),
                effect_class: intent.effect_class.clone(),
                request_digest: intent.request_digest,
                precondition_digest: intent.precondition_digest,
                receipt: receipt.clone(),
            },
        );
        Ok(receipt)
    }
}

/// Parameters for preparing an authoritative reference alert.
#[derive(Debug)]
pub struct PrepareAlertParams<'a> {
    /// Policy decision triggering this alert.
    pub decision: &'a ReferencePolicyDecision,
    /// Authoritative event receipt witness.
    pub event_receipt: &'a ReferenceEventReceipt,
    /// Current durable authority ledger.
    pub authority: &'a DurableReferenceLedger,
    /// Operation identity.
    pub operation_id: OperationId,
    /// Effect idempotency key.
    pub idempotency_key: IdempotencyKey,
    /// Obligation tracking identity.
    pub obligation_id: ObligationId,
    /// Alert delivery channel.
    pub channel: String,
    /// Preparation timestamp.
    pub now: TimestampNs,
}

/// Prepares an alert effect only from a currently authoritative independently corroborated event.
///
/// The supplied event receipt must match the current durable authority anchor and the latest
/// publication batch must contain the exact event root/revision witness; publication lineage
/// records, which change no authority object, are skipped for both. This prevents a forged or
/// stale typed receipt from becoming effect authority.
pub fn prepare_reference_alert(
    params: PrepareAlertParams<'_>,
    journal: &mut EffectJournal,
) -> Result<ReferenceAlertPlan, ReferenceError> {
    verify_event_alert_eligibility(
        params.decision.event.state,
        params.decision.action,
        &params.decision.event.evidence,
    )?;
    // Defence in depth: a sensor-integrity risk never becomes effect authority. The eligibility
    // check above refuses a tamper edge on this revision; the receipt's lineage tamper status
    // refuses a tamper an earlier revision reported and no evidenced restoration retired. The
    // receipt status itself is checked against the published witness below.
    if params.event_receipt.lineage_tamper_status.has_open_tamper() {
        return Err(fss_core::ContractError::SensorIntegrityRisk.into());
    }
    if params.event_receipt.event_revision_digest != params.decision.event.revision_digest() {
        return Err(ReferenceError::InvalidSpec("event_receipt_mismatch"));
    }
    // Publication lineage records change no authority object other than a lineage object, so a
    // receipt stays current across them and the latest authority batch is the latest non-lineage
    // one (fss-mnlz1).
    if !crate::situation_sections::anchor_is_current_modulo_lineage(
        params.authority,
        &params.event_receipt.authority_anchor,
    ) {
        return Err(ReferenceError::InvalidSpec("event_authority_stale"));
    }
    let latest_batch = params
        .authority
        .batches()
        .iter()
        .rev()
        .find(|batch| !crate::situation_sections::is_lineage_batch(batch))
        .ok_or(ReferenceError::InvalidSpec("event_authority_stale"))?;
    let latest_contains_event = latest_batch.deltas.iter().any(|delta| {
        delta.family == "event_revision"
            && delta.payload_digest == params.event_receipt.event_root
            && delta.witness_digest == Some(params.event_receipt.event_revision_digest)
    });
    if !latest_contains_event {
        return Err(ReferenceError::InvalidSpec("event_receipt_mismatch"));
    }
    let latest_contains_tamper = latest_batch.deltas.iter().any(|delta| {
        delta.family == "sensor_tamper_status"
            && delta.payload_digest == params.event_receipt.event_root
            && delta.witness_digest
                == Some(
                    params
                        .event_receipt
                        .lineage_tamper_status
                        .canonical_digest(),
                )
    });
    if !latest_contains_tamper {
        return Err(ReferenceError::InvalidSpec(
            "forged_event_receipt_tamper_status",
        ));
    }
    // The receipt and the witness are cross-checks only: eligibility is re-derived from the event's
    // lineage as the authority ledger holds it, with the check dispatch runs (fss-2uftm).
    let lineage_status = verify_alert_eligibility_in_lineage(
        params.authority,
        &params.decision.event,
        params.decision.action,
        &decode_prior_revisions(&params.event_receipt.prior_revision_encodings)?,
    )?;
    if lineage_status != params.event_receipt.lineage_tamper_status {
        return Err(ReferenceError::InvalidSpec(
            "forged_event_receipt_tamper_status",
        ));
    }

    let channel = params.channel;
    if channel.is_empty() || channel.len() > MAX_ALERT_CHANNEL_BYTES {
        return Err(ReferenceError::InvalidSpec("alert_channel"));
    }

    // The prepare-time head is read from the authority ledger itself and bound into the
    // precondition digest the journal records with the operation; no caller string carries it.
    let batches = params.authority.batches();
    let prepared_head_digest = batches
        .last()
        .map(|batch| batch.batch_digest)
        .ok_or(ReferenceError::InvalidSpec("event_receipt_mismatch"))?;
    let prepared_head_sequence =
        u64::try_from(batches.len()).map_err(|_| ReferenceError::ArithmeticOverflow)?;

    let request_digest = alert_request_digest(params.event_receipt, &channel);
    let precondition_digest = alert_precondition_digest_parts(
        params.event_receipt.event_revision_digest,
        &params.event_receipt.authority_anchor,
        params.decision.event.state,
        params.decision.event.decision_path.fingerprint,
        prepared_head_sequence,
        prepared_head_digest,
    );
    let intent = EffectIntent {
        operation_id: params.operation_id,
        idempotency_key: params.idempotency_key,
        effect_class: "alert.dispatch".to_owned(),
        request_digest,
        precondition_digest,
    };
    let receipt = journal.prepare(
        intent.clone(),
        params.obligation_id,
        REFERENCE_ALERT_TERMINAL_PREDICATE,
        params.now,
    )?;
    let prepared_intent = receipt.intent.clone();
    let actual_obligation = journal
        .obligations()
        .find(|obligation| obligation.operation_id == prepared_intent.operation_id)
        .ok_or(fss_core::ContractError::NotFound)?
        .obligation_id
        .clone();
    Ok(ReferenceAlertPlan {
        intent: prepared_intent,
        obligation_id: actual_obligation,
        event_root: params.event_receipt.event_root,
        event_revision_digest: params.event_receipt.event_revision_digest,
        authority_anchor: params.event_receipt.authority_anchor.clone(),
        channel,
        event_revision_encoding: event_revision_encoding(&params.decision.event),
        prior_revision_encodings: params.event_receipt.prior_revision_encodings.clone(),
        prepared_head_sequence,
        prepared_head_digest,
    })
}

/// Shared execution helper for alert dispatch through the deterministic provider oracle.
///
/// Ensures event authority and plan integrity are revalidated atomically before committing
/// and invoking provider dispatch.
pub(crate) fn execute_alert_dispatch<J: AlertEffectTransitioner>(
    plan: &ReferenceAlertPlan,
    authority: &DurableReferenceLedger,
    behavior: ReferenceProviderBehavior,
    commit_at: TimestampNs,
    outcome_at: TimestampNs,
    journal: &mut J,
    provider: &mut ReferenceAlertProvider,
) -> Result<OperationReceipt, ReferenceError> {
    revalidate_alert_event_authority(plan, authority, commit_at, journal)?;

    let operation_id = &plan.intent.operation_id;
    journal.transition_committed(operation_id, commit_at)?;

    match provider.dispatch(&plan.intent, behavior) {
        ProviderDispatch::Delivered(_proof) => {
            let receipt = journal.transition_adapter_accepted(operation_id, outcome_at)?;
            Ok(receipt)
        }
        ProviderDispatch::LostAck => {
            let receipt =
                journal.mark_indeterminate(operation_id, outcome_at, "provider_ack_lost")?;
            Ok(receipt)
        }
        ProviderDispatch::KnownFailure(proof) => {
            let receipt = journal.transition_failed(
                operation_id,
                outcome_at,
                Some(proof),
                Some(REFERENCE_ALERT_FAILURE_REASON.to_owned()),
            )?;
            Ok(receipt)
        }
        ProviderDispatch::ConflictingIdempotency => Err(ReferenceError::Contract(
            fss_core::ContractError::IdempotencyConflict,
        )),
    }
}

/// Commits and dispatches one exact prepared alert plan through the deterministic provider oracle.
///
/// A second call after `Indeterminate` fails in the effect journal before the provider is touched.
/// This models the required no-blind-retry rule for ambiguous external effects.
///
/// # Plane boundary (ADR-0001)
///
/// Invariant 4: dispatch accepts only a prepared [`ReferenceAlertPlan`]; a cognition value
/// passed in its place is rejected by the type checker.
///
/// ```compile_fail,E0308
/// use fss_core::belief::BeliefInterval;
/// use fss_core::{EffectJournal, TimestampNs};
/// use fss_ledger::DurableReferenceLedger;
/// use fss_reference::{ReferenceAlertPlan, ReferenceAlertProvider, ReferenceProviderBehavior, dispatch_reference_alert};
///
/// fn legal_dispatch(
///     plan: &ReferenceAlertPlan,
///     authority: &DurableReferenceLedger,
///     journal: &mut EffectJournal,
///     provider: &mut ReferenceAlertProvider,
/// ) {
///     let behavior = ReferenceProviderBehavior::Deliver;
///     let _ = dispatch_reference_alert(plan, authority, behavior, TimestampNs(1), TimestampNs(2), journal, provider);
/// }
///
/// fn forbidden_dispatch(
///     belief: &BeliefInterval,
///     authority: &DurableReferenceLedger,
///     journal: &mut EffectJournal,
///     provider: &mut ReferenceAlertProvider,
/// ) {
///     // adr-0001/inv-4-reference: a belief is not a prepared alert plan.
///     let behavior = ReferenceProviderBehavior::Deliver;
///     let _ = dispatch_reference_alert(belief, authority, behavior, TimestampNs(1), TimestampNs(2), journal, provider);
/// }
/// ```
pub fn dispatch_reference_alert(
    plan: &ReferenceAlertPlan,
    authority: &DurableReferenceLedger,
    behavior: ReferenceProviderBehavior,
    commit_at: TimestampNs,
    outcome_at: TimestampNs,
    journal: &mut EffectJournal,
    provider: &mut ReferenceAlertProvider,
) -> Result<OperationReceipt, ReferenceError> {
    execute_alert_dispatch(
        plan, authority, behavior, commit_at, outcome_at, journal, provider,
    )
}

/// Records an independent observation of an adapter-accepted alert.
pub fn observe_reference_alert(
    plan: &ReferenceAlertPlan,
    observation_proof: ContentDigest,
    observed_at: TimestampNs,
    journal: &mut EffectJournal,
    provider: &ReferenceAlertProvider,
) -> Result<OperationReceipt, ReferenceError> {
    validate_reference_alert_plan(plan)?;
    let Some(provider_receipt) = provider.lookup(&plan.intent)? else {
        return Err(ReferenceError::InvalidSpec("provider_proof_missing"));
    };
    if observation_proof != provider_receipt.receipt_digest() {
        return Err(ReferenceError::Contract(
            fss_core::ContractError::InvalidDigest,
        ));
    }
    let receipt = journal.transition(
        &plan.intent.operation_id,
        EffectState::Observed,
        observed_at,
        Some(observation_proof),
        None,
    )?;
    Ok(receipt.clone())
}

/// Verifies an observed alert using terminal proof witness.
pub fn verify_reference_alert(
    plan: &ReferenceAlertPlan,
    verified_at: TimestampNs,
    journal: &mut EffectJournal,
    provider: &ReferenceAlertProvider,
) -> Result<OperationReceipt, ReferenceError> {
    validate_reference_alert_plan(plan)?;
    let Some(provider_receipt) = provider.lookup(&plan.intent)? else {
        return Err(ReferenceError::InvalidSpec("provider_proof_missing"));
    };
    let receipt = journal.reconcile_verified(
        &plan.intent.operation_id,
        provider_receipt.receipt_digest(),
        verified_at,
    )?;
    Ok(receipt.clone())
}

/// Reconciles an indeterminate alert to terminal failure using an independent failure proof.
pub fn reconcile_failed_reference_alert(
    plan: &ReferenceAlertPlan,
    proof_digest: ContentDigest,
    reason: impl Into<String>,
    now: TimestampNs,
    journal: &mut EffectJournal,
    provider: &ReferenceAlertProvider,
) -> Result<OperationReceipt, ReferenceError> {
    validate_reference_alert_plan(plan)?;
    if provider.lookup(&plan.intent)?.is_some() {
        return Err(ReferenceError::Contract(
            fss_core::ContractError::InvalidEffectTransition,
        ));
    }
    let Some(failure_receipt) = provider.lookup_failure(&plan.intent)? else {
        return Err(ReferenceError::InvalidSpec(
            "provider_failure_proof_missing",
        ));
    };
    if proof_digest != failure_receipt.receipt_digest() {
        return Err(ReferenceError::Contract(
            fss_core::ContractError::InvalidDigest,
        ));
    }
    let reason_str = reason.into();
    if reason_str != failure_receipt.error_code {
        return Err(ReferenceError::InvalidSpec(
            "provider_failure_reason_mismatch",
        ));
    }
    let receipt =
        journal.reconcile_failed(&plan.intent.operation_id, proof_digest, now, reason_str)?;
    Ok(receipt.clone())
}

/// Reconciles an indeterminate alert from independent provider state without resending it.
///
/// `Ok(None)` means no positive terminal proof is currently available; the operation intentionally
/// remains indeterminate rather than being guessed failed.
pub fn reconcile_reference_alert(
    plan: &ReferenceAlertPlan,
    now: TimestampNs,
    journal: &mut EffectJournal,
    provider: &ReferenceAlertProvider,
) -> Result<Option<OperationReceipt>, ReferenceError> {
    validate_reference_alert_plan(plan)?;
    let Some(provider_receipt) = provider.lookup(&plan.intent)? else {
        return Ok(None);
    };
    let op = &plan.intent.operation_id;
    let current_state = journal
        .operation(op)
        .map(|r| r.state)
        .ok_or(fss_core::ContractError::NotFound)?;

    match current_state {
        EffectState::Verified => {
            let receipt = journal.reconcile_verified(op, provider_receipt.receipt_digest(), now)?;
            Ok(Some(receipt.clone()))
        }
        EffectState::Observed => {
            let receipt = journal.reconcile_verified(op, provider_receipt.receipt_digest(), now)?;
            Ok(Some(receipt.clone()))
        }
        EffectState::Indeterminate => {
            let obs_time = now;
            let ver_time = TimestampNs(now.0.saturating_add(1));
            journal.transition(
                op,
                EffectState::Observed,
                obs_time,
                Some(provider_receipt.receipt_digest()),
                None,
            )?;
            let receipt =
                journal.reconcile_verified(op, provider_receipt.receipt_digest(), ver_time)?;
            Ok(Some(receipt.clone()))
        }
        _ => Err(ReferenceError::Contract(
            fss_core::ContractError::InvalidEffectTransition,
        )),
    }
}

pub(crate) fn alert_request_digest(
    event_receipt: &ReferenceEventReceipt,
    channel: &str,
) -> ContentDigest {
    alert_request_digest_parts(
        event_receipt.event_root,
        event_receipt.event_revision_digest,
        channel,
    )
}

fn alert_request_digest_parts(
    event_root: ContentDigest,
    event_revision_digest: ContentDigest,
    channel: &str,
) -> ContentDigest {
    let mut encoder = CanonicalEncoder::new();
    encoder.text("fss.reference_alert_request.v1");
    encoder.digest(event_root);
    encoder.digest(event_revision_digest);
    encoder.text(channel);
    ContentDigest::sha256(&encoder.finish())
}

pub(crate) fn validate_reference_alert_plan(
    plan: &ReferenceAlertPlan,
) -> Result<(), ReferenceError> {
    if plan.channel.is_empty()
        || plan.channel.len() > MAX_ALERT_CHANNEL_BYTES
        || plan.intent.effect_class != "alert.dispatch"
        || plan.intent.request_digest
            != alert_request_digest_parts(
                plan.event_root,
                plan.event_revision_digest,
                &plan.channel,
            )
    {
        return Err(ReferenceError::InvalidSpec("alert_plan_integrity"));
    }
    Ok(())
}

/// Precondition digest recorded with the prepared alert intent.
///
/// Binds the exact event revision, its publishing authority anchor, the committed event state and
/// decision path, and the prepare-time authority ledger head (sequence and batch digest).
pub(crate) fn alert_precondition_digest_parts(
    event_revision_digest: ContentDigest,
    authority_anchor: &LedgerAnchor,
    state: EventState,
    decision_fingerprint: ContentDigest,
    prepared_head_sequence: u64,
    prepared_head_digest: ContentDigest,
) -> ContentDigest {
    let mut encoder = CanonicalEncoder::new();
    encoder.text("fss.reference_alert_precondition.v2");
    encoder.digest(event_revision_digest);
    authority_anchor.encode_canonical(&mut encoder);
    encoder.text(state.as_str());
    encoder.digest(decision_fingerprint);
    encoder.u64(prepared_head_sequence);
    encoder.digest(prepared_head_digest);
    ContentDigest::sha256(&encoder.finish())
}

pub(crate) fn reference_alert_terminal_proof_bytes(
    plan: &ReferenceAlertPlan,
    receipt: &OperationReceipt,
    provider: &ReferenceAlertProvider,
) -> Result<Option<Vec<u8>>, ReferenceError> {
    if receipt.intent != plan.intent {
        return Err(ReferenceError::InvalidSpec("alert_outcome_operation"));
    }
    match receipt.state {
        EffectState::Verified => {
            let provider_receipt = provider
                .lookup(&receipt.intent)?
                .ok_or(ReferenceError::InvalidSpec("provider_proof_missing"))?;
            let bytes = provider_receipt.canonical_bytes();
            if receipt.result_digest != Some(ContentDigest::sha256(&bytes)) {
                return Err(ReferenceError::InvalidSpec("alert_outcome_proof"));
            }
            Ok(Some(bytes))
        }
        EffectState::Failed => {
            let Some(reason) = receipt.error_code.as_deref().filter(|s| !s.is_empty()) else {
                return Err(ReferenceError::InvalidSpec("alert_outcome_proof"));
            };
            let failure_receipt =
                provider
                    .lookup_failure(&receipt.intent)?
                    .ok_or(ReferenceError::InvalidSpec(
                        "provider_failure_proof_missing",
                    ))?;
            if failure_receipt.error_code != reason {
                return Err(ReferenceError::InvalidSpec("alert_outcome_proof"));
            }
            let bytes = failure_receipt.canonical_bytes();
            if receipt.result_digest != Some(failure_receipt.receipt_digest()) {
                return Err(ReferenceError::InvalidSpec("alert_outcome_proof"));
            }
            Ok(Some(bytes))
        }
        EffectState::Indeterminate => {
            let Some(_reason) = receipt.error_code.as_deref().filter(|s| !s.is_empty()) else {
                return Err(ReferenceError::InvalidSpec("alert_outcome_proof"));
            };
            if receipt.result_digest.is_some() {
                return Err(ReferenceError::InvalidSpec("alert_outcome_proof"));
            }
            Ok(None)
        }
        _ => Err(ReferenceError::InvalidSpec("alert_outcome_not_publishable")),
    }
}
