//! Deterministic alert-effect oracle with lost-ACK reconciliation.

use std::collections::BTreeMap;

use fss_core::{
    CanonicalEncode, CanonicalEncoder, ContentDigest, EffectIntent, EffectJournal, EffectState,
    IdempotencyKey, ObligationId, OperationId, OperationReceipt, TimestampNs,
};
use fss_ledger::DurableReferenceLedger;

use crate::{
    ReferenceError, ReferenceEventReceipt, ReferencePolicyAction, ReferencePolicyDecision,
};

const MAX_ALERT_CHANNEL_BYTES: usize = 256;

/// Immutable prepared alert plan. Preparation grants no external dispatch by itself.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReferenceAlertPlan {
    /// Exact effect intent registered in the effect journal.
    pub intent: EffectIntent,
    /// Existing terminal-proof obligation owned by the operation.
    pub obligation_id: ObligationId,
    /// Exact canonical event graph being reported.
    pub event_root: ContentDigest,
    /// Event revision fingerprint.
    pub event_revision_digest: ContentDigest,
    /// Stable bounded alert channel identity.
    pub channel: String,
}

/// Deterministic provider fault choice for one dispatch attempt.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReferenceProviderBehavior {
    /// Provider stores the message and returns trustworthy delivery proof.
    Deliver,
    /// Provider stores the message but the caller loses the acknowledgement.
    LoseAckAfterDelivery,
    /// Provider proves the request failed before any message was created.
    FailBeforeDelivery,
}

/// Result of dispatching an intent through the reference alert provider.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProviderDispatch {
    /// Provider successfully delivered the message and generated delivery proof.
    Delivered(ContentDigest),
    /// Acknowledgement was lost after delivery.
    LostAck,
    /// Known failure before delivery with failure proof.
    KnownFailure(ContentDigest),
    /// Conflicting intent attempted under an existing idempotency key.
    ConflictingIdempotency,
}

/// Provider-generated observation receipt for a delivered message.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProviderObservationReceipt {
    /// Nonce generated by provider; cannot be derived from intent alone.
    pub provider_nonce: ContentDigest,
    /// Message digest of the dispatched intent.
    pub message_digest: ContentDigest,
}

impl ProviderObservationReceipt {
    /// Canonical encoded bytes of the observation receipt.
    #[must_use]
    pub fn canonical_bytes(&self) -> Vec<u8> {
        let mut encoder = CanonicalEncoder::new();
        encoder.text("fss.effect_proof.v1");
        encoder.digest(self.provider_nonce);
        encoder.digest(self.message_digest);
        encoder.finish()
    }

    /// SHA-256 digest of the canonical receipt bytes.
    #[must_use]
    pub fn receipt_digest(&self) -> ContentDigest {
        ContentDigest::sha256(&self.canonical_bytes())
    }
}

/// Typed failure proof issued by the reference provider oracle.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProviderFailureReceipt {
    /// Independent provider-generated dispatch nonce.
    pub provider_nonce: ContentDigest,
    /// Canonical digest of the dispatched intent payload.
    pub message_digest: ContentDigest,
    /// Error code or failure reason issued by the provider.
    pub error_code: String,
}

impl ProviderFailureReceipt {
    /// Canonical encoded bytes of the failure receipt.
    #[must_use]
    pub fn canonical_bytes(&self) -> Vec<u8> {
        let mut encoder = CanonicalEncoder::new();
        encoder.text("fss.effect_proof.v1");
        encoder.digest(self.provider_nonce);
        encoder.digest(self.message_digest);
        encoder.text(&self.error_code);
        encoder.finish()
    }

    /// SHA-256 digest of the canonical receipt bytes.
    #[must_use]
    pub fn receipt_digest(&self) -> ContentDigest {
        ContentDigest::sha256(&self.canonical_bytes())
    }
}

/// Bounded stable terminal predicate for reference alert obligations.
pub const REFERENCE_ALERT_TERMINAL_PREDICATE: &str =
    "provider delivery is independently reconciled";

pub const REFERENCE_ALERT_FAILURE_REASON: &str = "failed_before_delivery";

#[derive(Clone, Debug, Eq, PartialEq)]
struct ProviderMessage {
    operation_id: OperationId,
    effect_class: String,
    request_digest: ContentDigest,
    precondition_digest: ContentDigest,
    receipt: ProviderObservationReceipt,
}

impl ProviderMessage {
    fn matches_intent(&self, intent: &EffectIntent) -> bool {
        self.operation_id == intent.operation_id
            && self.effect_class == intent.effect_class
            && self.request_digest == intent.request_digest
            && self.precondition_digest == intent.precondition_digest
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct ProviderFailureMessage {
    operation_id: OperationId,
    effect_class: String,
    request_digest: ContentDigest,
    precondition_digest: ContentDigest,
    receipt: ProviderFailureReceipt,
}

impl ProviderFailureMessage {
    fn matches_intent(&self, intent: &EffectIntent) -> bool {
        self.operation_id == intent.operation_id
            && self.effect_class == intent.effect_class
            && self.request_digest == intent.request_digest
            && self.precondition_digest == intent.precondition_digest
    }
}

/// Deterministic idempotent alert provider oracle.
#[derive(Clone, Debug)]
pub struct ReferenceAlertProvider {
    provider_id: String,
    nonce_counter: u64,
    messages: BTreeMap<IdempotencyKey, ProviderMessage>,
    failures: BTreeMap<IdempotencyKey, ProviderFailureMessage>,
}

impl ReferenceAlertProvider {
    /// Creates an empty deterministic provider with explicit provider instance identity.
    #[must_use]
    pub fn new(provider_id: impl Into<String>) -> Self {
        Self::with_provider_id(provider_id)
    }

    /// Creates an empty deterministic provider with explicit provider instance identity.
    #[must_use]
    pub fn with_provider_id(provider_id: impl Into<String>) -> Self {
        Self {
            provider_id: provider_id.into(),
            nonce_counter: 0,
            messages: BTreeMap::new(),
            failures: BTreeMap::new(),
        }
    }

    /// Provider instance identity.
    #[must_use]
    pub fn provider_id(&self) -> &str {
        &self.provider_id
    }

    /// Number of unique provider delivery messages created.
    #[must_use]
    pub fn message_count(&self) -> usize {
        self.messages.len()
    }

    /// Number of unique provider failure receipts created.
    #[must_use]
    pub fn failure_count(&self) -> usize {
        self.failures.len()
    }

    /// Dispatches an intent to the provider oracle under the requested behavior.
    pub fn dispatch(
        &mut self,
        intent: &EffectIntent,
        behavior: ReferenceProviderBehavior,
    ) -> ProviderDispatch {
        if let Some(existing) = self.messages.get(&intent.idempotency_key) {
            return if existing.matches_intent(intent) {
                ProviderDispatch::Delivered(existing.receipt.receipt_digest())
            } else {
                ProviderDispatch::ConflictingIdempotency
            };
        }
        if let Some(existing) = self.failures.get(&intent.idempotency_key) {
            return if existing.matches_intent(intent) {
                ProviderDispatch::KnownFailure(existing.receipt.receipt_digest())
            } else {
                ProviderDispatch::ConflictingIdempotency
            };
        }

        if self.nonce_counter == u64::MAX {
            return ProviderDispatch::ConflictingIdempotency;
        }
        self.nonce_counter += 1;
        let mut nonce_enc = CanonicalEncoder::new();
        nonce_enc.text("fss.effect_proof.v1");
        nonce_enc.text(&self.provider_id);
        nonce_enc.u64(self.nonce_counter);
        let provider_nonce = ContentDigest::sha256(&nonce_enc.finish());

        match behavior {
            ReferenceProviderBehavior::FailBeforeDelivery => {
                let receipt = ProviderFailureReceipt {
                    provider_nonce,
                    message_digest: intent.canonical_digest("fss.effect_proof.v1"),
                    error_code: REFERENCE_ALERT_FAILURE_REASON.to_owned(),
                };
                let receipt_digest = receipt.receipt_digest();
                self.failures.insert(
                    intent.idempotency_key.clone(),
                    ProviderFailureMessage {
                        operation_id: intent.operation_id.clone(),
                        effect_class: intent.effect_class.clone(),
                        request_digest: intent.request_digest,
                        precondition_digest: intent.precondition_digest,
                        receipt,
                    },
                );
                ProviderDispatch::KnownFailure(receipt_digest)
            }
            ReferenceProviderBehavior::Deliver
            | ReferenceProviderBehavior::LoseAckAfterDelivery => {
                let receipt = ProviderObservationReceipt {
                    provider_nonce,
                    message_digest: intent.canonical_digest("fss.effect_proof.v1"),
                };
                let receipt_digest = receipt.receipt_digest();

                self.messages.insert(
                    intent.idempotency_key.clone(),
                    ProviderMessage {
                        operation_id: intent.operation_id.clone(),
                        effect_class: intent.effect_class.clone(),
                        request_digest: intent.request_digest,
                        precondition_digest: intent.precondition_digest,
                        receipt,
                    },
                );
                if behavior == ReferenceProviderBehavior::Deliver {
                    ProviderDispatch::Delivered(receipt_digest)
                } else {
                    ProviderDispatch::LostAck
                }
            }
        }
    }

    /// Looks up prior delivery observation receipt for an intent if present.
    pub fn lookup(
        &self,
        intent: &EffectIntent,
    ) -> Result<Option<ProviderObservationReceipt>, ReferenceError> {
        if let Some(message) = self.messages.get(&intent.idempotency_key) {
            return if message.matches_intent(intent) {
                Ok(Some(message.receipt.clone()))
            } else {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::IdempotencyConflict,
                ))
            };
        }
        if let Some(failure) = self.failures.get(&intent.idempotency_key) {
            return if failure.matches_intent(intent) {
                Ok(None)
            } else {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::IdempotencyConflict,
                ))
            };
        }
        Ok(None)
    }

    /// Looks up prior failure receipt for an intent if present.
    pub fn lookup_failure(
        &self,
        intent: &EffectIntent,
    ) -> Result<Option<ProviderFailureReceipt>, ReferenceError> {
        if let Some(failure) = self.failures.get(&intent.idempotency_key) {
            return if failure.matches_intent(intent) {
                Ok(Some(failure.receipt.clone()))
            } else {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::IdempotencyConflict,
                ))
            };
        }
        if let Some(message) = self.messages.get(&intent.idempotency_key) {
            return if message.matches_intent(intent) {
                Ok(None)
            } else {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::IdempotencyConflict,
                ))
            };
        }
        Ok(None)
    }

    /// Explicitly records an external provider delivery failure for an indeterminate intent.
    pub fn record_failure(
        &mut self,
        intent: &EffectIntent,
        error_code: impl Into<String>,
    ) -> Result<ProviderFailureReceipt, ReferenceError> {
        let error_str = error_code.into();
        if error_str.is_empty() {
            return Err(ReferenceError::Contract(
                fss_core::ContractError::EvidenceRequired,
            ));
        }
        if let Some(existing) = self.messages.get(&intent.idempotency_key) {
            return if existing.matches_intent(intent) {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::InvalidEffectTransition,
                ))
            } else {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::IdempotencyConflict,
                ))
            };
        }
        if let Some(existing) = self.failures.get(&intent.idempotency_key) {
            return if existing.matches_intent(intent) {
                if existing.receipt.error_code == error_str {
                    Ok(existing.receipt.clone())
                } else {
                    Err(ReferenceError::Contract(
                        fss_core::ContractError::IdempotencyConflict,
                    ))
                }
            } else {
                Err(ReferenceError::Contract(
                    fss_core::ContractError::IdempotencyConflict,
                ))
            };
        }

        if self.nonce_counter == u64::MAX {
            return Err(ReferenceError::ArithmeticOverflow);
        }
        self.nonce_counter += 1;
        let mut nonce_enc = CanonicalEncoder::new();
        nonce_enc.text("fss.effect_proof.v1");
        nonce_enc.text(&self.provider_id);
        nonce_enc.u64(self.nonce_counter);
        let provider_nonce = ContentDigest::sha256(&nonce_enc.finish());

        let receipt = ProviderFailureReceipt {
            provider_nonce,
            message_digest: intent.canonical_digest("fss.effect_proof.v1"),
            error_code: error_str,
        };
        self.failures.insert(
            intent.idempotency_key.clone(),
            ProviderFailureMessage {
                operation_id: intent.operation_id.clone(),
                effect_class: intent.effect_class.clone(),
                request_digest: intent.request_digest,
                precondition_digest: intent.precondition_digest,
                receipt: receipt.clone(),
            },
        );
        Ok(receipt)
    }
}

/// Parameters for preparing an authoritative reference alert.
#[derive(Debug)]
pub struct PrepareAlertParams<'a> {
    /// Policy decision triggering this alert.
    pub decision: &'a ReferencePolicyDecision,
    /// Authoritative event receipt witness.
    pub event_receipt: &'a ReferenceEventReceipt,
    /// Current durable authority ledger.
    pub authority: &'a DurableReferenceLedger,
    /// Operation identity.
    pub operation_id: OperationId,
    /// Effect idempotency key.
    pub idempotency_key: IdempotencyKey,
    /// Obligation tracking identity.
    pub obligation_id: ObligationId,
    /// Alert delivery channel.
    pub channel: String,
    /// Preparation timestamp.
    pub now: TimestampNs,
}

/// Prepares an alert effect only from a currently authoritative independently corroborated event.
///
/// The supplied event receipt must match the current durable authority anchor and the latest
/// publication batch must contain the exact event root/revision witness. This prevents a forged or
/// stale typed receipt from becoming effect authority.
pub fn prepare_reference_alert(
    params: PrepareAlertParams<'_>,
    journal: &mut EffectJournal,
) -> Result<ReferenceAlertPlan, ReferenceError> {
    if params.decision.action != ReferencePolicyAction::PrepareAlert
        || params.decision.event.state != fss_core::EventState::Corroborated
    {
        return Err(ReferenceError::InvalidSpec("alert_not_eligible"));
    }
    if params.event_receipt.event_revision_digest != params.decision.event.revision_digest() {
        return Err(ReferenceError::InvalidSpec("event_receipt_mismatch"));
    }
    if params.authority.current().anchor != params.event_receipt.authority_anchor {
        return Err(ReferenceError::InvalidSpec("event_authority_stale"));
    }
    let latest_contains_event = params.authority.batches().last().is_some_and(|batch| {
        batch.deltas.iter().any(|delta| {
            delta.family == "event_revision"
                && delta.payload_digest == params.event_receipt.event_root
                && delta.witness_digest == Some(params.event_receipt.event_revision_digest)
        })
    });
    if !latest_contains_event {
        return Err(ReferenceError::InvalidSpec("event_receipt_mismatch"));
    }

    let channel = params.channel;
    if channel.is_empty() || channel.len() > MAX_ALERT_CHANNEL_BYTES {
        return Err(ReferenceError::InvalidSpec("alert_channel"));
    }

    let request_digest = alert_request_digest(params.event_receipt, &channel);
    let precondition_digest = alert_precondition_digest(params.decision, params.event_receipt);
    let intent = EffectIntent {
        operation_id: params.operation_id,
        idempotency_key: params.idempotency_key,
        effect_class: "alert.dispatch".to_owned(),
        request_digest,
        precondition_digest,
    };
    let receipt = journal.prepare(
        intent.clone(),
        params.obligation_id,
        REFERENCE_ALERT_TERMINAL_PREDICATE,
        params.now,
    )?;
    let prepared_intent = receipt.intent.clone();
    let actual_obligation = journal
        .obligations()
        .find(|obligation| obligation.operation_id == prepared_intent.operation_id)
        .ok_or(fss_core::ContractError::NotFound)?
        .obligation_id
        .clone();
    Ok(ReferenceAlertPlan {
        intent: prepared_intent,
        obligation_id: actual_obligation,
        event_root: params.event_receipt.event_root,
        event_revision_digest: params.event_receipt.event_revision_digest,
        channel,
    })
}

/// Commits and dispatches one exact prepared alert plan through the deterministic provider oracle.
///
/// A second call after `Indeterminate` fails in the effect journal before the provider is touched.
/// This models the required no-blind-retry rule for ambiguous external effects.
pub fn dispatch_reference_alert(
    plan: &ReferenceAlertPlan,
    behavior: ReferenceProviderBehavior,
    commit_at: TimestampNs,
    outcome_at: TimestampNs,
    journal: &mut EffectJournal,
    provider: &mut ReferenceAlertProvider,
) -> Result<OperationReceipt, ReferenceError> {
    validate_reference_alert_plan(plan)?;
    let operation_id = &plan.intent.operation_id;
    let _ = journal.transition(operation_id, EffectState::Committed, commit_at, None, None)?;

    match provider.dispatch(&plan.intent, behavior) {
        ProviderDispatch::Delivered(_proof) => {
            let receipt = journal.transition(
                operation_id,
                EffectState::AdapterAccepted,
                outcome_at,
                None,
                None,
            )?;
            Ok(receipt.clone())
        }
        ProviderDispatch::LostAck => Ok(journal
            .mark_indeterminate(operation_id, outcome_at, "provider_ack_lost")?
            .clone()),
        ProviderDispatch::KnownFailure(proof) => Ok(journal
            .transition(
                operation_id,
                EffectState::Failed,
                outcome_at,
                Some(proof),
                Some(REFERENCE_ALERT_FAILURE_REASON.to_owned()),
            )?
            .clone()),
        ProviderDispatch::ConflictingIdempotency => Err(ReferenceError::Contract(
            fss_core::ContractError::IdempotencyConflict,
        )),
    }
}

/// Records an independent observation of an adapter-accepted alert.
pub fn observe_reference_alert(
    plan: &ReferenceAlertPlan,
    observation_proof: ContentDigest,
    observed_at: TimestampNs,
    journal: &mut EffectJournal,
    provider: &ReferenceAlertProvider,
) -> Result<OperationReceipt, ReferenceError> {
    validate_reference_alert_plan(plan)?;
    let Some(provider_receipt) = provider.lookup(&plan.intent)? else {
        return Err(ReferenceError::InvalidSpec("provider_proof_missing"));
    };
    if observation_proof != provider_receipt.receipt_digest() {
        return Err(ReferenceError::Contract(
            fss_core::ContractError::InvalidDigest,
        ));
    }
    let receipt = journal.transition(
        &plan.intent.operation_id,
        EffectState::Observed,
        observed_at,
        Some(observation_proof),
        None,
    )?;
    Ok(receipt.clone())
}

/// Verifies an observed alert using terminal proof witness.
pub fn verify_reference_alert(
    plan: &ReferenceAlertPlan,
    verified_at: TimestampNs,
    journal: &mut EffectJournal,
    provider: &ReferenceAlertProvider,
) -> Result<OperationReceipt, ReferenceError> {
    validate_reference_alert_plan(plan)?;
    let Some(provider_receipt) = provider.lookup(&plan.intent)? else {
        return Err(ReferenceError::InvalidSpec("provider_proof_missing"));
    };
    let receipt = journal.reconcile_verified(
        &plan.intent.operation_id,
        provider_receipt.receipt_digest(),
        verified_at,
    )?;
    Ok(receipt.clone())
}

/// Reconciles an indeterminate alert to terminal failure using an independent failure proof.
pub fn reconcile_failed_reference_alert(
    plan: &ReferenceAlertPlan,
    proof_digest: ContentDigest,
    reason: impl Into<String>,
    now: TimestampNs,
    journal: &mut EffectJournal,
    provider: &ReferenceAlertProvider,
) -> Result<OperationReceipt, ReferenceError> {
    validate_reference_alert_plan(plan)?;
    if provider.lookup(&plan.intent)?.is_some() {
        return Err(ReferenceError::Contract(
            fss_core::ContractError::InvalidEffectTransition,
        ));
    }
    let Some(failure_receipt) = provider.lookup_failure(&plan.intent)? else {
        return Err(ReferenceError::InvalidSpec(
            "provider_failure_proof_missing",
        ));
    };
    if proof_digest != failure_receipt.receipt_digest() {
        return Err(ReferenceError::Contract(
            fss_core::ContractError::InvalidDigest,
        ));
    }
    let reason_str = reason.into();
    if reason_str != failure_receipt.error_code {
        return Err(ReferenceError::InvalidSpec(
            "provider_failure_reason_mismatch",
        ));
    }
    let receipt =
        journal.reconcile_failed(&plan.intent.operation_id, proof_digest, now, reason_str)?;
    Ok(receipt.clone())
}

/// Reconciles an indeterminate alert from independent provider state without resending it.
///
/// `Ok(None)` means no positive terminal proof is currently available; the operation intentionally
/// remains indeterminate rather than being guessed failed.
pub fn reconcile_reference_alert(
    plan: &ReferenceAlertPlan,
    now: TimestampNs,
    journal: &mut EffectJournal,
    provider: &ReferenceAlertProvider,
) -> Result<Option<OperationReceipt>, ReferenceError> {
    validate_reference_alert_plan(plan)?;
    let Some(provider_receipt) = provider.lookup(&plan.intent)? else {
        return Ok(None);
    };
    let op = &plan.intent.operation_id;
    let current_state = journal
        .operation(op)
        .map(|r| r.state)
        .ok_or(fss_core::ContractError::NotFound)?;

    match current_state {
        EffectState::Verified => {
            let receipt = journal.reconcile_verified(op, provider_receipt.receipt_digest(), now)?;
            Ok(Some(receipt.clone()))
        }
        EffectState::Observed => {
            let receipt = journal.reconcile_verified(op, provider_receipt.receipt_digest(), now)?;
            Ok(Some(receipt.clone()))
        }
        EffectState::Indeterminate => {
            let obs_time = now;
            let ver_time = TimestampNs(now.0.saturating_add(1));
            journal.transition(
                op,
                EffectState::Observed,
                obs_time,
                Some(provider_receipt.receipt_digest()),
                None,
            )?;
            let receipt =
                journal.reconcile_verified(op, provider_receipt.receipt_digest(), ver_time)?;
            Ok(Some(receipt.clone()))
        }
        _ => Err(ReferenceError::Contract(
            fss_core::ContractError::InvalidEffectTransition,
        )),
    }
}

fn alert_request_digest(event_receipt: &ReferenceEventReceipt, channel: &str) -> ContentDigest {
    alert_request_digest_parts(
        event_receipt.event_root,
        event_receipt.event_revision_digest,
        channel,
    )
}

fn alert_request_digest_parts(
    event_root: ContentDigest,
    event_revision_digest: ContentDigest,
    channel: &str,
) -> ContentDigest {
    let mut encoder = CanonicalEncoder::new();
    encoder.text("fss.reference_alert_request.v1");
    encoder.digest(event_root);
    encoder.digest(event_revision_digest);
    encoder.text(channel);
    ContentDigest::sha256(&encoder.finish())
}

pub(crate) fn validate_reference_alert_plan(
    plan: &ReferenceAlertPlan,
) -> Result<(), ReferenceError> {
    if plan.channel.is_empty()
        || plan.channel.len() > MAX_ALERT_CHANNEL_BYTES
        || plan.intent.effect_class != "alert.dispatch"
        || plan.intent.request_digest
            != alert_request_digest_parts(
                plan.event_root,
                plan.event_revision_digest,
                &plan.channel,
            )
    {
        return Err(ReferenceError::InvalidSpec("alert_plan_integrity"));
    }
    Ok(())
}

fn alert_precondition_digest(
    decision: &ReferencePolicyDecision,
    event_receipt: &ReferenceEventReceipt,
) -> ContentDigest {
    let mut encoder = CanonicalEncoder::new();
    encoder.text("fss.reference_alert_precondition.v1");
    encoder.digest(event_receipt.event_revision_digest);
    event_receipt
        .authority_anchor
        .encode_canonical(&mut encoder);
    encoder.text(decision.event.state.as_str());
    encoder.digest(decision.event.decision_path.fingerprint);
    ContentDigest::sha256(&encoder.finish())
}

pub(crate) fn reference_alert_terminal_proof_bytes(
    plan: &ReferenceAlertPlan,
    receipt: &OperationReceipt,
    provider: &ReferenceAlertProvider,
) -> Result<Option<Vec<u8>>, ReferenceError> {
    if receipt.intent != plan.intent {
        return Err(ReferenceError::InvalidSpec("alert_outcome_operation"));
    }
    match receipt.state {
        EffectState::Verified => {
            let provider_receipt = provider
                .lookup(&receipt.intent)?
                .ok_or(ReferenceError::InvalidSpec("provider_proof_missing"))?;
            let bytes = provider_receipt.canonical_bytes();
            if receipt.result_digest != Some(ContentDigest::sha256(&bytes)) {
                return Err(ReferenceError::InvalidSpec("alert_outcome_proof"));
            }
            Ok(Some(bytes))
        }
        EffectState::Failed => {
            let Some(reason) = receipt.error_code.as_deref().filter(|s| !s.is_empty()) else {
                return Err(ReferenceError::InvalidSpec("alert_outcome_proof"));
            };
            let failure_receipt =
                provider
                    .lookup_failure(&receipt.intent)?
                    .ok_or(ReferenceError::InvalidSpec(
                        "provider_failure_proof_missing",
                    ))?;
            if failure_receipt.error_code != reason {
                return Err(ReferenceError::InvalidSpec("alert_outcome_proof"));
            }
            let bytes = failure_receipt.canonical_bytes();
            if receipt.result_digest != Some(failure_receipt.receipt_digest()) {
                return Err(ReferenceError::InvalidSpec("alert_outcome_proof"));
            }
            Ok(Some(bytes))
        }
        EffectState::Indeterminate => {
            let Some(_reason) = receipt.error_code.as_deref().filter(|s| !s.is_empty()) else {
                return Err(ReferenceError::InvalidSpec("alert_outcome_proof"));
            };
            if receipt.result_digest.is_some() {
                return Err(ReferenceError::InvalidSpec("alert_outcome_proof"));
            }
            Ok(None)
        }
        _ => Err(ReferenceError::InvalidSpec("alert_outcome_not_publishable")),
    }
}
