//! Deterministic virtual-camera source truth.

use fss_core::{
    CanonicalEncode, CanonicalEncoder, CaptureInterval, CapsuleId, ContentDigest, SensorId,
    TimestampNs,
};

use crate::ReferenceError;

/// Maximum packets generated by one reference capture.
pub const MAX_VIRTUAL_PACKETS: u32 = 65_536;
/// Maximum source payload bytes per virtual packet.
pub const MAX_VIRTUAL_PACKET_BYTES: usize = 4_096;

/// Immutable specification for one deterministic virtual-camera capture.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct VirtualCameraSpec {
    /// Stable capture identity used by the authority object.
    pub capture_id: CapsuleId,
    /// Stable configured sensor identity.
    pub sensor_id: SensorId,
    /// Deterministic payload seed.
    pub seed: u64,
    /// Number of source packets.
    pub packet_count: u32,
    /// Exact payload bytes per source packet.
    pub packet_bytes: usize,
    /// Earliest time of source packet one.
    pub start_ns: i128,
    /// Nominal spacing between source packets.
    pub period_ns: u64,
    /// Conservative capture uncertainty added to each earliest time.
    pub uncertainty_ns: u64,
}

impl VirtualCameraSpec {
    /// Validates one bounded deterministic capture specification.
    pub fn validate(&self) -> Result<(), ReferenceError> {
        if self.packet_count == 0 || self.packet_count > MAX_VIRTUAL_PACKETS {
            return Err(ReferenceError::InvalidSpec("packet_count"));
        }
        if self.packet_bytes == 0 || self.packet_bytes > MAX_VIRTUAL_PACKET_BYTES {
            return Err(ReferenceError::InvalidSpec("packet_bytes"));
        }
        if self.period_ns == 0 {
            return Err(ReferenceError::InvalidSpec("period_ns"));
        }
        Ok(())
    }
}

/// Exact source packet produced before transport faults are applied.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SourcePacket {
    /// Sensor that produced the packet.
    pub sensor_id: SensorId,
    /// Monotone one-based source sequence.
    pub sequence: u64,
    /// Conservative source capture interval.
    pub capture: CaptureInterval,
    /// Exact source bytes.
    pub bytes: Vec<u8>,
    /// SHA-256 identity of exact source bytes.
    pub digest: ContentDigest,
}

/// Canonical ordered metadata for an entire source capture.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct SourceTrace {
    sensor_id: SensorId,
    capture_id: CapsuleId,
    packets: Vec<SourcePacketSummary>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct SourcePacketSummary {
    sequence: u64,
    capture: CaptureInterval,
    digest: ContentDigest,
}

impl SourceTrace {
    pub(crate) fn from_packets(
        spec: &VirtualCameraSpec,
        packets: &[SourcePacket],
    ) -> Self {
        Self {
            sensor_id: spec.sensor_id.clone(),
            capture_id: spec.capture_id.clone(),
            packets: packets
                .iter()
                .map(|packet| SourcePacketSummary {
                    sequence: packet.sequence,
                    capture: packet.capture,
                    digest: packet.digest,
                })
                .collect(),
        }
    }
}

impl CanonicalEncode for SourceTrace {
    fn encode_canonical(&self, encoder: &mut CanonicalEncoder) {
        encoder.text("fss.virtual_source_trace.v1");
        self.capture_id.encode_canonical(encoder);
        self.sensor_id.encode_canonical(encoder);
        encoder.u64(self.packets.len() as u64);
        for packet in &self.packets {
            encoder.u64(packet.sequence);
            packet.capture.encode_canonical(encoder);
            encoder.digest(packet.digest);
        }
    }
}

/// Generates exact source packets for a validated virtual-camera specification.
pub fn generate_source(spec: &VirtualCameraSpec) -> Result<Vec<SourcePacket>, ReferenceError> {
    spec.validate()?;

    let sensor_hash = ContentDigest::sha256(spec.sensor_id.as_str().as_bytes()).bytes();
    let mut prefix = [0_u8; 8];
    prefix.copy_from_slice(&sensor_hash[..8]);
    let mut state = spec.seed
        ^ u64::from_be_bytes(prefix)
        ^ 0x9e37_79b9_7f4a_7c15_u64;
    if state == 0 {
        state = 0xd1b5_4a32_d192_ed03_u64;
    }

    let mut packets = Vec::with_capacity(spec.packet_count as usize);
    for index in 0..spec.packet_count {
        let sequence = u64::from(index) + 1;
        let offset = i128::from(index)
            .checked_mul(i128::from(spec.period_ns))
            .ok_or(ReferenceError::ArithmeticOverflow)?;
        let earliest = spec
            .start_ns
            .checked_add(offset)
            .ok_or(ReferenceError::ArithmeticOverflow)?;
        let latest = earliest
            .checked_add(i128::from(spec.uncertainty_ns))
            .ok_or(ReferenceError::ArithmeticOverflow)?;
        let capture = CaptureInterval::new(TimestampNs(earliest), TimestampNs(latest))?;

        state ^= sequence.wrapping_mul(0xa076_1d64_78bd_642f_u64);
        let mut bytes = Vec::with_capacity(spec.packet_bytes);
        while bytes.len() < spec.packet_bytes {
            state = xorshift64(state);
            for byte in state.to_be_bytes() {
                if bytes.len() == spec.packet_bytes {
                    break;
                }
                bytes.push(byte);
            }
        }
        let digest = ContentDigest::sha256(&bytes);
        packets.push(SourcePacket {
            sensor_id: spec.sensor_id.clone(),
            sequence,
            capture,
            bytes,
            digest,
        });
    }
    Ok(packets)
}

fn xorshift64(mut value: u64) -> u64 {
    value ^= value << 13;
    value ^= value >> 7;
    value ^= value << 17;
    value
}
