//! Deterministic virtual-camera source truth.

use fss_core::{
    CanonicalEncode, CanonicalEncoder, CapsuleId, CaptureInterval, ContentDigest,
    IndeterminateDetail, OperationError, OperationOutcome, RefusalDetail, SensorId,
};

use crate::{ReferenceError, VirtualClock};

/// Maximum packets generated by one reference capture.
pub const MAX_VIRTUAL_PACKETS: u32 = 65_536;
/// Maximum source payload bytes per virtual packet.
pub const MAX_VIRTUAL_PACKET_BYTES: usize = 4_096;

/// Immutable specification for one deterministic virtual-camera capture.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct VirtualCameraSpec {
    /// Stable capture identity used by the authority object.
    pub capture_id: CapsuleId,
    /// Stable configured sensor identity.
    pub sensor_id: SensorId,
    /// Deterministic payload seed.
    pub seed: u64,
    /// Number of source packets.
    pub packet_count: u32,
    /// Exact payload bytes per source packet.
    pub packet_bytes: usize,
    /// Earliest time of source packet one.
    pub start_ns: i128,
    /// Nominal spacing between source packets.
    pub period_ns: u64,
    /// Conservative capture uncertainty added to each earliest time.
    pub uncertainty_ns: u64,
}

impl VirtualCameraSpec {
    /// Validates one bounded deterministic capture specification.
    pub fn validate(&self) -> Result<(), ReferenceError> {
        if self.packet_count == 0 || self.packet_count > MAX_VIRTUAL_PACKETS {
            return Err(ReferenceError::InvalidSpec("packet_count"));
        }
        if self.packet_bytes == 0 || self.packet_bytes > MAX_VIRTUAL_PACKET_BYTES {
            return Err(ReferenceError::InvalidSpec("packet_bytes"));
        }
        if self.period_ns == 0 {
            return Err(ReferenceError::InvalidSpec("period_ns"));
        }
        Ok(())
    }
}

/// Exact source packet produced before transport faults are applied.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SourcePacket {
    /// Sensor that produced the packet.
    pub sensor_id: SensorId,
    /// Monotone one-based source sequence.
    pub sequence: u64,
    /// Conservative source capture interval.
    pub capture: CaptureInterval,
    /// Exact source bytes.
    pub bytes: Vec<u8>,
    /// SHA-256 identity of exact source bytes.
    pub digest: ContentDigest,
}

/// Canonical ordered metadata for an entire source capture.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct SourceTrace {
    sensor_id: SensorId,
    capture_id: CapsuleId,
    packets: Vec<SourcePacketSummary>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct SourcePacketSummary {
    sequence: u64,
    capture: CaptureInterval,
    digest: ContentDigest,
}

impl SourceTrace {
    pub(crate) fn from_packets(spec: &VirtualCameraSpec, packets: &[SourcePacket]) -> Self {
        Self {
            sensor_id: spec.sensor_id.clone(),
            capture_id: spec.capture_id.clone(),
            packets: packets
                .iter()
                .map(|packet| SourcePacketSummary {
                    sequence: packet.sequence,
                    capture: packet.capture,
                    digest: packet.digest,
                })
                .collect(),
        }
    }
}

impl CanonicalEncode for SourceTrace {
    fn encode_canonical(&self, encoder: &mut CanonicalEncoder) {
        encoder.text("fss.virtual_source_trace.v1");
        self.capture_id.encode_canonical(encoder);
        self.sensor_id.encode_canonical(encoder);
        encoder.u64(self.packets.len() as u64);
        for packet in &self.packets {
            encoder.u64(packet.sequence);
            packet.capture.encode_canonical(encoder);
            encoder.digest(packet.digest);
        }
    }
}

/// Generates exact source packets for a validated virtual-camera specification.
pub fn generate_source(spec: &VirtualCameraSpec) -> Result<Vec<SourcePacket>, ReferenceError> {
    let mut source = VirtualSource::new(spec.clone())?;
    source.generate_packets()
}

/// Generates source packets using an explicit virtual clock authority.
pub fn generate_source_with_clock(
    spec: &VirtualCameraSpec,
    clock: VirtualClock,
) -> Result<Vec<SourcePacket>, ReferenceError> {
    let mut source = VirtualSource::with_clock(spec.clone(), clock)?;
    source.generate_packets()
}

/// Deterministic virtual sensor source driven by an explicit [`VirtualClock`].
#[derive(Clone, Debug)]
pub struct VirtualSource {
    spec: VirtualCameraSpec,
    clock: VirtualClock,
    current_sequence: u64,
    pending_indeterminate: bool,
    payload_state: u64,
    indeterminate_faults: std::collections::BTreeMap<u64, String>,
    unobservable_faults: std::collections::BTreeMap<u64, String>,
    execution_failure_faults: std::collections::BTreeMap<u64, String>,
}

impl VirtualSource {
    /// Creates a virtual source with a fresh deterministic virtual clock derived from the spec.
    pub fn new(spec: VirtualCameraSpec) -> Result<Self, ReferenceError> {
        spec.validate()?;
        let clock = VirtualClock::from_spec(&spec);
        Self::with_clock(spec, clock)
    }

    /// Creates a virtual source with an explicit time authority clock.
    pub fn with_clock(
        spec: VirtualCameraSpec,
        clock: VirtualClock,
    ) -> Result<Self, ReferenceError> {
        spec.validate()?;
        let sensor_hash = ContentDigest::sha256(spec.sensor_id.as_str().as_bytes()).bytes();
        let mut prefix = [0_u8; 8];
        prefix.copy_from_slice(&sensor_hash[..8]);
        let mut payload_state = spec.seed ^ u64::from_be_bytes(prefix) ^ 0x9e37_79b9_7f4a_7c15_u64;
        if payload_state == 0 {
            payload_state = 0xd1b5_4a32_d192_ed03_u64;
        }
        Ok(Self {
            spec,
            clock,
            current_sequence: 0,
            pending_indeterminate: false,
            payload_state,
            indeterminate_faults: std::collections::BTreeMap::new(),
            unobservable_faults: std::collections::BTreeMap::new(),
            execution_failure_faults: std::collections::BTreeMap::new(),
        })
    }

    /// Returns a reference to the underlying virtual clock.
    #[must_use]
    pub const fn clock(&self) -> &VirtualClock {
        &self.clock
    }

    /// Returns a mutable reference to the underlying virtual clock.
    pub fn clock_mut(&mut self) -> &mut VirtualClock {
        &mut self.clock
    }

    /// Returns the active virtual camera specification.
    #[must_use]
    pub const fn spec(&self) -> &VirtualCameraSpec {
        &self.spec
    }

    /// Returns the current 1-based sequence number of the last emitted packet (or 0 if none).
    #[must_use]
    pub const fn current_sequence(&self) -> u64 {
        self.current_sequence
    }

    /// Injects an indeterminate read outcome on the specified 1-based packet sequence.
    pub fn inject_indeterminate_read(&mut self, sequence: u64, reason: impl Into<String>) {
        self.indeterminate_faults.insert(sequence, reason.into());
    }

    /// Injects an unauthorized or unobservable outcome on the specified 1-based packet sequence.
    pub fn inject_unobservable_read(&mut self, sequence: u64, reason: impl Into<String>) {
        self.unobservable_faults.insert(sequence, reason.into());
    }

    /// Injects an operational execution failure on the specified 1-based packet sequence.
    pub fn inject_execution_failure(&mut self, sequence: u64, reason: impl Into<String>) {
        self.execution_failure_faults
            .insert(sequence, reason.into());
    }

    /// Clears an injected indeterminate read fault for the specified sequence.
    pub fn clear_indeterminate_read(&mut self, sequence: u64) -> Option<String> {
        self.indeterminate_faults.remove(&sequence)
    }

    /// Clears an injected unobservable read fault for the specified sequence.
    pub fn clear_unobservable_read(&mut self, sequence: u64) -> Option<String> {
        self.unobservable_faults.remove(&sequence)
    }

    /// Clears an injected execution failure fault for the specified sequence.
    pub fn clear_execution_failure(&mut self, sequence: u64) -> Option<String> {
        self.execution_failure_faults.remove(&sequence)
    }

    /// Emits the next capture interval through the virtual clock.
    ///
    /// Advances the clock by `period_ns` for all emissions after the first packet.
    /// Returns [`OperationOutcome::Success`] containing the conservative [`CaptureInterval`],
    /// or [`OperationOutcome::Indeterminate`], [`OperationOutcome::UnauthorizedOrNotObservable`],
    /// or [`OperationOutcome::Failed`] if a fault is triggered.
    pub fn emit_interval(&mut self) -> Result<OperationOutcome<CaptureInterval>, ReferenceError> {
        let sequence_to_attempt = if self.pending_indeterminate {
            self.current_sequence
        } else {
            let next = self.current_sequence + 1;
            if next > u64::from(self.spec.packet_count) {
                return Err(ReferenceError::UnknownSourceSequence(next));
            }
            if self.current_sequence > 0 {
                self.clock.advance(self.spec.period_ns)?;
            }
            self.current_sequence = next;
            next
        };

        if let Some(reason) = self.indeterminate_faults.get(&sequence_to_attempt) {
            self.pending_indeterminate = true;
            return Ok(OperationOutcome::indeterminate(IndeterminateDetail::new(
                "virtual_source_capture",
                reason.clone(),
                "resnapshot sensor anchor and re-poll capture interval",
            )));
        }

        self.pending_indeterminate = false;

        if let Some(reason) = self.unobservable_faults.get(&sequence_to_attempt) {
            return Ok(OperationOutcome::unauthorized_or_not_observable(
                RefusalDetail::not_observable(reason.clone(), true),
            ));
        }
        if let Some(reason) = self.execution_failure_faults.get(&sequence_to_attempt) {
            return Ok(OperationOutcome::failed(OperationError::execution_failed(
                reason.clone(),
            )?));
        }

        let interval = self.clock.read_interval(self.spec.uncertainty_ns)?;
        Ok(OperationOutcome::success(interval))
    }

    /// Emits the next source packet with payload bytes and content digest.
    pub fn emit_packet(&mut self) -> Result<OperationOutcome<SourcePacket>, ReferenceError> {
        let outcome = self.emit_interval()?;
        match outcome {
            OperationOutcome::Success(capture) => {
                let sequence = self.current_sequence;
                self.payload_state ^= sequence.wrapping_mul(0xa076_1d64_78bd_642f_u64);
                let mut bytes = Vec::with_capacity(self.spec.packet_bytes);
                while bytes.len() < self.spec.packet_bytes {
                    self.payload_state = xorshift64(self.payload_state);
                    for byte in self.payload_state.to_be_bytes() {
                        if bytes.len() == self.spec.packet_bytes {
                            break;
                        }
                        bytes.push(byte);
                    }
                }
                let digest = ContentDigest::sha256(&bytes);
                let packet = SourcePacket {
                    sensor_id: self.spec.sensor_id.clone(),
                    sequence,
                    capture,
                    bytes,
                    digest,
                };
                Ok(OperationOutcome::success(packet))
            }
            OperationOutcome::Failed(err) => Ok(OperationOutcome::failed(err)),
            OperationOutcome::Indeterminate(detail) => Ok(OperationOutcome::indeterminate(detail)),
            OperationOutcome::UnauthorizedOrNotObservable(refusal) => {
                Ok(OperationOutcome::unauthorized_or_not_observable(refusal))
            }
        }
    }

    /// Generates all source packets for the virtual camera specification.
    ///
    /// Any non-success outcome is returned as a typed [`ReferenceError`].
    pub fn generate_packets(&mut self) -> Result<Vec<SourcePacket>, ReferenceError> {
        let mut packets = Vec::with_capacity(self.spec.packet_count as usize);
        while self.current_sequence < u64::from(self.spec.packet_count)
            || self.pending_indeterminate
        {
            let outcome = self.emit_packet()?;
            match outcome {
                OperationOutcome::Success(packet) => packets.push(packet),
                OperationOutcome::Failed(err) => {
                    return Err(ReferenceError::ExecutionFailedSourceCapture {
                        sequence: self.current_sequence,
                        reason: err.message,
                    });
                }
                OperationOutcome::Indeterminate(detail) => {
                    return Err(ReferenceError::IndeterminateSourceCapture {
                        sequence: self.current_sequence,
                        reason: detail.reason,
                    });
                }
                OperationOutcome::UnauthorizedOrNotObservable(refusal) => {
                    return Err(ReferenceError::UnobservableSourceCapture {
                        sequence: self.current_sequence,
                        reason: refusal.message,
                    });
                }
            }
        }
        Ok(packets)
    }
}

fn xorshift64(mut value: u64) -> u64 {
    value ^= value << 13;
    value ^= value >> 7;
    value ^= value << 17;
    value
}
