#![forbid(unsafe_code)]
//! Contract tests for the `0xCC51` wire layer and XXTEA, using vectors
//! generated by the live-proven Python reference (LAB-2026-10-07) plus the
//! public doc's own PSK NUL-truncation example.

use fss_tutk::wire::{
    auth_key, derive_psk, derive_psk_truncated, new_session_id, NewProto, CHANNEL_MAIN,
};
use fss_tutk::xxtea::{challenge_response, decrypt, encrypt, ChallengeKey};

const UID: &str = "SIMCAMSIMCAMSIMCAM11";
const ENR: &str = "sim-enr-16byte!!";
const MAC: &str = "00AA11BB22CC";

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

#[test]
fn authkey_matches_python_reference() {
    assert_eq!(std::str::from_utf8(&auth_key(ENR, MAC)).unwrap(), "vW28cYGv");
}

#[test]
fn psk_derivations() {
    assert_eq!(
        hex(&derive_psk(ENR)),
        "14e4c91457f21664b7c1d2a48a0a042254751cca085662050dba5f4b5ad38839"
    );
    assert_eq!(
        hex(&derive_psk_truncated(ENR)),
        "14e4c91457f21664b7c1d2a48a0a042254751cca085662050dba5f4b5ad38839"
    );
    // the public doc's NUL-truncation example (PSK length 11, zero-padded)
    let psk = derive_psk("GkB9S7cX38GgzSC6");
    assert_eq!(
        hex(&psk),
        "16549c533b4e9812808f91000000000000000000000000000000000000000000"
    );
    let trunc = derive_psk_truncated("GkB9S7cX38GgzSC6");
    assert_eq!(hex(&trunc), "16549c533b4e9812808f91");
}

#[test]
fn discovery_packet_exact_bytes() {
    let sid = new_session_id([0x1c, 0x24]);
    assert_eq!(hex(&sid), "1c24760a9d2488ba");
    let proto = NewProto::new(UID, ENR, MAC).expect("valid uid");
    let pkt = proto.build_discovery(0, 0, &sid).expect("build");
    assert_eq!(
        hex(&pkt),
        "51cc00000210280000000000000000001c24760a9d2488ba000803041d0000009eb97cc8ef722832eb3597d189ee3b1f4a14b61e"
    );
    // round-trip: parse sees the same fields and a valid auth trailer
    let parsed = proto.parse_discovery(&pkt).expect("parse");
    assert_eq!(parsed.seq, 0);
    assert_eq!(parsed.ticket, 0);
    assert_eq!(parsed.session_id, sid);
    assert!(parsed.auth_ok);
}

#[test]
fn discovery_response_and_keepalive() {
    let sid = new_session_id([0x1c, 0x24]);
    let proto = NewProto::new(UID, ENR, MAC).expect("valid uid");
    let ka = proto.build_keepalive_echo(42, &sid);
    assert_eq!(
        hex(&ka),
        "51cc00000212240000000000000000002a0000001c24760a9d2488bacd5d46600e30eb06626d7ae0e488c42e834652a4"
    );
    let (counter, ksid, auth_ok) = proto.parse_keepalive(&ka).expect("parse");
    assert_eq!(counter, 42);
    assert_eq!(ksid, sid);
    assert!(auth_ok);
}

#[test]
fn dtls_wrapper_exact_bytes() {
    let sid = new_session_id([0x1c, 0x24]);
    let proto = NewProto::new(UID, ENR, MAC).expect("valid uid");
    let wrapped = proto.wrap_dtls(&unhex("16fefd0000"), 0x05e0, &sid, CHANNEL_MAIN);
    assert_eq!(
        hex(&wrapped),
        "51cc000002152900000000001000e0051c24760a9d2488ba0100000016fefd00009efef5d660606309a7ba11b23b80ed4cb5199eb4"
    );
    let (payload, auth_ok, channel) = proto.unwrap_dtls(&wrapped, true).expect("unwrap");
    assert_eq!(hex(payload), "16fefd0000");
    assert!(auth_ok);
    assert_eq!(channel, CHANNEL_MAIN);
}

#[test]
fn unwrap_rejects_tampered_payload_size() {
    let sid = new_session_id([0x1c, 0x24]);
    let proto = NewProto::new(UID, ENR, MAC).expect("valid uid");
    let mut wrapped = proto.wrap_dtls(&unhex("16fefd0000"), 0x05e0, &sid, CHANNEL_MAIN);
    wrapped[7] ^= 0xFF; // payload-size field
    assert!(proto.unwrap_dtls(&wrapped, false).is_err());
}

#[test]
fn xxtea_vectors_from_python_reference() {
    let c = encrypt(&unhex("0011223344556677"), b"0123456789abcdef").expect("enc");
    assert_eq!(hex(&c), "910d06dd55597012");
    let p = decrypt(&c, b"0123456789abcdef").expect("dec");
    assert_eq!(hex(&p), "0011223344556677");

    let c16 = encrypt(&unhex("000102030405060708090a0b0c0d0e0f"), b"0123456789abcdef").expect("enc16");
    assert_eq!(hex(&c16), "8d9ed214cc86fe675ca1c4ba9a70aca5");
    let p16 = decrypt(&c16, b"0123456789abcdef").expect("dec16");
    assert_eq!(hex(&p16), "000102030405060708090a0b0c0d0e0f");
}

#[test]
fn challenge_response_modes() {
    let ch = unhex("00e1d2c3b4a5968778695a4b3c2d1e0f");
    let enr = "0123456789abcdef0123456789abcdef";
    assert_eq!(
        hex(&challenge_response(ChallengeKey::Default, &ch, enr).expect("s1")),
        "91263c38706f6d75c5d0835ab2003366"
    );
    assert_eq!(
        hex(&challenge_response(ChallengeKey::Enr, &ch, enr).expect("s3")),
        "29ecfbc95fdbb2e20db33eeff528daa4"
    );
    assert_eq!(
        hex(&challenge_response(ChallengeKey::EnrDouble, &ch, enr).expect("s6")),
        "fbcce3120a41d045950880f491675821"
    );
}

#[test]
fn round_trip_randomized() {
    // deterministic PRNG so failures reproduce
    let mut state = 0x1234_5678_9abc_def0u64;
    let mut next = || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        (state >> 33) as u8
    };
    for len in [8usize, 12, 16, 20, 32, 64] {
        let data: Vec<u8> = (0..len).map(|_| next()).collect();
        let mut key = [0u8; 16];
        for k in key.iter_mut() {
            *k = next();
        }
        let c = encrypt(&data, &key).expect("enc");
        let p = decrypt(&c, &key).expect("dec");
        assert_eq!(p, data, "round trip failed at len {len}");
    }
}
